"""Immutable PLC Engine.

Redux-style architecture where logic is a pure function:
    Logic(Current_State) -> Next_State

Uses ScanContext for batched updates within a scan cycle,
reducing object allocation from O(instructions) to O(1) per scan.
"""

from pyrung.core.analysis import DataView, ProgramGraph, TagRole, TagVersion, build_program_graph
from pyrung.core.compiled_plc import CompiledPLC
from pyrung.core.context import ScanContext
from pyrung.core.copy_converters import to_ascii, to_binary, to_text, to_value
from pyrung.core.debug_trace import RungTrace, RungTraceEvent
from pyrung.core.expression import (
    PI,
    Expression,
    acos,
    asin,
    atan,
    cos,
    degrees,
    log,
    log10,
    lro,
    lsh,
    radians,
    rro,
    rsh,
    sin,
    sqrt,
    tan,
)
from pyrung.core.harness import Harness, profile
from pyrung.core.instruction.send_receive import (
    ModbusAddress,
    ModbusRtuTarget,
    ModbusTcpTarget,
    RegisterType,
    WordOrder,
    receive,
    send,
)
from pyrung.core.memory_block import (
    Block,
    BlockRange,
    IndirectBlockRange,
    IndirectExprRef,
    IndirectRef,
    InputBlock,
    OutputBlock,
    RangeComparison,
    RangeSlotView,
    SlotView,
)
from pyrung.core.physical import Physical, parse_duration
from pyrung.core.program import (
    And,
    ForbiddenControlFlowError,
    ForLoop,
    Or,
    Program,
    Rung,
    SubroutineFunc,
    blockcopy,
    branch,
    calc,
    call,
    comment,
    copy,
    count_down,
    count_up,
    event_drum,
    fall,
    fill,
    forloop,
    latch,
    off_delay,
    on_delay,
    out,
    pack_bits,
    pack_text,
    pack_words,
    program,
    reset,
    return_early,
    rise,
    run_enabled_function,
    run_function,
    search,
    shift,
    subroutine,
    time_drum,
    unpack_to_bits,
    unpack_to_words,
)
from pyrung.core.runner import PLC
from pyrung.core.state import SystemState
from pyrung.core.structure import (
    AutoDefault,
    Counter,
    DoneAccUDT,
    Field,
    InstanceView,
    Timer,
    auto,
    named_array,
    udt,
)
from pyrung.core.system_points import system
from pyrung.core.tag import (
    Bool,
    Char,
    Dint,
    ImmediateRef,
    InputTag,
    Int,
    OutputTag,
    Real,
    Tag,
    TagType,
    Word,
    immediate,
)
from pyrung.core.time_mode import (  # noqa: F401 (TimeMode importable but not in __all__)
    TimeMode,
    TimeUnit,
    normalize_unit,
)

__all__ = [
    "PLC",
    "CompiledPLC",
    "ScanContext",
    "SystemState",
    "DataView",
    "ProgramGraph",
    "RungTrace",
    "RungTraceEvent",
    "TagRole",
    "system",
    "TagVersion",
    "TimeUnit",
    "build_program_graph",
    "normalize_unit",
    # Physical feedback
    "Physical",
    "parse_duration",
    # Autoharness
    "Harness",
    "profile",
    # Structured factories
    "DoneAccUDT",
    "Field",
    "AutoDefault",
    "auto",
    "udt",
    "named_array",
    "InstanceView",
    "Timer",
    "Counter",
    # Tags (IEC 61131-3 names)
    "Tag",
    "TagType",
    "Bool",
    "Int",
    "Dint",
    "Real",
    "Char",
    "Word",
    "InputTag",
    "OutputTag",
    "ImmediateRef",
    "immediate",
    # Memory blocks
    "Block",
    "InputBlock",
    "OutputBlock",
    "BlockRange",
    "IndirectBlockRange",
    "IndirectRef",
    "IndirectExprRef",
    "RangeComparison",
    "RangeSlotView",
    "SlotView",
    # Program structure
    "Program",
    "Rung",
    "SubroutineFunc",
    "ForLoop",
    "ForbiddenControlFlowError",
    "comment",
    "program",
    "branch",
    "forloop",
    "subroutine",
    # Instructions
    "out",
    "latch",
    "reset",
    "copy",
    "run_function",
    "run_enabled_function",
    "blockcopy",
    "fill",
    "pack_bits",
    "pack_text",
    "pack_words",
    "unpack_to_bits",
    "unpack_to_words",
    "calc",
    "call",
    "return_early",
    "count_up",
    "count_down",
    "event_drum",
    "search",
    "shift",
    "on_delay",
    "off_delay",
    "time_drum",
    "send",
    "receive",
    "ModbusAddress",
    "ModbusRtuTarget",
    "ModbusTcpTarget",
    "RegisterType",
    "WordOrder",
    # Conditions
    "rise",
    "fall",
    "And",
    "Or",
    # Copy converters
    "to_value",
    "to_ascii",
    "to_text",
    "to_binary",
    # Expressions
    "Expression",
    "PI",
    "sqrt",
    "sin",
    "cos",
    "tan",
    "asin",
    "acos",
    "atan",
    "radians",
    "degrees",
    "log",
    "log10",
    "lsh",
    "rsh",
    "lro",
    "rro",
]
