"""Compiled replay runner built on top of ``CompiledKernel``.

``CompiledPLC`` is a replay-focused execution engine used to accelerate
historical reconstruction.  It mirrors the core scan semantics that
``PLC.replay_to()`` depends on while delegating rung execution to the
kernel code generated by ``compile_kernel()``.
"""

from __future__ import annotations

from collections.abc import Mapping
from contextlib import contextmanager
from datetime import datetime, timedelta
from typing import Any, cast

from pyrsistent import pmap

from pyrung.core.context import ScanContext
from pyrung.core.input_overrides import InputOverrideManager
from pyrung.core.kernel import CompiledKernel, ReplayKernel
from pyrung.core.state import SystemState
from pyrung.core.system_points import (
    _BATTERY_PRESENT_KEY,
    _DERIVED_TAG_NAMES,
    _MODE_RUN_KEY,
    READ_ONLY_SYSTEM_TAG_NAMES,
    SYSTEM_TAGS_BY_NAME,
    SystemPointRuntime,
)
from pyrung.core.tag import Tag
from pyrung.core.time_mode import TimeMode


class _KernelRuntimeContext:
    """Mutable tag/memory view for runtime hooks around one kernel scan."""

    __slots__ = ("_tags", "_memory", "_scan_id", "_timestamp")

    def __init__(
        self,
        *,
        tags: dict[str, Any],
        memory: dict[str, Any],
        scan_id: int,
        timestamp: float,
    ) -> None:
        self._tags = tags
        self._memory = memory
        self._scan_id = scan_id
        self._timestamp = timestamp

    def get_tag(self, name: str, default: Any = None) -> Any:
        return self._tags.get(name, default)

    def get_memory(self, key: str, default: Any = None) -> Any:
        return self._memory.get(key, default)

    def set_tag(self, name: str, value: Any) -> None:
        if name in READ_ONLY_SYSTEM_TAG_NAMES:
            raise ValueError(f"Tag '{name}' is read-only system point and cannot be written")
        self._tags[name] = value

    def set_tags(self, updates: dict[str, Any]) -> None:
        for name in updates:
            if name in READ_ONLY_SYSTEM_TAG_NAMES:
                raise ValueError(f"Tag '{name}' is read-only system point and cannot be written")
        self._tags.update(updates)

    def _set_tag_internal(self, name: str, value: Any) -> None:
        self._tags[name] = value

    def _set_tags_internal(self, updates: dict[str, Any]) -> None:
        self._tags.update(updates)

    def set_memory(self, key: str, value: Any) -> None:
        self._memory[key] = value

    def set_memory_bulk(self, updates: dict[str, Any]) -> None:
        self._memory.update(updates)

    def _get_tag_internal(self, name: str, default: Any = None) -> Any:
        return self._tags.get(name, default)

    def _has_tag_internal(self, name: str) -> bool:
        return name in self._tags

    def _get_memory_internal(self, key: str, default: Any = None) -> Any:
        return self._memory.get(key, default)

    def _has_memory_internal(self, key: str) -> bool:
        return key in self._memory

    @property
    def scan_id(self) -> int:
        return self._scan_id

    @property
    def timestamp(self) -> float:
        return self._timestamp


class CompiledPLC:
    """Fixed-step replay runner backed by a compiled kernel."""

    def __init__(
        self,
        program: Any,
        initial_state: SystemState | None = None,
        *,
        dt: float = 0.010,
        compiled: CompiledKernel | None = None,
    ) -> None:
        from pyrung.circuitpy.codegen.render_kernel import compile_kernel
        from pyrung.core.program import Program

        if not isinstance(program, Program):
            raise TypeError("CompiledPLC requires a Program")
        self._program = program
        self._compiled = compiled if compiled is not None else compile_kernel(program)
        self._kernel: ReplayKernel = self._compiled.create_kernel()
        self._dt = float(dt)
        self._time_mode = TimeMode.FIXED_STEP
        self._running = True
        self._battery_present = True
        self._rtc_base = self._normalize_rtc_datetime(datetime.now())
        self._rtc_base_sim_time = 0.0
        self._system_runtime = SystemPointRuntime(
            time_mode_getter=lambda: self._time_mode,
            fixed_step_dt_getter=lambda: self._dt,
            rtc_now_getter=self._rtc_at_sim_time,
            rtc_setter=self._set_rtc_internal,
        )
        self._input_overrides = InputOverrideManager(is_read_only=self._system_runtime.is_read_only)
        self._pending_patches = self._input_overrides.pending_patches
        self._forces = self._input_overrides.forces_mutable
        self._referenced_system_tags = frozenset(
            name for name in self._compiled.referenced_tags if name in SYSTEM_TAGS_BY_NAME
        )
        self._known_tags_by_name: dict[str, Tag] = {
            name: tag
            for name, tag in self._compiled.referenced_tags.items()
            if name not in SYSTEM_TAGS_BY_NAME
        }
        self._state = initial_state if initial_state is not None else SystemState()
        self._initialize_from_state(self._state)

        seed = {
            t.name: t.default
            for t in self._known_tags_by_name.values()
            if t.name not in self._state.tags
        }
        if seed:
            self._state = self._state.with_tags(seed)
            self._initialize_from_state(self._state)

    @property
    def current_state(self) -> SystemState:
        return self._state

    @property
    def simulation_time(self) -> float:
        return self._state.timestamp

    @property
    def forces(self) -> Mapping[str, bool | int | float | str]:
        return self._input_overrides.forces

    def patch(
        self,
        tags: Mapping[str, bool | int | float | str]
        | Mapping[Tag, bool | int | float | str]
        | Mapping[str | Tag, bool | int | float | str],
    ) -> None:
        self._input_overrides.patch(tags)

    def force(self, tag: str | Tag, value: bool | int | float | str) -> None:
        self._input_overrides.add_force(tag, value)

    def unforce(self, tag: str | Tag) -> None:
        self._input_overrides.remove_force(tag)

    def clear_forces(self) -> None:
        self._input_overrides.clear_forces()

    @contextmanager
    def forced(
        self,
        overrides: Mapping[str, bool | int | float | str]
        | Mapping[Tag, bool | int | float | str]
        | Mapping[str | Tag, bool | int | float | str],
    ):
        with self._input_overrides.force(overrides):
            yield self

    @property
    def battery_present(self) -> bool:
        return self._battery_present

    @battery_present.setter
    def battery_present(self, value: bool) -> None:
        self._battery_present = bool(value)
        self._kernel.memory[_BATTERY_PRESENT_KEY] = self._battery_present
        self._state = self._state.with_memory({_BATTERY_PRESENT_KEY: self._battery_present})

    def stop(self) -> None:
        if not self._running:
            return
        self._running = False
        self._kernel.memory[_MODE_RUN_KEY] = False
        self._state = self._state.with_memory({_MODE_RUN_KEY: False})

    def step(self) -> SystemState:
        self._ensure_running()

        ctx = _KernelRuntimeContext(
            tags=self._kernel.tags,
            memory=self._kernel.memory,
            scan_id=self._state.scan_id,
            timestamp=self._state.timestamp,
        )
        scan_ctx = cast(ScanContext, ctx)
        self._system_runtime.on_scan_start(scan_ctx)
        self._input_overrides.apply_pre_scan(scan_ctx)

        if self._kernel.memory.get("_dt") != self._dt:
            ctx.set_memory("_dt", self._dt)

        self._materialize_system_tags(ctx)

        for spec in self._compiled.block_specs.values():
            self._kernel.load_block_from_tags(spec)
        self._compiled.step_fn(
            self._kernel.tags,
            self._kernel.blocks,
            self._kernel.memory,
            self._kernel.prev,
            self._dt,
        )
        for spec in self._compiled.block_specs.values():
            self._kernel.flush_block_to_tags(spec)

        self._input_overrides.apply_post_logic(scan_ctx)
        self._capture_previous_states()
        self._system_runtime.on_scan_end(scan_ctx)

        next_state = SystemState(
            scan_id=self._state.scan_id + 1,
            timestamp=self._state.timestamp + self._dt,
            tags=pmap(self._committed_tags()),
            memory=pmap(dict(self._kernel.memory)),
        )
        self._kernel.scan_id = next_state.scan_id
        self._kernel.timestamp = next_state.timestamp
        self._state = next_state
        self._sync_runtime_flags_from_state()
        return self._state

    def run(self, cycles: int) -> SystemState:
        for _ in range(cycles):
            self.step()
        return self._state

    def run_for(self, seconds: float) -> SystemState:
        target_time = self._state.timestamp + seconds
        while self._state.timestamp < target_time:
            self.step()
        return self._state

    def set_rtc(self, value: datetime) -> None:
        self._set_rtc_internal(self._normalize_rtc_datetime(value), self._state.timestamp)

    def _initialize_from_state(self, state: SystemState) -> None:
        self._kernel = self._compiled.create_kernel()
        self._kernel.tags.update(dict(state.tags))
        self._kernel.memory.update(dict(state.memory))
        self._kernel.scan_id = state.scan_id
        self._kernel.timestamp = state.timestamp
        self._running = bool(self._kernel.memory.get(_MODE_RUN_KEY, True))
        self._battery_present = bool(self._kernel.memory.get(_BATTERY_PRESENT_KEY, True))
        self._kernel.memory.setdefault(_MODE_RUN_KEY, self._running)
        self._kernel.memory.setdefault(_BATTERY_PRESENT_KEY, self._battery_present)
        state_memory_defaults: dict[str, Any] = {}
        if _MODE_RUN_KEY not in self._state.memory:
            state_memory_defaults[_MODE_RUN_KEY] = self._running
        if _BATTERY_PRESENT_KEY not in self._state.memory:
            state_memory_defaults[_BATTERY_PRESENT_KEY] = self._battery_present
        if state_memory_defaults:
            self._state = self._state.with_memory(state_memory_defaults)
        for name in self._compiled.edge_tags:
            self._kernel.prev[name] = state.memory.get(
                f"_prev:{name}",
                state.tags.get(name, self._compiled.referenced_tags[name].default),
            )
        for spec in self._compiled.block_specs.values():
            self._kernel.load_block_from_tags(spec)

    def _materialize_system_tags(self, ctx: _KernelRuntimeContext) -> None:
        scan_ctx = cast(ScanContext, ctx)
        for name in self._referenced_system_tags:
            resolved, value = self._system_runtime.resolve(name, scan_ctx)
            if resolved:
                self._kernel.tags[name] = value

    def _capture_previous_states(self) -> None:
        committed_names = set(self._state.tags)
        committed_names.update(name for name in self._kernel.tags if name not in _DERIVED_TAG_NAMES)
        for name in committed_names:
            value = self._kernel.tags.get(name)
            self._kernel.memory[f"_prev:{name}"] = value
        for name in self._compiled.edge_tags:
            if name in self._kernel.tags:
                self._kernel.prev[name] = self._kernel.tags[name]

    def _committed_tags(self) -> dict[str, Any]:
        return {
            name: value
            for name, value in self._kernel.tags.items()
            if name not in _DERIVED_TAG_NAMES
        }

    def _ensure_running(self) -> None:
        if not self._running:
            self._stop_to_run_transition()

    def _stop_to_run_transition(self) -> None:
        if self._running:
            return
        tag_values = self._rebuild_tags_for_reset(preserve_all=False, preserve_retentive=True)
        self._reset_runtime_scope(
            tag_values=tag_values, mode_run=True, preserve_rtc_continuity=True
        )
        self._running = True

    def _rebuild_tags_for_reset(
        self,
        *,
        preserve_all: bool,
        preserve_retentive: bool,
    ) -> dict[str, Any]:
        current_tags = self._state.tags
        rebuilt: dict[str, Any] = {}
        for tag in self._known_tags_by_name.values():
            if preserve_all:
                rebuilt[tag.name] = current_tags.get(tag.name, tag.default)
                continue
            if preserve_retentive and tag.retentive and tag.name in current_tags:
                rebuilt[tag.name] = current_tags[tag.name]
                continue
            rebuilt[tag.name] = tag.default
        return rebuilt

    def _reset_runtime_scope(
        self,
        *,
        tag_values: Mapping[str, Any],
        mode_run: bool,
        preserve_rtc_continuity: bool,
    ) -> None:
        rtc_after_reset = (
            self._rtc_at_sim_time(self._state.timestamp)
            if preserve_rtc_continuity
            else self._normalize_rtc_datetime(datetime.now())
        )
        next_state = (
            SystemState()
            .with_tags(dict(tag_values))
            .with_memory(
                {
                    _MODE_RUN_KEY: bool(mode_run),
                    _BATTERY_PRESENT_KEY: bool(self._battery_present),
                }
            )
        )
        self._state = next_state
        self._initialize_from_state(self._state)
        self._set_rtc_internal(rtc_after_reset, self._state.timestamp)
        self._pending_patches.clear()
        self._forces.clear()

    def _sync_runtime_flags_from_state(self) -> None:
        self._running = bool(self._state.memory.get(_MODE_RUN_KEY, True))
        self._battery_present = bool(
            self._state.memory.get(_BATTERY_PRESENT_KEY, self._battery_present)
        )

    def _normalize_rtc_datetime(self, value: datetime) -> datetime:
        if value.tzinfo is None:
            return value
        return value.astimezone().replace(tzinfo=None)

    def _set_rtc_internal(self, value: datetime, sim_time: float) -> None:
        self._rtc_base = value
        self._rtc_base_sim_time = float(sim_time)

    def _rtc_at_sim_time(self, sim_time: float) -> datetime:
        return self._rtc_base + timedelta(seconds=float(sim_time) - self._rtc_base_sim_time)
