from __future__ import annotations

from enum import Enum
from typing import Any, ClassVar, Literal

from pyrung.core.condition import Condition
from pyrung.core.memory_block import Block, BlockRange
from pyrung.core.physical import Physical

class TagType(Enum):
    BOOL: TagType
    INT: TagType
    DINT: TagType
    REAL: TagType
    WORD: TagType
    CHAR: TagType

ChoiceKey = int | float | str
ChoiceMap = dict[ChoiceKey, str]

class MappingEntry:
    source: Tag | Block
    target: Tag | BlockRange
    def __init__(self, source: Tag | Block, target: Tag | BlockRange) -> None: ...

class Tag:
    name: str
    type: TagType
    default: Any
    retentive: bool
    comment: str
    choices: ChoiceMap | None
    readonly: bool
    external: bool
    final: bool
    public: bool
    physical: Physical | None
    link: str | None
    min: int | float | None
    max: int | float | None
    uom: str | None
    _pyrung_structure_runtime: Any | None
    _pyrung_structure_kind: Literal["udt", "named_array"] | None
    _pyrung_structure_name: str | None
    _pyrung_structure_field: str | None
    _pyrung_structure_index: int | None

    def __init__(
        self,
        name: str,
        type: TagType = TagType.BOOL,
        default: Any = None,
        retentive: bool = False,
        comment: str = "",
        choices: ChoiceMap | None = None,
        readonly: bool = False,
        external: bool = False,
        final: bool = False,
        public: bool = False,
        physical: Physical | None = None,
        link: str | None = None,
        min: int | float | None = None,
        max: int | float | None = None,
        uom: str | None = None,
    ) -> None: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> Condition: ...  # ty: ignore[invalid-method-override]
    def __ne__(self, other: object) -> Condition: ...  # ty: ignore[invalid-method-override]
    def __lt__(self, other: Any) -> Condition: ...
    def __le__(self, other: Any) -> Condition: ...
    def __gt__(self, other: Any) -> Condition: ...
    def __ge__(self, other: Any) -> Condition: ...
    def __or__(self, other: object) -> Any: ...
    def __ror__(self, other: Any) -> Any: ...
    def __bool__(self) -> bool: ...
    @property
    def value(self) -> Any: ...
    @value.setter
    def value(self, new_value: Any) -> None: ...
    def map_to(self, target: Tag) -> MappingEntry: ...
    def __add__(self, other: Any) -> Any: ...
    def __radd__(self, other: Any) -> Any: ...
    def __sub__(self, other: Any) -> Any: ...
    def __rsub__(self, other: Any) -> Any: ...
    def __mul__(self, other: Any) -> Any: ...
    def __rmul__(self, other: Any) -> Any: ...
    def __truediv__(self, other: Any) -> Any: ...
    def __rtruediv__(self, other: Any) -> Any: ...
    def __floordiv__(self, other: Any) -> Any: ...
    def __rfloordiv__(self, other: Any) -> Any: ...
    def __mod__(self, other: Any) -> Any: ...
    def __rmod__(self, other: Any) -> Any: ...
    def __pow__(self, other: Any) -> Any: ...
    def __rpow__(self, other: Any) -> Any: ...
    def __neg__(self) -> Any: ...
    def __pos__(self) -> Any: ...
    def __abs__(self) -> Any: ...
    def __and__(self, other: Any) -> Any: ...
    def __rand__(self, other: Any) -> Any: ...
    def __xor__(self, other: Any) -> Any: ...
    def __rxor__(self, other: Any) -> Any: ...
    def __lshift__(self, other: Any) -> Any: ...
    def __rlshift__(self, other: Any) -> Any: ...
    def __rshift__(self, other: Any) -> Any: ...
    def __rrshift__(self, other: Any) -> Any: ...
    def __invert__(self) -> Any: ...

class LiveTag(Tag): ...

class ImmediateRef:
    value: Tag | BlockRange
    def __init__(self, value: Tag | BlockRange) -> None: ...
    @property
    def tag(self) -> Tag: ...
    def __invert__(self) -> Condition: ...

def immediate(value: Tag | BlockRange | ImmediateRef) -> ImmediateRef: ...

class InputTag(Tag):
    @property
    def immediate(self) -> ImmediateRef: ...

class OutputTag(Tag):
    @property
    def immediate(self) -> ImmediateRef: ...

class LiveInputTag(LiveTag, InputTag): ...
class LiveOutputTag(LiveTag, OutputTag): ...

class _TagTypeBase(LiveTag):
    _tag_type: ClassVar[TagType]
    _default_retentive: ClassVar[bool]
    def __new__(
        cls,
        name: str,
        *,
        default: Any = None,
        retentive: bool | None = None,
        comment: str = "",
        choices: Any = None,
        readonly: bool = False,
        external: bool = False,
        final: bool = False,
        public: bool = False,
        physical: Physical | None = None,
        link: str | None = None,
        min: int | float | None = None,
        max: int | float | None = None,
        uom: str | None = None,
    ) -> LiveTag: ...

class Bool(_TagTypeBase): ...
class Int(_TagTypeBase): ...
class Dint(_TagTypeBase): ...
class Real(_TagTypeBase): ...
class Word(_TagTypeBase): ...
class Char(_TagTypeBase): ...

def _normalize_choices(
    raw: object,
    *,
    tag_type: TagType,
    owner: str = "choices",
) -> ChoiceMap | None: ...
def _structured_choice_items(raw: object, *, owner: str) -> Any: ...
