"""Industrial clothes tumbler/dryer fixture (Click-generated PLC program).

PackML state machine with burner/heat/rotate/blower subsystems, generated by
pyrung from the Click ladder CSV export.  ``logic`` is the full Program.

PackML state map (Sts_StateCurrent):
    1 CLEARING  2 STOPPED  3 STARTING  4 IDLE  5 SUSPENDED  6 EXECUTE
    7 STOPPING  8 ABORTING  9 ABORTED  10 HOLDING  11 HELD  12 UNHOLDING
    13 SUSPENDING 14 UNSUSPENDING 15 RESETTING  16 COMPLETING  17 COMPLETED
"""

from __future__ import annotations

from .main import logic

__all__ = ["logic", "enter_production"]


def enter_production(plc, *, settle_scans: int = 3) -> None:
    """Drive a cold-booted PLC into Production mode.

    A cold boot lands in Manual mode where all PackML states are disabled;
    tests that skip this hit false-unreachable.  Mode changes are only
    accepted in Idle/Stopped/Aborted (ModeChange R5), so the first scan must
    have run (cold boot settles into ABORTED(9)).

    Mirrors the reconstitute bench: pulse ``Cmd_Mode_Production`` together
    with ``Cmd_UnitModeChgRequest``; main R22 copies 1 into
    ``Cmd_UnitModeChgReqBool`` (oneshot) and R23 calls the ModeChange
    subroutine, which latches ``Sts_UnitModeCurrent = 1`` and clears the
    request tags itself.
    """
    if plc.state.scan_id == 0:
        plc.step()
    plc.patch({"Cmd_Mode_Production": True, "Cmd_UnitModeChgRequest": True})
    for _ in range(settle_scans):
        plc.step()
    mode = plc.state.tags.get("Sts_UnitModeCurrent")
    if mode != 1:
        raise RuntimeError(
            f"enter_production failed: Sts_UnitModeCurrent={mode!r} (expected 1); "
            f"mode changes are only accepted in Idle/Stopped/Aborted"
        )
