# Generated by pyrung from Click ladder CSV

from pyrung import (
    And,
    Or,
    Program,
    branch,
    calc,
    call,
    comment,
    copy,
    fall,
    fill,
    on_delay,
    out,
    reset,
    rise,
    rung,
)
from pyrung.core.system_points import system

from .subroutines.ack_alarm import ack_alarm
from .subroutines.ack_and_clear_all_alarms import ack_and_clear_all_alarms
from .subroutines.ack_warning import ack_warning
from .subroutines.alm_historian import alm_historian
from .subroutines.blower import blower
from .subroutines.disable_outputs import disable_outputs
from .subroutines.heat import heat
from .subroutines.init import init
from .subroutines.maint import maint
from .subroutines.manual import manual
from .subroutines.mode_change import mode_change
from .subroutines.plc_date_time import plc_date_time
from .subroutines.production_boilerplate import production_boilerplate
from .subroutines.production_errors import production_errors
from .subroutines.production_execute_steps import production_execute_steps
from .subroutines.production_hmi import production_hmi
from .subroutines.production_states import production_states
from .subroutines.read_inputs import read_inputs
from .subroutines.recipe_change import recipe_change
from .subroutines.rotate import rotate
from .subroutines.set_outputs import set_outputs
from .subroutines.set_outputs_manual import set_outputs_manual
from .subroutines.sfc_example import sfc_example
from .subroutines.sm_copy_or_jump_state import sm_copy_or_jump_state
from .subroutines.sm_ctrl_cmd2_state_request import sm_ctrl_cmd2_state_request
from .subroutines.sm_is_cmd_valid import sm_is_cmd_valid
from .subroutines.sm_map_cmd2_val import sm_map_cmd2_val
from .subroutines.sm_map_val2_state import sm_map_val2_state
from .subroutines.sm_state_complete2_request import sm_state_complete2_request
from .subroutines.therm_errors import therm_errors
from .subroutines.validation import validation
from .subroutines.warn_timestamp import warn_timestamp
from .tags import (
    A_PLCDT_MMDD,
    A_Alm1_PLC,
    A_Alm2_PLCLostData,
    A_Alm3_1stScanWatchdog,
    A_Alm4_ThermError,
    A_Alm11_Rotate_Trig,
    A_Alm12_Blower_Trig,
    A_Alm13_Heat_Trig,
    A_Alm14_DoorOpen_Trig,
    A_Alm15_LintOpen_Trig,
    A_Alm16_Sail_Trig,
    A_Alm17_HiHeat_Trig,
    A_AlmExtent,
    A_ModeTimeCurrent_tmr,
    A_PLCDT_hhmm,
    A_PLCDT_Second,
    A_StateTimeCurrent_tmr,
    A_StopReason_AbortCmd,
    A_StopReason_Date_MMDD,
    A_StopReason_ID,
    A_StopReason_StopCmd,
    A_StopReason_Time_hhmm,
    A_StopReason_Time_ss,
    A_Warn1_WatchdogTimerErr,
    A_Warn2_BatteryNeedsRepl,
    A_Warn3_BatteryLowVoltag,
    A_Warn4_LanError,
    A_Warn11_DoorOpen,
    A_Warn12_LintDoorOpen,
    A_WarnExtent,
    AlmHistorian_Bit2Record,
    AlmHistorian_Id2Record,
    AlmHistorian_ManualRecor,
    Blower__x,
    Blower_xCall,
    Blower_xPause,
    Cmd_AcknowledgeAlarmId,
    Cmd_AcknowledgeWarningId,
    Cmd_CmdChgRequest,
    Cmd_CmdChgRequestBool,
    Cmd_CtrlCmd,
    Cmd_ForceClear,
    Cmd_ForceOffAlmWarn_BOOL,
    Cmd_RecipeChgRequest,
    Cmd_Reset2FactoryDefault,
    Cmd_SelectedRecipe,
    Cmd_UnitModeChgReqBool,
    Cmd_UnitModeChgRequest,
    Heat__x,
    Heat_TargetTemp_F,
    Heat_TsPerDegree,
    Heat_xCall,
    Heat_xPause,
    Ref_Cmd_Abort,
    Ref_Cmd_Stop,
    Ref_Cmd_Suspend,
    Ref_State_EXECUTE,
    Rotate__x,
    Rotate_xCall,
    Rotate_xPause,
    SFCExample,
    Sts_BatteryInstalled,
    Sts_Mode_Maintenance,
    Sts_Mode_Manual,
    Sts_Mode_Production,
    Sts_P1_OperatingTemp_F,
    Sts_Pending1stScanSuspnd,
    Sts_RecipeChgInProcess,
    Sts_State_Aborted,
    Sts_State_Aborting,
    Sts_State_Clearing,
    Sts_State_Idle,
    Sts_State_Stopped,
    Sts_State_Stopping,
    Sts_StateChgInProcess,
    Sts_StateCompleteBool,
    Sts_StateCompleteFlag,
    Sts_StateCurrent,
    Sts_StateRequested,
    Sts_UnitModeCurrent,
    Sts_UnitModeRequested,
    Test_Simulate_1st_Scan,
    WarnTimestamp_Bit2Record,
    WarnTimestamp_Id2Stamp,
    WarnTimestamp_ManualStam,
    _Battery_Low_Voltage,
    _Battery_Replacement,
    _Port_1_Error_Flag,
    _Port_2_Error_Flag,
    _Port_3_Error_Flag,
    _Watchdog_Timer_Error,
    ds,
    sm__loopindex,
    sm_isCmdValid_Yes,
    z_AckAndClearAllAlm_loop,
)

with Program() as logic:
    comment("""\
        v0.1.0 - 20250603 - Debugged on T
        v0.1.1 - 20250822 - Fixed Mode outputs staying on

        Template APC_PackTag_SFC v0.1.1""")
    with rung():  # R1
        call(plc_date_time)

    with rung(
        Or(And(system.sys.first_scan, Sts_UnitModeCurrent == 0), Cmd_Reset2FactoryDefault)
    ):  # R2
        call(init)

    with rung():  # R3
        call(therm_errors)

    with rung():  # R4
        call(read_inputs)

    with rung():  # R5
        call(validation)

    comment("BATTERY")
    with rung(system.sys.battery_present):  # R6
        out(Sts_BatteryInstalled)

    comment("Continous Timers for Mode & State")
    with rung():  # R7
        on_delay(A_ModeTimeCurrent_tmr, 0, "hour")

    with rung():  # R8
        on_delay(A_StateTimeCurrent_tmr, 0, "min")

    comment("""\
        Flow needs to be:

        1) Suspend on Power Loss Logic
        2) State Machine
        3) Custom Logic Logic for Modes/States
        4) SFC functions
        5) Alarms & Warnings

        State changes take priority-always resolve them before SFC or alarms act on the system.   


        If in Execute, safety Suspend on Power-Loss""")
    with rung(
        Sts_StateCurrent == Ref_State_EXECUTE, Or(system.sys.first_scan, Test_Simulate_1st_Scan)
    ):  # R9
        copy(1, Sts_Pending1stScanSuspnd)

    with rung(Sts_Pending1stScanSuspnd == 1):  # R10
        copy(Ref_Cmd_Suspend, Cmd_CtrlCmd)
        copy(1, Cmd_CmdChgRequestBool)

    comment("Set 'Out's for different Modes")
    with rung(Sts_UnitModeCurrent == 1):  # R11
        out(Sts_Mode_Production)

    with rung(Sts_UnitModeCurrent == 2):  # R12
        out(Sts_Mode_Maintenance)

    with rung(Sts_UnitModeCurrent == 3):  # R13
        out(Sts_Mode_Manual)

    with rung(Sts_UnitModeCurrent == 1):  # R14
        call(production_boilerplate)
        call(production_states)
        call(production_execute_steps)
        with branch(Sts_Pending1stScanSuspnd != 1):
            call(production_errors)
        call(production_hmi)

    with rung(Sts_UnitModeCurrent == 2):  # R15
        call(maint)

    with rung(Sts_UnitModeCurrent == 3):  # R16
        call(manual)

    comment("Record Stop Reason (Simplistic, either from an Abort Cmd or a Stop Cmd)")
    with rung(Sts_State_Aborting):  # R17
        copy(Ref_Cmd_Abort, A_StopReason_ID)

    with rung(Sts_State_Stopping):  # R18
        copy(Ref_Cmd_Stop, A_StopReason_ID)

    with rung(Sts_State_Stopped):  # R19
        copy(A_PLCDT_MMDD, A_StopReason_Date_MMDD, oneshot=True)
        copy(A_PLCDT_hhmm, A_StopReason_Time_hhmm, oneshot=True)
        copy(A_PLCDT_Second, A_StopReason_Time_ss, oneshot=True)

    with rung(A_StopReason_ID == Ref_Cmd_Stop):  # R20
        out(A_StopReason_StopCmd)

    with rung(A_StopReason_ID == Ref_Cmd_Abort):  # R21
        out(A_StopReason_AbortCmd)

    comment("""\
        # ==============================================================================#
        # UnitMode Change
        # ==============================================================================#""")
    with rung(Cmd_UnitModeChgRequest):  # R22
        copy(1, Cmd_UnitModeChgReqBool, oneshot=True)

    with rung(Cmd_UnitModeChgReqBool == 1):  # R23
        call(mode_change)
        out(Sts_UnitModeRequested)

    with rung(Or(system.sys.first_scan, Test_Simulate_1st_Scan)):  # R24
        call(mode_change)

    comment("""\
        # ==============================================================================#
        # `State Complete` State Change
        # ==============================================================================#

        Internal only, don't map coil to value""")
    with rung(Sts_StateCompleteBool == 1):  # R25
        out(Sts_StateCompleteFlag)

    with rung(Sts_StateCompleteFlag):  # R26
        call(sm_state_complete2_request)

    comment("""\
        # ==============================================================================#
        # `Control Command` State Change
        # ==============================================================================#

        Map CtrlCmd bits to values""")
    with rung():  # R27
        call(sm_map_cmd2_val)

    with rung(Cmd_CmdChgRequest):  # R28
        copy(1, Cmd_CmdChgRequestBool, oneshot=True)

    comment("Verify Cmd")
    with rung(Cmd_CmdChgRequestBool == 1, Cmd_CtrlCmd >= 1, Cmd_CtrlCmd <= 10):  # R29
        call(sm_is_cmd_valid)
        reset(Cmd_CmdChgRequest)

    with rung(sm_isCmdValid_Yes):  # R30
        copy(0, Cmd_CmdChgRequestBool)
        reset(sm_isCmdValid_Yes)
        call(sm_ctrl_cmd2_state_request)

    with rung(Cmd_CtrlCmd != 0, Cmd_CmdChgRequestBool != 0):  # R31
        copy(0, Cmd_CtrlCmd)
        copy(0, Cmd_CmdChgRequestBool)

    comment("""\
        # ==============================================================================#
        # Finalize either State Change
        # ==============================================================================#""")
    with rung(Sts_StateRequested != 0):  # R32
        copy(0, sm__loopindex, oneshot=True)
        out(Sts_StateChgInProcess)
        call(sm_copy_or_jump_state)

    with rung():  # R33
        call(sm_map_val2_state)

    comment("Recipe Handling")
    with rung(
        rise(Cmd_RecipeChgRequest),
        Or(Sts_State_Idle, Sts_State_Stopped, Sts_State_Aborted),
        Cmd_SelectedRecipe >= 1,
        Cmd_SelectedRecipe <= 10,
    ):  # R34
        out(Sts_RecipeChgInProcess)

    with rung(Sts_RecipeChgInProcess):  # R35
        call(recipe_change)

    comment("SFC Example")
    with rung(SFCExample.xCall == 1, SFCExample.xPause != 1):  # R36
        copy(1, SFCExample._x)

    with rung(SFCExample._x == 1):  # R37
        call(sfc_example)

    comment("Rotate")
    with rung(Rotate_xCall == 1, Rotate_xPause != 1):  # R38
        copy(1, Rotate__x)

    with rung(Rotate__x == 1):  # R39
        call(rotate)

    comment("Blower")
    with rung(Blower_xCall == 1, Blower_xPause != 1):  # R40
        copy(1, Blower__x)

    with rung(Blower__x == 1):  # R41
        call(blower)

    comment("Call for Heat")
    with rung(Heat_xCall == 1, Heat_xPause != 1):  # R42
        copy(1, Heat__x)

    with rung(Heat__x == 1):  # R43
        copy(Sts_P1_OperatingTemp_F, Heat_TargetTemp_F)
        copy(10, Heat_TsPerDegree)
        call(heat)

    comment("""\
        Alarm Recording

        When you hit an Alarm condition

        1) Copy the ID value of Alarm to ds.AlmHistorian_Id2Record
        2) Copy Alarm Bit (C) to c.AlmHistorian_Bit2Record
        3) Call AlmHistorian""")
    with rung(AlmHistorian_ManualRecor != 0):  # R44
        call(alm_historian)

    with rung(Or(rise(A_Alm1_PLC), fall(A_Alm1_PLC))):  # R45
        copy(1, AlmHistorian_Id2Record)
        copy(A_Alm1_PLC, AlmHistorian_Bit2Record)
        call(alm_historian)

    with rung(Or(rise(A_Alm2_PLCLostData), fall(A_Alm2_PLCLostData))):  # R46
        copy(2, AlmHistorian_Id2Record)
        copy(A_Alm2_PLCLostData, AlmHistorian_Bit2Record)
        call(alm_historian)

    with rung(Or(rise(A_Alm3_1stScanWatchdog), fall(A_Alm3_1stScanWatchdog))):  # R47
        copy(3, AlmHistorian_Id2Record)
        copy(A_Alm3_1stScanWatchdog, AlmHistorian_Bit2Record)
        call(alm_historian)

    with rung(Or(rise(A_Alm4_ThermError), fall(A_Alm4_ThermError))):  # R48
        copy(4, AlmHistorian_Id2Record)
        copy(A_Alm4_ThermError, AlmHistorian_Bit2Record)
        call(alm_historian)

    with rung(Or(rise(A_Alm11_Rotate_Trig), fall(A_Alm11_Rotate_Trig))):  # R49
        copy(11, AlmHistorian_Id2Record)
        copy(A_Alm11_Rotate_Trig, AlmHistorian_Bit2Record)
        call(alm_historian)

    with rung(Or(rise(A_Alm12_Blower_Trig), fall(A_Alm12_Blower_Trig))):  # R50
        copy(12, AlmHistorian_Id2Record)
        copy(A_Alm12_Blower_Trig, AlmHistorian_Bit2Record)
        call(alm_historian)

    with rung(Or(rise(A_Alm13_Heat_Trig), fall(A_Alm13_Heat_Trig))):  # R51
        copy(13, AlmHistorian_Id2Record)
        copy(A_Alm13_Heat_Trig, AlmHistorian_Bit2Record)
        call(alm_historian)

    with rung(Or(rise(A_Alm14_DoorOpen_Trig), fall(A_Alm14_DoorOpen_Trig))):  # R52
        copy(14, AlmHistorian_Id2Record)
        copy(A_Alm14_DoorOpen_Trig, AlmHistorian_Bit2Record)
        call(alm_historian)

    with rung(Or(rise(A_Alm15_LintOpen_Trig), fall(A_Alm15_LintOpen_Trig))):  # R53
        copy(15, AlmHistorian_Id2Record)
        copy(A_Alm15_LintOpen_Trig, AlmHistorian_Bit2Record)
        call(alm_historian)

    with rung(Or(rise(A_Alm16_Sail_Trig), fall(A_Alm16_Sail_Trig))):  # R54
        copy(16, AlmHistorian_Id2Record)
        copy(A_Alm16_Sail_Trig, AlmHistorian_Bit2Record)
        call(alm_historian)

    with rung(Or(rise(A_Alm17_HiHeat_Trig), fall(A_Alm17_HiHeat_Trig))):  # R55
        copy(17, AlmHistorian_Id2Record)
        copy(A_Alm17_HiHeat_Trig, AlmHistorian_Bit2Record)
        call(alm_historian)

    comment("""\
        Warning Recording

        When you hit an Warn condition

        1) Copy the ID value of Warning to ds.WarnTimestamp_Id2Stamp
        2) Copy the Warning Bit (C) to WarnTimestamp_Bit2Stamp
        3) Call WarnTimestamp""")
    with rung(WarnTimestamp_ManualStam != 0):  # R56
        call(warn_timestamp)

    with rung(_Watchdog_Timer_Error):  # R57
        out(A_Warn1_WatchdogTimerErr)

    with rung(Or(rise(A_Warn1_WatchdogTimerErr), fall(A_Warn1_WatchdogTimerErr))):  # R58
        copy(1, WarnTimestamp_Id2Stamp)
        copy(A_Warn2_BatteryNeedsRepl, WarnTimestamp_Bit2Record)
        call(warn_timestamp)

    with rung(_Battery_Replacement):  # R59
        out(A_Warn2_BatteryNeedsRepl)

    with rung(Or(rise(A_Warn2_BatteryNeedsRepl), fall(A_Warn2_BatteryNeedsRepl))):  # R60
        copy(2, WarnTimestamp_Id2Stamp)
        copy(A_Warn2_BatteryNeedsRepl, WarnTimestamp_Bit2Record)
        call(warn_timestamp)

    with rung(_Battery_Low_Voltage):  # R61
        out(A_Warn3_BatteryLowVoltag)

    with rung(Or(rise(A_Warn3_BatteryLowVoltag), fall(A_Warn3_BatteryLowVoltag))):  # R62
        copy(3, WarnTimestamp_Id2Stamp)
        copy(A_Warn3_BatteryLowVoltag, WarnTimestamp_Bit2Record)
        call(warn_timestamp)

    with rung(Or(_Port_1_Error_Flag, _Port_2_Error_Flag, _Port_3_Error_Flag)):  # R63
        out(A_Warn4_LanError)

    with rung(Or(rise(A_Warn4_LanError), fall(A_Warn4_LanError))):  # R64
        copy(4, WarnTimestamp_Id2Stamp)
        copy(A_Warn4_LanError, WarnTimestamp_Bit2Record)
        call(warn_timestamp)

    with rung(Or(rise(A_Warn11_DoorOpen), fall(A_Warn11_DoorOpen))):  # R65
        copy(11, WarnTimestamp_Id2Stamp)
        copy(A_Warn11_DoorOpen, WarnTimestamp_Bit2Record)
        call(warn_timestamp)

    with rung(Or(rise(A_Warn12_LintDoorOpen), fall(A_Warn12_LintDoorOpen))):  # R66
        copy(12, WarnTimestamp_Id2Stamp)
        copy(A_Warn12_LintDoorOpen, WarnTimestamp_Bit2Record)
        call(warn_timestamp)

    with rung(rise(system.sys.clock_1s)):  # R67
        calc(ds.select(201, 300).sum(), A_AlmExtent)

    with rung(fall(system.sys.clock_1s)):  # R68
        calc(ds.select(301, 350).sum(), A_WarnExtent)

    with rung(Sts_State_Clearing):  # R69
        copy(0, z_AckAndClearAllAlm_loop, oneshot=True)
        call(ack_and_clear_all_alarms)

    comment("Clearing should reset AlmExtent")
    with rung(Sts_State_Clearing, A_AlmExtent == 0):  # R70
        copy(1, Sts_StateCompleteBool)

    with rung(Cmd_AcknowledgeAlarmId != 0):  # R71
        call(ack_alarm)

    with rung(Cmd_AcknowledgeWarningId != 0):  # R72
        call(ack_warning)

    with rung(Cmd_ForceClear, Sts_State_Clearing):  # R73
        copy(1, Cmd_ForceOffAlmWarn_BOOL)

    with rung(Cmd_ForceOffAlmWarn_BOOL == 1):  # R74
        fill(0, ds.select(201, 350))  # A_Alm1_Status..A_Warn50_Status
        copy(0, Cmd_ForceOffAlmWarn_BOOL)
        reset(Cmd_ForceClear)

    with rung(Or(Sts_Mode_Production, Sts_Mode_Maintenance)):  # R75
        call(set_outputs)

    with rung(Sts_Mode_Manual):  # R76
        call(set_outputs_manual)

    comment("Undefined mode")
    with rung(Sts_UnitModeCurrent == 0):  # R77
        call(disable_outputs)

    with rung():  # R78
        reset(Test_Simulate_1st_Scan)
