"""Reproducer: reachability cross-check — simulation state not in BFS set."""

from pyrung.core import (
    PLC, And, Block, Bool, Char, Counter, Dint, Int, Or, Program, Real, Rung,
    TagType, Timer, Word, blockcopy, branch, calc, call, copy, count_down, count_up,
    event_drum, fall, fill, forloop, latch, lro, lsh, off_delay, on_delay, out, pack_bits,
    pack_text, pack_words, receive, reset, return_early, rise, rro, rsh, search, shift,
    subroutine, time_drum,
    to_ascii, to_binary, to_text, to_value, unpack_to_bits, unpack_to_words,
)
from pyrung.core.analysis.prove import Intractable, reachable_states


def test_reproducer():
    In0 = Bool("In0", external=True)
    In1 = Bool("In1", external=True)
    In2 = Bool("In2", external=True)
    In3 = Bool("In3", external=True)
    B0 = Bool("B0")
    B1 = Bool("B1")
    B2 = Bool("B2")
    ExtN0 = Int("ExtN0", external=True, choices={0: 'Idle', 1: 'Run', 2: 'Done'})
    ExtN1 = Int("ExtN1", external=True, choices={1: 'A', 2: 'B'})
    N0 = Int("N0")
    D0 = Dint("D0")
    R0 = Real("R0")
    W0 = Word("W0")
    T0 = Timer.clone("T0")
    C0 = Counter.clone("C0")
    C1 = Counter.clone("C1")

    with Program(strict=False) as logic:
        with Rung(rise(In2)):
            out(B1)
        with Rung(In0):
            count_up(C1, 5).reset(C1.Done)

    projection = ['B1', 'C1_Done']
    bfs_result = reachable_states(logic, project=projection,
                                  max_states=10_000, depth_budget=20)
    assert not isinstance(bfs_result, Intractable)

    plc = PLC(logic, dt=0.010)
    plc.patch({'In0': True, 'In1': True, 'In2': False, 'In3': True, 'ExtN0': 1, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': False, 'In3': False, 'ExtN0': 2, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'In1': False, 'In2': True, 'In3': False, 'ExtN0': 2, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': False, 'In3': False, 'ExtN0': 2, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': True, 'In3': False, 'ExtN0': 2, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': False, 'In3': False, 'ExtN0': 1, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': False, 'In3': False, 'ExtN0': 2, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': False, 'In3': False, 'ExtN0': 1, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': False, 'In3': False, 'ExtN0': 0, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': False, 'In3': False, 'ExtN0': 0, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': True, 'In3': True, 'ExtN0': 1, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'In1': False, 'In2': False, 'In3': True, 'ExtN0': 1, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': False, 'In3': True, 'ExtN0': 1, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': False, 'In2': True, 'In3': True, 'ExtN0': 1, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': False, 'In3': False, 'ExtN0': 0, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'In1': False, 'In2': False, 'In3': True, 'ExtN0': 2, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': True, 'In3': False, 'ExtN0': 2, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': True, 'In3': False, 'ExtN0': 2, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': True, 'In3': True, 'ExtN0': 2, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': False, 'In3': True, 'ExtN0': 2, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': True, 'In3': False, 'ExtN0': 1, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': False, 'In3': False, 'ExtN0': 0, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': False, 'In3': True, 'ExtN0': 2, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'In1': False, 'In2': False, 'In3': True, 'ExtN0': 2, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': True, 'In3': False, 'ExtN0': 2, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': True, 'In3': True, 'ExtN0': 1, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'In1': False, 'In2': True, 'In3': False, 'ExtN0': 1, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': False, 'In2': True, 'In3': False, 'ExtN0': 0, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': False, 'In3': False, 'ExtN0': 1, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': False, 'In3': False, 'ExtN0': 0, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': True, 'In3': True, 'ExtN0': 0, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': True, 'In3': True, 'ExtN0': 1, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': False, 'In3': True, 'ExtN0': 2, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'In1': False, 'In2': True, 'In3': True, 'ExtN0': 0, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': False, 'In3': True, 'ExtN0': 2, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': False, 'In2': False, 'In3': True, 'ExtN0': 2, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': False, 'In3': True, 'ExtN0': 1, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': True, 'In3': True, 'ExtN0': 2, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': True, 'In3': True, 'ExtN0': 2, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': True, 'In3': False, 'ExtN0': 1, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': False, 'In3': False, 'ExtN0': 1, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': True, 'In3': False, 'ExtN0': 2, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': False, 'In3': False, 'ExtN0': 0, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': False, 'In3': False, 'ExtN0': 2, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'In1': False, 'In2': False, 'In3': False, 'ExtN0': 2, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': False, 'In3': True, 'ExtN0': 1, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': False, 'In3': False, 'ExtN0': 1, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': True, 'In3': True, 'ExtN0': 1, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': False, 'In3': False, 'ExtN0': 0, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': True, 'In3': True, 'ExtN0': 1, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': True, 'In3': True, 'ExtN0': 0, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': False, 'In2': False, 'In3': False, 'ExtN0': 1, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': True, 'In3': True, 'ExtN0': 2, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': True, 'In3': True, 'ExtN0': 2, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'In1': False, 'In2': True, 'In3': True, 'ExtN0': 2, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': True, 'In3': False, 'ExtN0': 0, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': False, 'In3': True, 'ExtN0': 1, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': False, 'In2': True, 'In3': True, 'ExtN0': 2, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': False, 'In3': False, 'ExtN0': 2, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': False, 'In3': False, 'ExtN0': 0, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': True, 'In3': False, 'ExtN0': 1, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'In1': False, 'In2': False, 'In3': False, 'ExtN0': 0, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': True, 'In3': True, 'ExtN0': 1, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': False, 'In3': True, 'ExtN0': 2, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': True, 'In3': False, 'ExtN0': 1, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': False, 'In3': False, 'ExtN0': 2, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': False, 'In3': True, 'ExtN0': 0, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': True, 'In3': True, 'ExtN0': 2, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': False, 'In2': True, 'In3': True, 'ExtN0': 0, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': False, 'In2': False, 'In3': False, 'ExtN0': 2, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': True, 'In3': True, 'ExtN0': 1, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': False, 'In3': True, 'ExtN0': 0, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'In1': False, 'In2': True, 'In3': True, 'ExtN0': 0, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': True, 'In3': True, 'ExtN0': 0, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': False, 'In3': True, 'ExtN0': 1, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'In1': False, 'In2': False, 'In3': True, 'ExtN0': 1, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': False, 'In3': True, 'ExtN0': 0, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': True, 'In3': True, 'ExtN0': 1, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': False, 'In3': True, 'ExtN0': 2, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': False, 'In3': False, 'ExtN0': 0, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': True, 'In3': False, 'ExtN0': 0, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': False, 'In3': True, 'ExtN0': 2, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': False, 'In2': False, 'In3': False, 'ExtN0': 0, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': False, 'In3': True, 'ExtN0': 0, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': True, 'In3': False, 'ExtN0': 2, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': False, 'In3': True, 'ExtN0': 1, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': True, 'In3': False, 'ExtN0': 2, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': True, 'In3': True, 'ExtN0': 2, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': True, 'In3': False, 'ExtN0': 1, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': False, 'In3': False, 'ExtN0': 2, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': True, 'In3': False, 'ExtN0': 1, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': False, 'In2': True, 'In3': True, 'ExtN0': 2, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'In1': False, 'In2': False, 'In3': False, 'ExtN0': 2, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': False, 'In3': False, 'ExtN0': 0, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'In1': False, 'In2': True, 'In3': True, 'ExtN0': 1, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': False, 'In2': False, 'In3': True, 'ExtN0': 2, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': False, 'In3': False, 'ExtN0': 2, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'In1': False, 'In2': False, 'In3': True, 'ExtN0': 1, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': False, 'In3': True, 'ExtN0': 1, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': False, 'In2': True, 'In3': False, 'ExtN0': 2, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': False, 'In3': False, 'ExtN0': 2, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'In1': False, 'In2': False, 'In3': False, 'ExtN0': 2, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': True, 'In3': False, 'ExtN0': 0, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': False, 'In3': False, 'ExtN0': 2, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': False, 'In2': False, 'In3': False, 'ExtN0': 2, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': False, 'In3': True, 'ExtN0': 2, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': True, 'In3': True, 'ExtN0': 1, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': False, 'In2': True, 'In3': True, 'ExtN0': 2, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': False, 'In3': True, 'ExtN0': 1, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': False, 'In3': False, 'ExtN0': 1, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': False, 'In2': False, 'In3': False, 'ExtN0': 2, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': True, 'In3': False, 'ExtN0': 0, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': True, 'In3': False, 'ExtN0': 2, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': False, 'In2': True, 'In3': False, 'ExtN0': 2, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': True, 'In3': True, 'ExtN0': 2, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': False, 'In3': True, 'ExtN0': 2, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': True, 'In3': True, 'ExtN0': 0, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': True, 'In3': False, 'ExtN0': 0, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': False, 'In3': False, 'ExtN0': 0, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': False, 'In3': False, 'ExtN0': 1, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': True, 'In3': False, 'ExtN0': 2, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': True, 'In3': True, 'ExtN0': 1, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': True, 'In3': False, 'ExtN0': 2, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': False, 'In3': False, 'ExtN0': 0, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': False, 'In3': False, 'ExtN0': 0, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': True, 'In3': False, 'ExtN0': 0, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': True, 'In3': False, 'ExtN0': 2, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': False, 'In2': True, 'In3': False, 'ExtN0': 0, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': False, 'In3': True, 'ExtN0': 1, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': False, 'In3': False, 'ExtN0': 0, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': False, 'In2': False, 'In3': False, 'ExtN0': 1, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': True, 'In3': True, 'ExtN0': 1, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': True, 'In3': False, 'ExtN0': 0, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': False, 'In2': False, 'In3': True, 'ExtN0': 0, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': True, 'In3': False, 'ExtN0': 2, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': False, 'In3': True, 'ExtN0': 1, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': False, 'In3': True, 'ExtN0': 1, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': False, 'In3': True, 'ExtN0': 0, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': True, 'In3': True, 'ExtN0': 0, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': True, 'In3': True, 'ExtN0': 0, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': False, 'In2': True, 'In3': True, 'ExtN0': 2, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': True, 'In3': True, 'ExtN0': 0, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': False, 'In3': True, 'ExtN0': 0, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': True, 'In3': False, 'ExtN0': 1, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': False, 'In2': True, 'In3': True, 'ExtN0': 0, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': False, 'In3': True, 'ExtN0': 2, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'In1': False, 'In2': False, 'In3': True, 'ExtN0': 2, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': False, 'In2': True, 'In3': True, 'ExtN0': 1, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': False, 'In3': True, 'ExtN0': 0, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': False, 'In3': False, 'ExtN0': 2, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': True, 'In3': True, 'ExtN0': 1, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': False, 'In3': False, 'ExtN0': 2, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': False, 'In3': True, 'ExtN0': 2, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': True, 'In3': False, 'ExtN0': 2, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': True, 'In3': False, 'ExtN0': 1, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': False, 'In2': False, 'In3': True, 'ExtN0': 1, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': True, 'In3': False, 'ExtN0': 2, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'In1': False, 'In2': False, 'In3': False, 'ExtN0': 0, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': True, 'In3': False, 'ExtN0': 2, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': True, 'In3': True, 'ExtN0': 1, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'In1': False, 'In2': False, 'In3': False, 'ExtN0': 2, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'In1': False, 'In2': True, 'In3': True, 'ExtN0': 0, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': False, 'In2': True, 'In3': True, 'ExtN0': 2, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': False, 'In2': False, 'In3': False, 'ExtN0': 0, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': True, 'In3': False, 'ExtN0': 2, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': True, 'In3': False, 'ExtN0': 1, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': False, 'In3': False, 'ExtN0': 0, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': True, 'In3': True, 'ExtN0': 0, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': False, 'In3': True, 'ExtN0': 1, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': True, 'In3': True, 'ExtN0': 1, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': False, 'In3': False, 'ExtN0': 1, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'In1': False, 'In2': True, 'In3': True, 'ExtN0': 2, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': False, 'In3': True, 'ExtN0': 2, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': False, 'In3': False, 'ExtN0': 0, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': False, 'In3': False, 'ExtN0': 0, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': False, 'In3': True, 'ExtN0': 2, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': False, 'In2': True, 'In3': False, 'ExtN0': 1, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': False, 'In2': False, 'In3': True, 'ExtN0': 0, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': False, 'In2': False, 'In3': True, 'ExtN0': 1, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': True, 'In3': True, 'ExtN0': 1, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': True, 'In3': False, 'ExtN0': 2, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': True, 'In3': False, 'ExtN0': 0, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': True, 'In3': True, 'ExtN0': 2, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': True, 'In3': False, 'ExtN0': 2, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': False, 'In3': True, 'ExtN0': 2, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'In1': False, 'In2': True, 'In3': True, 'ExtN0': 1, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'In1': False, 'In2': False, 'In3': True, 'ExtN0': 1, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': False, 'In3': True, 'ExtN0': 1, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': False, 'In3': False, 'ExtN0': 0, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': True, 'In3': True, 'ExtN0': 0, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': True, 'In3': False, 'ExtN0': 1, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': True, 'In3': True, 'ExtN0': 1, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': False, 'In3': False, 'ExtN0': 0, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': True, 'In3': True, 'ExtN0': 0, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': True, 'In3': True, 'ExtN0': 0, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'In1': False, 'In2': False, 'In3': True, 'ExtN0': 1, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': True, 'In3': False, 'ExtN0': 0, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': True, 'In3': True, 'ExtN0': 1, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': False, 'In3': False, 'ExtN0': 2, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': False, 'In3': True, 'ExtN0': 1, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': True, 'In3': True, 'ExtN0': 1, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': True, 'In3': False, 'ExtN0': 1, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': False, 'In2': True, 'In3': False, 'ExtN0': 1, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': False, 'In3': False, 'ExtN0': 1, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': False, 'In3': True, 'ExtN0': 0, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': True, 'In3': True, 'ExtN0': 2, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': True, 'In3': False, 'ExtN0': 1, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': False, 'In3': False, 'ExtN0': 0, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': True, 'In3': False, 'ExtN0': 2, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': False, 'In2': False, 'In3': True, 'ExtN0': 0, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': True, 'In3': True, 'ExtN0': 2, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': False, 'In3': True, 'ExtN0': 1, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': True, 'In3': False, 'ExtN0': 2, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': True, 'In3': False, 'ExtN0': 1, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'In1': False, 'In2': False, 'In3': True, 'ExtN0': 2, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': False, 'In3': False, 'ExtN0': 0, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': True, 'In3': True, 'ExtN0': 2, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': False, 'In3': True, 'ExtN0': 0, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': False, 'In3': False, 'ExtN0': 2, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': False, 'In3': True, 'ExtN0': 1, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': True, 'In3': False, 'ExtN0': 1, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': False, 'In3': False, 'ExtN0': 0, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': False, 'In3': False, 'ExtN0': 2, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': True, 'In3': True, 'ExtN0': 0, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': True, 'In3': False, 'ExtN0': 2, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': True, 'In3': False, 'ExtN0': 0, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': False, 'In3': True, 'ExtN0': 2, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': True, 'In3': False, 'ExtN0': 0, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': True, 'In3': False, 'ExtN0': 1, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': False, 'In2': True, 'In3': False, 'ExtN0': 1, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': True, 'In3': True, 'ExtN0': 0, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': True, 'In3': False, 'ExtN0': 2, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'In1': False, 'In2': True, 'In3': False, 'ExtN0': 0, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': True, 'In3': True, 'ExtN0': 1, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': False, 'In3': False, 'ExtN0': 2, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': True, 'In3': False, 'ExtN0': 2, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': False, 'In3': False, 'ExtN0': 1, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': False, 'In3': False, 'ExtN0': 1, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': False, 'In3': False, 'ExtN0': 0, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': True, 'In3': False, 'ExtN0': 1, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': True, 'In3': False, 'ExtN0': 1, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': False, 'In3': True, 'ExtN0': 0, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': False, 'In3': False, 'ExtN0': 2, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': True, 'In3': True, 'ExtN0': 2, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': True, 'In3': False, 'ExtN0': 2, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': False, 'In3': False, 'ExtN0': 0, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': False, 'In2': True, 'In3': True, 'ExtN0': 1, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': False, 'In3': True, 'ExtN0': 2, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': False, 'In3': True, 'ExtN0': 2, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': True, 'In3': True, 'ExtN0': 0, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'In1': False, 'In2': True, 'In3': True, 'ExtN0': 0, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': True, 'In3': True, 'ExtN0': 0, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': True, 'In3': False, 'ExtN0': 0, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': True, 'In3': True, 'ExtN0': 1, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': False, 'In2': True, 'In3': False, 'ExtN0': 0, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': False, 'In3': True, 'ExtN0': 1, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': True, 'In3': True, 'ExtN0': 1, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'In1': False, 'In2': True, 'In3': False, 'ExtN0': 2, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': False, 'In3': False, 'ExtN0': 0, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': True, 'In3': False, 'ExtN0': 1, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': False, 'In3': False, 'ExtN0': 1, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'In1': False, 'In2': True, 'In3': False, 'ExtN0': 1, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': True, 'In3': False, 'ExtN0': 0, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': True, 'In3': False, 'ExtN0': 2, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': True, 'In3': False, 'ExtN0': 1, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': True, 'In3': True, 'ExtN0': 0, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'In1': False, 'In2': True, 'In3': False, 'ExtN0': 1, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': False, 'In2': True, 'In3': False, 'ExtN0': 1, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'In1': False, 'In2': False, 'In3': False, 'ExtN0': 2, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': False, 'In3': True, 'ExtN0': 2, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': True, 'In3': True, 'ExtN0': 0, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': False, 'In2': True, 'In3': True, 'ExtN0': 1, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': False, 'In3': True, 'ExtN0': 0, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': False, 'In3': False, 'ExtN0': 1, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': True, 'In3': True, 'ExtN0': 2, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'In1': False, 'In2': True, 'In3': True, 'ExtN0': 1, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'In1': False, 'In2': True, 'In3': False, 'ExtN0': 2, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': False, 'In3': True, 'ExtN0': 1, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': False, 'In3': True, 'ExtN0': 0, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': False, 'In3': True, 'ExtN0': 0, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': False, 'In3': True, 'ExtN0': 2, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': True, 'In3': False, 'ExtN0': 0, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': False, 'In3': False, 'ExtN0': 1, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': True, 'In3': False, 'ExtN0': 1, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': True, 'In3': True, 'ExtN0': 0, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': False, 'In3': True, 'ExtN0': 1, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': False, 'In3': False, 'ExtN0': 2, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': True, 'In3': False, 'ExtN0': 2, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'In1': True, 'In2': False, 'In3': True, 'ExtN0': 0, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'In1': True, 'In2': False, 'In3': False, 'ExtN0': 1, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': True, 'In3': True, 'ExtN0': 2, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': False, 'In3': True, 'ExtN0': 2, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'In1': False, 'In2': True, 'In3': True, 'ExtN0': 2, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': False, 'In3': True, 'ExtN0': 0, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'In1': False, 'In2': True, 'In3': True, 'ExtN0': 1, 'ExtN1': 2})
    plc.step()

    # Expected BFS set size: 3
    # Simulated state at scan 294: {'B1': True, 'C1_Done': True}
    tags = plc.current_state.tags
    state = frozenset((name, tags[name]) for name in ['B1', 'C1_Done'])
    assert state in bfs_result, (
        f"Simulation state not in BFS set: {dict(state)}"
    )
