"""Reproducer: reachability cross-check — simulation state not in BFS set."""

from pyrung.core import (
    PLC, And, Block, Bool, Char, Counter, Dint, Int, Or, Program, Real, Rung,
    TagType, Timer, Word, blockcopy, branch, calc, call, copy, count_down, count_up,
    event_drum, fall, fill, forloop, latch, lro, lsh, off_delay, on_delay, out, pack_bits,
    pack_text, pack_words, receive, reset, return_early, rise, rro, rsh, search, shift,
    subroutine, time_drum,
    to_ascii, to_binary, to_text, to_value, unpack_to_bits, unpack_to_words,
)
from pyrung.core.analysis.prove import Intractable, reachable_states


def test_reproducer():
    In0 = Bool("In0", external=True)
    B0 = Bool("B0")
    ExtN0 = Int("ExtN0", external=True, min=0, max=50)
    ExtN1 = Int("ExtN1", external=True, choices={1: 'A', 2: 'B'})
    N0 = Int("N0", min=-2, max=6)
    R0 = Real("R0")
    T0 = Timer.clone("T0")
    CB = Block("CB", TagType.BOOL, 1, 8)

    with Program(strict=False) as logic:
        with Rung(ExtN0 < 5):
            out(B0)
        with Rung():
            on_delay(T0, 100).reset(B0)
        with Rung():
            calc(ExtN0 + 0, N0)
        with Rung(N0 == 0):
            out(B0)

    projection = ['B0', 'T0_Done']
    bfs_result = reachable_states(logic, project=projection,
                                  max_states=10_000, depth_budget=20)
    assert not isinstance(bfs_result, Intractable)

    plc = PLC(logic, dt=0.010)
    plc.patch({'In0': True, 'ExtN0': 35, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'ExtN0': 27, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'ExtN0': 36, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'ExtN0': 26, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'ExtN0': 25, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'ExtN0': 33, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'ExtN0': 16, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'ExtN0': 27, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'ExtN0': 12, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'ExtN0': 8, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'ExtN0': 10, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'ExtN0': 7, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'ExtN0': 5, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'ExtN0': 7, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'ExtN0': 41, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'ExtN0': 41, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'ExtN0': 41, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'ExtN0': 24, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'ExtN0': 8, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'ExtN0': 40, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'ExtN0': 28, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'ExtN0': 4, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'ExtN0': 15, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'ExtN0': 39, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'ExtN0': 46, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'ExtN0': 24, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'ExtN0': 21, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'ExtN0': 42, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'ExtN0': 50, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'ExtN0': 30, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'ExtN0': 45, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'ExtN0': 43, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'ExtN0': 17, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'ExtN0': 36, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'ExtN0': 29, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'ExtN0': 15, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'ExtN0': 2, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'ExtN0': 15, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'ExtN0': 16, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'ExtN0': 7, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'ExtN0': 33, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'ExtN0': 44, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'ExtN0': 23, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'ExtN0': 27, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'ExtN0': 5, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'ExtN0': 24, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'ExtN0': 13, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'ExtN0': 40, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'ExtN0': 16, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'ExtN0': 32, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'ExtN0': 10, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'ExtN0': 48, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'ExtN0': 22, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'ExtN0': 24, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'ExtN0': 37, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'ExtN0': 34, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'ExtN0': 26, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'ExtN0': 4, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'ExtN0': 7, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'ExtN0': 38, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'ExtN0': 6, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'ExtN0': 22, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'ExtN0': 39, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'ExtN0': 31, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'ExtN0': 46, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'ExtN0': 19, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'ExtN0': 19, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'ExtN0': 39, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'ExtN0': 29, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'ExtN0': 21, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'ExtN0': 16, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': True, 'ExtN0': 42, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': False, 'ExtN0': 50, 'ExtN1': 2})
    plc.step()
    plc.patch({'In0': True, 'ExtN0': 46, 'ExtN1': 1})
    plc.step()
    plc.patch({'In0': False, 'ExtN0': 30, 'ExtN1': 1})
    plc.step()

    # Expected BFS set size: 2
    # Simulated state at scan 74: {'T0_Done': True, 'B0': False}
    tags = plc.current_state.tags
    state = frozenset((name, tags[name]) for name in ['B0', 'T0_Done'])
    assert state in bfs_result, (
        f"Simulation state not in BFS set: {dict(state)}"
    )
