# Generated by pyrung from Click ladder CSV

from pyrung import calc, copy, reset, return_early, rung, subroutine

from ..tags import (
    A_AlmCoil,
    Cmd_AcknowledgeAlarmId,
    ds,
    z_AckAndClearAllAlm_eval,
    z_AckAndClearAllAlm_idx,
    z_AckAndClearAllAlm_loop,
)


@subroutine("AckAndClearAllAlarms")
def ack_and_clear_all_alarms():
    with rung():  # R1
        calc(z_AckAndClearAllAlm_loop + 1, z_AckAndClearAllAlm_loop)

    with rung(z_AckAndClearAllAlm_loop > 100):  # R2
        reset(A_AlmCoil.select(1, 100))  # A_Alm1_PLC..A_AlmCoil100
        return_early()

    with rung():  # R3
        calc(z_AckAndClearAllAlm_loop + 200, z_AckAndClearAllAlm_idx)

    with rung():  # R4
        copy(ds[z_AckAndClearAllAlm_idx], z_AckAndClearAllAlm_eval)

    with rung(z_AckAndClearAllAlm_eval == 1):  # R5
        copy(z_AckAndClearAllAlm_loop, Cmd_AcknowledgeAlarmId)
