# Generated by pyrung from Click ladder CSV

from pyrung import calc, copy, rung, subroutine

from ..tags import (
    A_PLCDT_hhmm,
    Cmd_AcknowledgeAlarmId,
    Cmd_AcknowledgeWarningId,
    ds,
    z_WarnAlarm_ack_idx,
)


@subroutine("AckWarning")
def ack_warning():
    with rung(Cmd_AcknowledgeWarningId >= 1, Cmd_AcknowledgeAlarmId <= 50):  # R1
        calc((Cmd_AcknowledgeWarningId * 10) + 3991 + 8, z_WarnAlarm_ack_idx)
        copy(A_PLCDT_hhmm, ds[z_WarnAlarm_ack_idx])

    with rung():  # R2
        copy(0, Cmd_AcknowledgeWarningId)
