# Generated by pyrung from Click ladder CSV

from pyrung import calc, copy, rung, subroutine

from ..tags import A_PLCDT_hhmm, Cmd_AcknowledgeAlarmId, ds, z_AckAlarm_ack_idx


@subroutine("AckAlarm")
def ack_alarm():
    with rung(Cmd_AcknowledgeAlarmId >= 1, Cmd_AcknowledgeAlarmId <= 100):  # R1
        calc((Cmd_AcknowledgeAlarmId * 10) + 2991 + 8, z_AckAlarm_ack_idx)
        copy(A_PLCDT_hhmm, ds[z_AckAlarm_ack_idx])

    with rung():  # R2
        copy(0, Cmd_AcknowledgeAlarmId)
