# Generated by pyrung from Click ladder CSV

from pyrung import (
    blockcopy,
    branch,
    calc,
    comment,
    copy,
    pack_bits,
    reset,
    return_early,
    rung,
    subroutine,
    unpack_to_words,
)

from ..tags import (
    A_PLCDT_MMDD,
    A_AlmHist,
    A_PLCDT_hhmm,
    A_PLCDT_Second,
    AlmHistorian__ack_idx,
    AlmHistorian__bit2status,
    AlmHistorian__cat_idx,
    AlmHistorian__hhmm_idx,
    AlmHistorian__id_idx,
    AlmHistorian__MMDD_idx,
    AlmHistorian__packedbit,
    AlmHistorian__ss_idx,
    AlmHistorian__status_idx,
    AlmHistorian__stepid_idx,
    AlmHistorian__subid_idx,
    AlmHistorian__val_idx,
    AlmHistorian_Bit2Record,
    AlmHistorian_Id2Record,
    AlmHistorian_ManualRecor,
    c,
    ds,
)


@subroutine("AlmHistorian")
def alm_historian():
    comment("Return early if not in range")
    with rung():  # R1
        with branch(AlmHistorian_Id2Record < 1):
            copy(0, AlmHistorian_Id2Record)
        reset(AlmHistorian_Bit2Record)
        copy(0, AlmHistorian_ManualRecor)
        return_early()

    comment("""\
        So we can have a SINGLE run when calling AlarmHistorian

        Only care about the 1 bit, but you need 2
        Pack into a DD, unpack into DS""")
    with rung():  # R2
        pack_bits(
            c.select(1061, 1062), AlmHistorian__packedbit
        )  # AlmHistorian_Bit2Record..AlmHistorian__empty1

    with rung():  # R3
        unpack_to_words(
            AlmHistorian__packedbit, ds.select(183, 184)
        )  # AlmHistorian__bit2status..AlmHistorian__leaveempty

    comment("When called, copy in the ID of the Alarm to AlarmHistory_Id2Copy")
    with rung():  # R4
        calc((AlmHistorian_Id2Record * 10) + 2991, AlmHistorian__id_idx)

    with rung():  # R5
        calc(AlmHistorian__id_idx + 1, AlmHistorian__subid_idx)

    with rung():  # R6
        calc(AlmHistorian__id_idx + 2, AlmHistorian__stepid_idx)

    with rung():  # R7
        calc(AlmHistorian__id_idx + 3, AlmHistorian__val_idx)

    with rung():  # R8
        calc(AlmHistorian__id_idx + 4, AlmHistorian__cat_idx)

    with rung():  # R9
        calc(AlmHistorian__id_idx + 5, AlmHistorian__MMDD_idx)

    with rung():  # R10
        calc(AlmHistorian__id_idx + 6, AlmHistorian__hhmm_idx)

    with rung():  # R11
        calc(AlmHistorian__id_idx + 7, AlmHistorian__ss_idx)

    with rung():  # R12
        calc(AlmHistorian__id_idx + 8, AlmHistorian__ack_idx)

    with rung():  # R13
        calc(AlmHistorian_Id2Record + 200, AlmHistorian__status_idx)

    comment("Adding MMDD hhmm ss to alarm")
    with rung():  # R14
        copy(A_PLCDT_MMDD, ds[AlmHistorian__MMDD_idx])

    with rung():  # R15
        copy(A_PLCDT_hhmm, ds[AlmHistorian__hhmm_idx])

    with rung():  # R16
        copy(A_PLCDT_Second, ds[AlmHistorian__ss_idx])

    comment("Copy in the status flag")
    with rung():  # R17
        copy(AlmHistorian__bit2status, ds[AlmHistorian__status_idx])

    comment("If we are turning on the bit, then remove any acknowledgement")
    with rung(AlmHistorian_ManualRecor == 1):  # R18
        copy(0, AlmHistorian__ack_idx)

    comment("Shift Alarm History down")
    with rung():  # R19
        blockcopy(
            A_AlmHist.instance_select(1, 49), A_AlmHist.instance_select(2, 50)
        )  # A_AlmHist1_ID..A_AlmHist49_Status  # A_AlmHist2_ID..A_AlmHist50_Status

    with rung():  # R20
        copy(ds[AlmHistorian__id_idx], A_AlmHist[1].ID)

    comment("Then copy into alarm history")
    with rung():  # R21
        copy(ds[AlmHistorian__subid_idx], A_AlmHist[1].SubID)

    with rung():  # R22
        copy(ds[AlmHistorian__stepid_idx], A_AlmHist[1].StepID)

    with rung():  # R23
        copy(ds[AlmHistorian__val_idx], A_AlmHist[1].Val)

    with rung():  # R24
        copy(ds[AlmHistorian__cat_idx], A_AlmHist[1].Cat)

    with rung():  # R25
        copy(ds[AlmHistorian__MMDD_idx], A_AlmHist[1].Date_MMDD)

    with rung():  # R26
        copy(ds[AlmHistorian__hhmm_idx], A_AlmHist[1].Time_hhmm)

    with rung():  # R27
        copy(ds[AlmHistorian__ss_idx], A_AlmHist[1].Time_ss)

    with rung():  # R28
        copy(ds[AlmHistorian__ack_idx], A_AlmHist[1].AckTime_hhmm)

    with rung():  # R29
        copy(ds[AlmHistorian__status_idx], A_AlmHist[1].Status)

    comment("Reset subroutine bits")
    with rung():  # R30
        copy(0, AlmHistorian_Id2Record)

    with rung():  # R31
        reset(AlmHistorian_Bit2Record)

    with rung():  # R32
        copy(0, AlmHistorian_ManualRecor)

    with rung():  # R33
        pass

    with rung():  # R34
        pass
