# Generated by pyrung from Click ladder CSV

from pyrung import (
    Or,
    calc,
    comment,
    copy,
    fill,
    latch,
    on_delay,
    out,
    reset,
    return_early,
    rung,
    subroutine,
)

from ..tags import (
    Blower__init,
    Blower__valstepisodd,
    Blower__x,
    Blower_CurStep,
    Blower_CurStep_tmr,
    Blower_EnableLimit,
    Blower_Error,
    Blower_ErrorStep,
    Blower_Limit_Ts,
    Blower_ResetTmr,
    Blower_StoredStep,
    Blower_tmr,
    Blower_Trans,
    Blower_x,
    Blower_xCall,
    Blower_xInit,
    Blower_xPause,
    Blower_xReset,
    ds,
    i_BlowerFB,
    o_BlowerCt,
)


@subroutine("Blower")
def blower():
    comment("""\
        Error List:

        1 = Not getting Feedback from Contactor (ie either contactor or thermal overload isn't getting power

            # ==============================================================================#
            # SECTION 1: SFC INITIALIZATION BOILERPLATE - DO NOT MODIFY
            # ==============================================================================#""")
    with rung():  # R1
        latch(Blower_x)

    comment("Shared Resets for Init and Reset")
    with rung(Or(Blower_xInit == 1, Blower_xReset == 1)):  # R2
        copy(0, Blower__init)
        copy(0, Blower_tmr.Acc)
        copy(0, Blower_CurStep_tmr.Acc)
        fill(1, ds.select(531, 532))  # Blower_CurStep..Blower_StoredStep
        fill(0, ds.select(525, 526))  # Blower_Error..Blower_ErrorStep

    comment("Built-in timer for step timeout detection")
    with rung():  # R3
        on_delay(Blower_tmr, Blower_Limit_Ts, "sec").reset(Blower_ResetTmr == 1)

    comment("Reset the timer reset flag after it's been processed")
    with rung(Blower_ResetTmr == 1):  # R4
        copy(0, Blower_ResetTmr)

    comment("Error detection - If step exceeds time limit")
    with rung(Blower_tmr.Acc >= Blower_Limit_Ts, Blower_EnableLimit == 1):  # R5
        copy(1, Blower_Error, oneshot=True)
        copy(Blower_CurStep, Blower_ErrorStep, oneshot=True)

    comment("Synchronize current and stored step (must be at top)")
    with rung(Blower_CurStep != Blower_StoredStep):  # R6
        copy(Blower_CurStep, Blower_StoredStep)

    comment("""\
            # ==============================================================================#
            # SECTION 2: STEP IMPLEMENTATION SECTION - MODIFY THIS SECTION ONLY
            # ==============================================================================#

        FIRST STEP IS INIT
        (we will automatically set _init to 1 after Trans)

        Use `Once` as 'Entry' like actions for Steps""")
    with rung(Blower_CurStep >= 1, Blower_Error == 0):  # R7
        out(o_BlowerCt)

    comment("# after everything is done, then Trans = 1")
    with rung(Blower_CurStep == 1, Blower_tmr.Acc > 2, i_BlowerFB):  # R8
        copy(1, Blower_Trans)

    comment("Problem with either Contactor or Thermal Overload")
    with rung(Blower_CurStep >= 1, Blower_tmr.Acc > 2, ~i_BlowerFB):  # R9
        copy(1, Blower_Error)
        copy(3, Blower_ErrorStep)

    comment("""\
            # =================================================================#
            # SECTION 3: SFC Pause and Shutdown definition - Modify to Suit your project
            # =================================================================#


        Pause actions""")
    with rung(Blower_xPause == 1):  # R10
        reset(o_BlowerCt)
        copy(0, Blower_CurStep)

    comment("Pause conditions")
    with rung(Blower_xPause == 1, ~i_BlowerFB):  # R11
        copy(0, Blower__x)

    comment("Stop actions")
    with rung(Blower_xCall == 0):  # R12
        reset(o_BlowerCt)

    comment("Stop conditions & Standard shutdown procedure")
    with rung(Blower_xCall == 0):  # R13
        fill(0, ds.select(522, 526))  # Blower_xInit..Blower_ErrorStep
        copy(0, Blower_tmr.Acc)
        copy(0, Blower_CurStep_tmr.Acc)
        fill(0, ds.select(529, 535))  # Blower_ResetTmr..Blower__valstepisodd
        copy(0, Blower__x)
        reset(Blower_x)
        return_early()

    comment("""\
            # =================================================================#
            # SECTION 4: SFC EXECUTION CONTROL BOILERPLATE - DO NOT MODIFY
            # =================================================================#


        Reset handling - xReset is self-clearing, while XInit must be set back to 0 manually.""")
    with rung(Blower_xReset == 1):  # R14
        copy(0, Blower_xReset)

    comment("Check if current step is odd")
    with rung():  # R15
        calc(Blower_CurStep % 2, Blower__valstepisodd)

    comment("""\
        EVEN STEP HANDLING - SAFETY MECHANISM FOR MANUAL INTERVENTION
            # This stays ABOVE incrementing CurStep
            # If we detect an even step number (either from normal transition or manual intervention),
            # we immediately increment to the next odd step without executing any step logic.
            # This provides a safe "neutral zone" when manually changing step numbers.""")
    with rung(Blower__valstepisodd != 1, Blower_xPause == 0):  # R16
        calc(Blower_CurStep + 1, Blower_CurStep)

    comment("Step advancement when transition is triggered")
    with rung(Blower_Trans == 1):  # R17
        calc(Blower_CurStep + 1, Blower_CurStep)
        copy(0, Blower_Trans)

    comment("""\
        Built-in timer for step duration tracking
        # Note: reset after Trans""")
    with rung(Blower_CurStep == Blower_StoredStep):  # R18
        on_delay(Blower_CurStep_tmr, 0, "sec")

    comment("Mark initialization complete after first step")
    with rung(Blower_CurStep == 2):  # R19
        copy(1, Blower__init)
