# Generated by pyrung from Click ladder CSV

from pyrung import reset, rung, subroutine

from ..tags import y_BlowerCt, y_BurnerLoop, y_Buzzer, y_RotateCt


@subroutine("DisableOutputs")
def disable_outputs():
    with rung():  # R1
        reset(y_RotateCt)

    with rung():  # R2
        reset(y_BlowerCt)

    with rung():  # R3
        reset(y_BurnerLoop)

    with rung():  # R4
        reset(y_Buzzer)
