# Generated by pyrung from Click ladder CSV

from pyrung import (
    Or,
    branch,
    calc,
    comment,
    copy,
    fill,
    latch,
    on_delay,
    out,
    reset,
    return_early,
    rung,
    subroutine,
)

from ..tags import (
    Heat__init,
    Heat__val_ts_limit,
    Heat__valstepisodd,
    Heat__x,
    Heat_CurStep,
    Heat_CurStep_tmr,
    Heat_EnableLimit,
    Heat_Error,
    Heat_ErrorStep,
    Heat_Limit_Ts,
    Heat_PvTemp_F,
    Heat_ResetTmr,
    Heat_StoredStep,
    Heat_TargetTemp_F,
    Heat_tmr,
    Heat_Trans,
    Heat_TsPerDegree,
    Heat_x,
    Heat_xCall,
    Heat_xInit,
    Heat_xPause,
    Heat_xReset,
    S_DryerTemp_F,
    ds,
    i_SailRelay,
    o_BurnerLoop,
)


@subroutine("Heat")
def heat():
    comment("""\
        Error List:

        1 = Task Overtime (disabled)
        2 = Sail Switch
        3 = Not heating in Time

            # ==============================================================================#
            # SECTION 1: SFC INITIALIZATION BOILERPLATE - DO NOT MODIFY
            # ==============================================================================#""")
    with rung():  # R1
        latch(Heat_x)

    comment("Hard-coded val so that it always takes some time")
    with rung(Heat_CurStep <= 1):  # R2
        with branch(Heat__val_ts_limit > 15):
            copy(Heat__val_ts_limit, Heat_Limit_Ts)
        with branch(Heat__val_ts_limit <= 15):
            copy(15, Heat_Limit_Ts)

    comment("Shared Resets for Init and Reset")
    with rung(Or(Heat_xInit == 1, Heat_xReset == 1)):  # R3
        copy(0, Heat__init)
        copy(0, Heat_tmr.Acc)
        copy(0, Heat_CurStep_tmr.Acc)
        fill(1, ds.select(571, 572))  # Heat_CurStep..Heat_StoredStep
        fill(0, ds.select(565, 566))  # Heat_Error..Heat_ErrorStep

    comment("Built-in timer for step timeout detection")
    with rung():  # R4
        on_delay(Heat_tmr, Heat_Limit_Ts, "sec").reset(Heat_ResetTmr == 1)

    comment("Reset the timer reset flag after it's been processed")
    with rung(Heat_ResetTmr == 1):  # R5
        copy(0, Heat_ResetTmr)

    comment("Error detection - If step exceeds time limit")
    with rung(Heat_tmr.Acc >= Heat_Limit_Ts, Heat_EnableLimit == 1):  # R6
        copy(1, Heat_Error, oneshot=True)
        copy(Heat_CurStep, Heat_ErrorStep, oneshot=True)

    comment("Synchronize current and stored step (must be at top)")
    with rung(Heat_CurStep != Heat_StoredStep):  # R7
        copy(Heat_CurStep, Heat_StoredStep)

    comment("""\
            # ==============================================================================#
            # SECTION 2: STEP IMPLEMENTATION SECTION - MODIFY THIS SECTION ONLY
            # ==============================================================================#

        FIRST STEP IS INIT
        (we will automatically set _init to 1 after Trans)

        Use `Once` as 'Entry' like actions for Steps

        ### Copy in the current Temperature""")
    with rung():  # R8
        copy(S_DryerTemp_F, Heat_PvTemp_F)

    comment("### Calculate a dynamic seconds (Ts) limit to heat per heat `cycle`")
    with rung(Heat_CurStep == 1):  # R9
        calc((Heat_TargetTemp_F - Heat_PvTemp_F) * Heat_TsPerDegree, Heat__val_ts_limit)

    with rung(Heat_CurStep == 1, Heat_tmr.Acc > 1):  # R10
        copy(1, Heat_Trans)

    comment("Above temp? Exit")
    with rung(Heat_PvTemp_F >= Heat_TargetTemp_F):  # R11
        copy(0, Heat_xCall)

    with rung(Heat_CurStep == 3, Heat_PvTemp_F < Heat_TargetTemp_F, Heat_Error == 0):  # R12
        out(o_BurnerLoop)

    comment("Problem with either Sail Switch or Sail Relay")
    with rung(
        Heat_CurStep == 3,
        Heat_CurStep_tmr.Acc >= 1,
        ~i_SailRelay,
        Heat_Error != 2,
        Heat_xCall != 0,
        o_BurnerLoop,
    ):  # R13
        copy(2, Heat_Error)
        copy(3, Heat_ErrorStep)

    comment("Heating too long")
    with rung(Heat_tmr.Done, Heat_Error != 1):  # R14
        copy(3, Heat_Error)
        copy(3, Heat_ErrorStep)

    comment("""\
            # =================================================================#
            # SECTION 3: SFC Pause and Shutdown definition - Modify to Suit your project
            # =================================================================#


        Pause actions""")
    with rung(Heat_xPause == 1):  # R15
        reset(o_BurnerLoop)
        copy(0, Heat_CurStep)

    comment("Pause conditions")
    with rung(Heat_xPause == 1):  # R16
        copy(0, Heat__x)

    comment("Stop actions")
    with rung(Heat_xCall == 0):  # R17
        reset(o_BurnerLoop)

    comment("Stop conditions & Standard shutdown procedure")
    with rung(Heat_xCall == 0):  # R18
        fill(0, ds.select(562, 566))  # Heat_xInit..Heat_ErrorStep
        copy(0, Heat_tmr.Acc)
        copy(0, Heat_CurStep_tmr.Acc)
        fill(0, ds.select(569, 575))  # Heat_ResetTmr..Heat__valstepisodd
        copy(0, Heat__x)
        reset(Heat_x)
        return_early()

    comment("""\
            # =================================================================#
            # SECTION 4: SFC EXECUTION CONTROL BOILERPLATE - DO NOT MODIFY
            # =================================================================#


        Reset handling - xReset is self-clearing, while XInit must be set back to 0 manually.""")
    with rung(Heat_xReset == 1):  # R19
        copy(0, Heat_xReset)

    comment("Check if current step is odd")
    with rung():  # R20
        calc(Heat_CurStep % 2, Heat__valstepisodd)

    comment("""\
        EVEN STEP HANDLING - SAFETY MECHANISM FOR MANUAL INTERVENTION
            # This stays ABOVE incrementing CurStep
            # If we detect an even step number (either from normal transition or manual intervention),
            # we immediately increment to the next odd step without executing any step logic.
            # This provides a safe "neutral zone" when manually changing step numbers.""")
    with rung(Heat__valstepisodd != 1, Heat_xPause == 0):  # R21
        calc(Heat_CurStep + 1, Heat_CurStep)

    comment("Step advancement when transition is triggered")
    with rung(Heat_Trans == 1):  # R22
        calc(Heat_CurStep + 1, Heat_CurStep)
        copy(0, Heat_Trans)

    comment("""\
        Built-in timer for step duration tracking
        # Note: reset after Trans""")
    with rung(Heat_CurStep == Heat_StoredStep):  # R23
        on_delay(Heat_CurStep_tmr, 0, "sec")

    comment("Mark initialization complete after first step")
    with rung(Heat_CurStep == 2):  # R24
        copy(1, Heat__init)
