# Generated by pyrung from Click ladder CSV

from pyrung import comment, copy, rung, subroutine

from ..tags import (
    A_P1_ResumeFromPwrLoss,
    A_P2_PwrLossDebounce_Ts,
    A_P3_1stScanMinTime_Ts,
    Internal__Step,
    S_P7_CompleteBuzzTime_Ts,
    S_P8_HeatLowBand_F,
    S_P9_HeatTooHighBand_F,
    Sts_P1_OperatingTemp_F,
    Sts_P2_Dry_Tm,
    Sts_P3_Sheet_Tm,
    Sts_P4_Cooldown_Tm,
    Sts_P5_HeatHoldBackBnd_F,
    Sts_P6_HeatMaxRetry,
    Sts_StateCurrent,
    Sts_UnitModeCurrent,
    _True,
)


@subroutine("Init")
def init():
    with rung():  # R1
        copy(101, Internal__Step)

    comment("Start in Manual Mode")
    with rung():  # R2
        copy(3, Sts_UnitModeCurrent)

    comment("Start in Aborted state (safe power-up; allows mode change + Clear)")
    with rung():  # R3
        copy(9, Sts_StateCurrent)

    with rung():  # R4
        copy(135, Sts_P1_OperatingTemp_F)

    with rung():  # R5
        copy(60, Sts_P2_Dry_Tm)

    with rung():  # R6
        copy(30, Sts_P3_Sheet_Tm)

    with rung():  # R7
        copy(15, Sts_P4_Cooldown_Tm)

    with rung():  # R8
        copy(5, Sts_P5_HeatHoldBackBnd_F)

    with rung():  # R9
        copy(1, Sts_P6_HeatMaxRetry)

    with rung():  # R10
        copy(30, S_P7_CompleteBuzzTime_Ts)

    with rung():  # R11
        copy(2, S_P8_HeatLowBand_F)

    with rung():  # R12
        copy(10, S_P9_HeatTooHighBand_F)

    with rung():  # R13
        copy(_True, A_P1_ResumeFromPwrLoss)

    with rung():  # R14
        copy(30, A_P2_PwrLossDebounce_Ts)

    with rung():  # R15
        copy(300, A_P3_1stScanMinTime_Ts)
