# Generated by pyrung from Click ladder CSV

from pyrung import comment, copy, on_delay, rung, subroutine

from ..tags import (
    A_CTmr_Mnt_Aborted,
    A_CTmr_Mnt_Execute,
    A_CTmr_Mnt_Held,
    A_CTmr_Mnt_Idle,
    A_CTmr_Mnt_Stopped,
    Blower_x,
    Blower_xCall,
    Heat_xCall,
    Rotate_xCall,
    Sts_State_Aborted,
    Sts_State_Execute,
    Sts_State_Held,
    Sts_State_Idle,
    Sts_State_Starting,
    Sts_State_Stopped,
    Sts_State_Unholding,
    Sts_UnitModeCurrent,
)


@subroutine("Maint")
def maint():
    comment("Stop Rotate/Blower/Heat if not in Execute/Starting/Unholding")
    with rung(~Sts_State_Execute, ~Sts_State_Starting, ~Sts_State_Unholding):  # R1
        copy(0, Rotate_xCall)
        copy(0, Blower_xCall)
        copy(0, Heat_xCall)

    comment("Blower has to be on to call Heat")
    with rung(~Blower_x):  # R2
        copy(0, Heat_xCall)

    with rung():  # R3
        copy(2, Sts_UnitModeCurrent)

    with rung(Sts_State_Stopped):  # R4
        on_delay(A_CTmr_Mnt_Stopped, 0, "hour")

    with rung(Sts_State_Idle):  # R5
        on_delay(A_CTmr_Mnt_Idle, 0, "hour")

    with rung(Sts_State_Execute):  # R6
        on_delay(A_CTmr_Mnt_Execute, 0, "hour")

    with rung(Sts_State_Aborted):  # R7
        on_delay(A_CTmr_Mnt_Aborted, 0, "hour")

    with rung(Sts_State_Held):  # R8
        on_delay(A_CTmr_Mnt_Held, 0, "hour")
