# Generated by pyrung from Click ladder CSV

from pyrung import comment, copy, on_delay, rung, subroutine

from ..tags import (
    A_CTmr_Man_Aborted,
    A_CTmr_Man_Execute,
    A_CTmr_Man_Idle,
    A_CTmr_Man_Stopped,
    Blower_xCall,
    Heat_xCall,
    Rotate_xCall,
    Sts_State_Aborted,
    Sts_State_Execute,
    Sts_State_Idle,
    Sts_State_Stopped,
    Sts_UnitModeCurrent,
)


@subroutine("Manual")
def manual():
    comment("Manual mode disallows automatic rotate/blower/heat")
    with rung():  # R1
        copy(0, Rotate_xCall)

    with rung():  # R2
        copy(0, Blower_xCall)

    with rung():  # R3
        copy(0, Heat_xCall)

    with rung():  # R4
        copy(3, Sts_UnitModeCurrent)

    with rung(Sts_State_Stopped):  # R5
        on_delay(A_CTmr_Man_Stopped, 0, "hour")

    with rung(Sts_State_Idle):  # R6
        on_delay(A_CTmr_Man_Idle, 0, "hour")

    with rung(Sts_State_Execute):  # R7
        on_delay(A_CTmr_Man_Execute, 0, "hour")

    with rung(Sts_State_Aborted):  # R8
        on_delay(A_CTmr_Man_Aborted, 0, "hour")
