# Generated by pyrung from Click ladder CSV

from pyrung import Or, calc, comment, copy, reset, rung, subroutine

from ..tags import (
    A_CurDisabledStates_HEX,
    A_ModeTimeCurrent_tmr,
    Cmd_Mode_Maintenance,
    Cmd_Mode_Manual,
    Cmd_Mode_Production,
    Cmd_UnitMode,
    Cmd_UnitModeChgReqBool,
    Cmd_UnitModeChgRequest,
    Sts_State_Aborted,
    Sts_State_Idle,
    Sts_State_Stopped,
    Sts_UnitModeCurrent,
    c,
    dh,
    sm__modeChange_cfgidx,
)


@subroutine("ModeChange")
def mode_change():
    with rung(Cmd_Mode_Production):  # R1
        copy(1, Cmd_UnitMode, oneshot=True)

    with rung(Cmd_Mode_Maintenance):  # R2
        copy(2, Cmd_UnitMode, oneshot=True)

    with rung(Cmd_Mode_Manual):  # R3
        copy(3, Cmd_UnitMode, oneshot=True)

    with rung(Cmd_UnitMode != 0):  # R4
        reset(c.select(1004, 1006))  # Cmd_Mode_Production..Cmd_Mode_Manual

    comment("Allow Mode changes within Idle / Stopped / Aborted")
    with rung(
        Or(Sts_State_Idle, Sts_State_Stopped, Sts_State_Aborted),
        Cmd_UnitMode >= 1,
        Cmd_UnitMode <= 3,
    ):  # R5
        copy(Cmd_UnitMode, Sts_UnitModeCurrent)
        copy(0, A_ModeTimeCurrent_tmr.Acc)

    comment("""\
            # Get the current mode's disabled states configuration 
            # Mode configs are stored in DH201 thru ...""")
    with rung():  # R6
        calc(200 + Sts_UnitModeCurrent, sm__modeChange_cfgidx)

    with rung():  # R7
        copy(dh[sm__modeChange_cfgidx], A_CurDisabledStates_HEX)

    with rung():  # R8
        copy(0, Cmd_UnitModeChgReqBool)

    with rung():  # R9
        copy(0, Cmd_UnitMode)

    with rung():  # R10
        reset(Cmd_UnitModeChgRequest)
