# Generated by pyrung from Click ladder CSV

from pyrung import Or, comment, latch, rung, subroutine
from pyrung.core.system_points import system

from ..tags import (
    A_Alm1_PLC,
    A_Alm2_PLCLostData,
    _C2INT_FW_Ver_Error,
    _CPLD_Version_Error,
    _Firmware_Version_Error,
    _I_O_Config_Error,
    _I_O_Module_Error,
    _Lost_SDRAM_Data,
    _Memory_Check_Error,
    _Project_File_Error,
    _Run_Edit_Project_Error,
    _Sub_CPU_FW_Ver_Error,
    _System_Config_Error,
)


@subroutine("PLCErrors")
def plc_errors():
    comment("PLC")
    with rung(
        Or(
            system.fault.plc_error,
            _I_O_Module_Error,
            _System_Config_Error,
            _I_O_Config_Error,
            _Memory_Check_Error,
            _Project_File_Error,
            _Firmware_Version_Error,
            _Run_Edit_Project_Error,
            _Sub_CPU_FW_Ver_Error,
            _C2INT_FW_Ver_Error,
            _CPLD_Version_Error,
        )
    ):  # R1
        latch(A_Alm1_PLC)

    with rung(_Lost_SDRAM_Data):  # R2
        latch(A_Alm2_PLCLostData)
