# Generated by pyrung from Click ladder CSV

from pyrung import And, Or, calc, comment, copy, latch, on_delay, rung, subroutine
from pyrung.core.system_points import system

from ..tags import (
    A_PLCDT_MMDD,
    A_PLCDT_YYMMDD,
    A_1stScanDebounce,
    A_Alm3_1stScanWatchdog,
    A_FirstScan_hhmmss,
    A_FirstScan_YYMMDD,
    A_P3_1stScanMinTime_Ts,
    A_PLCDT_Day,
    A_PLCDT_hhmm,
    A_PLCDT_hhmmss,
    A_PLCDT_Hour,
    A_PLCDT_Minute,
    A_PLCDT_Month,
    A_PLCDT_Second,
    A_PLCDT_Year,
    A_TimeBetween1stScan_tmr,
    Test_Simulate_1st_Scan,
    _1stScanDebounce_tmr,
)


@subroutine("PLCDateTime")
def plc_date_time():
    with rung(Or(system.sys.first_scan, Test_Simulate_1st_Scan)):  # R1
        copy(1, A_1stScanDebounce)

    with rung(
        Or(And(system.sys.first_scan, A_1stScanDebounce == 0), Test_Simulate_1st_Scan),
        A_TimeBetween1stScan_tmr.Acc < A_P3_1stScanMinTime_Ts,
    ):  # R2
        latch(A_Alm3_1stScanWatchdog)

    with rung(A_1stScanDebounce == 1):  # R3
        on_delay(_1stScanDebounce_tmr, 10, "sec")

    with rung(_1stScanDebounce_tmr.Done):  # R4
        copy(0, A_1stScanDebounce)

    with rung():  # R5
        on_delay(A_TimeBetween1stScan_tmr, 0, "sec").reset(
            Or(A_1stScanDebounce == 1, Test_Simulate_1st_Scan)
        )

    comment(
        "A PLC normally reads inputs at the top of the scan and writes outputs at the bottom of the scan"
    )
    with rung(Or(system.sys.first_scan, Test_Simulate_1st_Scan)):  # R6
        calc(system.rtc.year2 * 10000 + system.rtc.month * 100 + system.rtc.day, A_FirstScan_YYMMDD)

    with rung(Or(system.sys.first_scan, Test_Simulate_1st_Scan)):  # R7
        calc(
            system.rtc.hour * 10000 + system.rtc.minute * 100 + system.rtc.second,
            A_FirstScan_hhmmss,
        )

    with rung():  # R8
        calc(system.rtc.year4 * 10000 + system.rtc.month * 100 + system.rtc.day, A_PLCDT_YYMMDD)

    with rung():  # R9
        calc(system.rtc.hour * 10000 + system.rtc.minute * 100 + system.rtc.second, A_PLCDT_hhmmss)

    with rung():  # R10
        calc(system.rtc.month * 100 + system.rtc.day, A_PLCDT_MMDD)

    with rung():  # R11
        calc(system.rtc.hour * 100 + system.rtc.minute, A_PLCDT_hhmm)

    with rung():  # R12
        copy(system.rtc.year4, A_PLCDT_Year)

    with rung():  # R13
        copy(system.rtc.month, A_PLCDT_Month)

    with rung():  # R14
        copy(system.rtc.day, A_PLCDT_Day)

    with rung():  # R15
        copy(system.rtc.hour, A_PLCDT_Hour)

    with rung():  # R16
        copy(system.rtc.minute, A_PLCDT_Minute)

    with rung():  # R17
        copy(system.rtc.second, A_PLCDT_Second)
