# Generated by pyrung from Click ladder CSV

from pyrung import comment, copy, on_delay, rung, subroutine

from ..tags import (
    A_CTmr_Prd_Aborted,
    A_CTmr_Prd_Completed,
    A_CTmr_Prd_Execute,
    A_CTmr_Prd_Held,
    A_CTmr_Prd_Idle,
    A_CTmr_Prd_Stopped,
    A_CTmr_Prd_Suspended,
    Sts_State_Aborted,
    Sts_State_Completed,
    Sts_State_Execute,
    Sts_State_Held,
    Sts_State_Idle,
    Sts_State_Stopped,
    Sts_State_Suspended,
    Sts_UnitModeCurrent,
)


@subroutine("ProductionBoilerplate")
def production_boilerplate():
    comment("BOILERPLATE FOR PRODUCTION")
    with rung():  # R1
        copy(1, Sts_UnitModeCurrent)

    with rung(Sts_State_Stopped):  # R2
        on_delay(A_CTmr_Prd_Stopped, 0, "hour")

    with rung(Sts_State_Idle):  # R3
        on_delay(A_CTmr_Prd_Idle, 0, "hour")

    with rung(Sts_State_Suspended):  # R4
        on_delay(A_CTmr_Prd_Suspended, 0, "hour")

    with rung(Sts_State_Execute):  # R5
        on_delay(A_CTmr_Prd_Execute, 0, "hour")

    with rung(Sts_State_Aborted):  # R6
        on_delay(A_CTmr_Prd_Aborted, 0, "hour")

    with rung(Sts_State_Held):  # R7
        on_delay(A_CTmr_Prd_Held, 0, "hour")

    with rung(Sts_State_Completed):  # R8
        on_delay(A_CTmr_Prd_Completed, 0, "hour")
