# Generated by pyrung from Click ladder CSV

from pyrung import And, Or, branch, calc, comment, copy, on_delay, out, reset, rung, subroutine

from ..tags import (
    A_P1_ResumeFromPwrLoss,
    A_P2_PwrLossDebounce_Ts,
    A_Prod,
    A_TimeBetween1stScan_tmr,
    Blower__init,
    Blower_x,
    Blower_xCall,
    Buzzer_tmr,
    C_P_FluffOnlyFlag,
    Cmd_CmdChgRequestBool,
    Cmd_CtrlCmd,
    Heat_x,
    Heat_xCall,
    Internal__Step,
    Ref_Cmd_Hold,
    Ref_Cmd_Reset,
    Ref_Cmd_Unsuspend,
    Rotate__init,
    Rotate_tmr,
    Rotate_x,
    Rotate_xCall,
    S_CurrHeatRetryCount,
    S_P7_CompleteBuzzTime_Ts,
    Sts_Pending1stScanSuspnd,
    Sts_State_Aborting,
    Sts_State_Completed,
    Sts_State_Completing,
    Sts_State_Execute,
    Sts_State_Holding,
    Sts_State_Resetting,
    Sts_State_Starting,
    Sts_State_Stopping,
    Sts_State_Suspended,
    Sts_State_Suspending,
    Sts_State_Unholding,
    Sts_State_Unsuspending,
    Sts_StateCompleteBool,
    _True,
    i_DoorClosed,
    i_LintDoorClosed,
    o_CompleteBuzzer,
)


@subroutine("ProductionStates")
def production_states():
    with rung(
        Sts_State_Suspended,
        A_P1_ResumeFromPwrLoss == _True,
        A_TimeBetween1stScan_tmr.Acc >= A_P2_PwrLossDebounce_Ts,
    ):  # R1
        copy(Ref_Cmd_Unsuspend, Cmd_CtrlCmd, oneshot=True)
        copy(1, Cmd_CmdChgRequestBool, oneshot=True)

    comment("Start Rotate/Blower")
    with rung(Or(Sts_State_Starting, Sts_State_Unholding, Sts_State_Unsuspending)):  # R2
        copy(1, Rotate_xCall)
        with branch(Rotate_tmr.Acc > 4):
            copy(1, Blower_xCall)

    comment("State complete when they are complete")
    with rung(
        Or(Sts_State_Starting, Sts_State_Unholding, Sts_State_Unsuspending),
        Blower__init == 1,
        Rotate__init == 1,
    ):  # R3
        copy(1, Sts_StateCompleteBool)

    comment("Stop Rotate/Blower/Heat if not in Execute/Starting/Unholding")
    with rung(
        Or(
            And(
                ~Sts_State_Execute,
                ~Sts_State_Starting,
                ~Sts_State_Unholding,
                ~Sts_State_Unsuspending,
            ),
            Sts_Pending1stScanSuspnd == 1,
        )
    ):  # R4
        copy(0, Rotate_xCall)
        copy(0, Blower_xCall)
        copy(0, Heat_xCall)

    comment("Just HOLD if door or lint-door opens")
    with rung(Sts_State_Execute, Or(~i_DoorClosed, ~i_LintDoorClosed)):  # R5
        copy(Ref_Cmd_Hold, Cmd_CtrlCmd)
        copy(1, Cmd_CmdChgRequestBool)

    comment("After SFC have stopped, say state is complete")
    with rung(
        Or(
            Sts_State_Aborting,
            Sts_State_Stopping,
            Sts_State_Holding,
            Sts_State_Completing,
            Sts_State_Suspending,
        ),
        ~Rotate_x,
        ~Blower_x,
        ~Heat_x,
    ):  # R6
        copy(1, Sts_StateCompleteBool)

    comment("Add to Tumbler Count if it completed (and not a fluff-only)")
    with rung(Sts_State_Completing, ~C_P_FluffOnlyFlag):  # R7
        copy(96, A_Prod[1].ProcessedCt)
        calc(A_Prod[1].AccProcessedCt + A_Prod[1].ProcessedCt, A_Prod[1].AccProcessedCt)

    with rung(Sts_State_Completed):  # R8
        on_delay(Buzzer_tmr, 0, "sec")

    with rung(Sts_State_Completed, Buzzer_tmr.Acc < S_P7_CompleteBuzzTime_Ts):  # R9
        out(o_CompleteBuzzer)

    with rung(Sts_State_Completed, ~i_DoorClosed):  # R10
        copy(Ref_Cmd_Reset, Cmd_CtrlCmd)
        copy(1, Cmd_CmdChgRequestBool)

    comment("Normal Resetting behavior (after completion)")
    with rung(Sts_State_Resetting):  # R11
        copy(101, Internal__Step)
        copy(1, Sts_StateCompleteBool)
        copy(0, S_CurrHeatRetryCount)
        reset(C_P_FluffOnlyFlag)
