# Generated by pyrung from Click ladder CSV

from pyrung import calc, out, rung, subroutine

from ..tags import (
    A_P2_PwrLossDebounce_Ts,
    A_TimeBetween1stScan_tmr,
    HMI_DisplayClear,
    HMI_DisplayForceClear,
    HMI_DisplayHold,
    HMI_DisplayReset,
    HMI_DisplayStart,
    HMI_DisplayStop,
    HMI_DisplayUnHold,
    HMI_DisplayUnSuspend,
    HMI_TimeLeft_Tm,
    S_CoolCycle_tmr,
    S_CurrStep_Cool,
    S_CurrStep_Dry,
    S_CurrStep_Fluff,
    S_Fluffing_tmr,
    S_HeatAtTemp_tmr,
    Sts_P2_Dry_Tm,
    Sts_P3_Fluff_Tm,
    Sts_P4_Cooldown_Tm,
    Sts_State_Aborted,
    Sts_State_Aborting,
    Sts_State_Clearing,
    Sts_State_Execute,
    Sts_State_Held,
    Sts_State_Idle,
    Sts_State_Stopped,
    Sts_State_Suspended,
    i_DoorClosed,
)


@subroutine("ProductionHMI")
def production_hmi():
    with rung(Sts_State_Idle, i_DoorClosed):  # R1
        out(HMI_DisplayStart)

    with rung(Sts_State_Execute):  # R2
        out(HMI_DisplayHold)

    with rung(Sts_State_Held, i_DoorClosed):  # R3
        out(HMI_DisplayUnHold)

    with rung(Sts_State_Suspended, i_DoorClosed):  # R4
        out(HMI_DisplayUnSuspend)

    with rung(Sts_State_Aborted):  # R5
        out(HMI_DisplayClear)

    with rung(Sts_State_Clearing):  # R6
        out(HMI_DisplayForceClear)

    with rung(Sts_State_Stopped):  # R7
        out(HMI_DisplayReset)

    with rung(~Sts_State_Aborting, ~Sts_State_Aborted):  # R8
        out(HMI_DisplayStop)

    with rung(S_CurrStep_Dry):  # R9
        calc(Sts_P2_Dry_Tm - S_HeatAtTemp_tmr.Acc, HMI_TimeLeft_Tm)

    with rung(S_CurrStep_Cool):  # R10
        calc(Sts_P4_Cooldown_Tm - S_CoolCycle_tmr.Acc, HMI_TimeLeft_Tm)

    with rung(S_CurrStep_Fluff):  # R11
        calc(Sts_P3_Fluff_Tm - S_Fluffing_tmr.Acc, HMI_TimeLeft_Tm)

    with rung(~S_CurrStep_Dry, ~S_CurrStep_Cool, ~S_CurrStep_Fluff):  # R12
        calc(0, HMI_TimeLeft_Tm)

    with rung(Sts_State_Suspended):  # R13
        calc(A_P2_PwrLossDebounce_Ts - A_TimeBetween1stScan_tmr.Acc, HMI_TimeLeft_Tm)
