# Generated by pyrung from Click ladder CSV

from pyrung import calc, comment, copy, fall, on_delay, out, rise, rung, subroutine

from ..tags import (
    C_P_FluffOnlyFlag,
    Cmd_CmdChgRequestBool,
    Cmd_CtrlCmd,
    Heat_EnableLimit,
    Heat_Error,
    Heat_x,
    Heat_xCall,
    Heat_xReset,
    HeatDelay_Tmr,
    Internal__Step,
    Internal__TransBool,
    Internal__valstepisodd,
    Ref_Cmd_Complete,
    Ref_Cmd_Hold,
    S_CoolCycle_tmr,
    S_CurrHeatRetryCount,
    S_CurrStep_Cool,
    S_CurrStep_Dry,
    S_CurrStep_Fluff,
    S_CurrStep_FlufferAdded,
    S_CurrStep_HoldForFluff,
    S_DryerTemp_F,
    S_Fluffing_tmr,
    S_HeatAtTemp_tmr,
    S_P8_HeatLowBand_F,
    S_ValHoldBackTemp_F,
    S_ValLowBandTemp_F,
    Sts_P1_OperatingTemp_F,
    Sts_P2_Dry_Tm,
    Sts_P3_Fluff_Tm,
    Sts_P4_Cooldown_Tm,
    Sts_P5_HeatHoldBackBnd_F,
    Sts_P6_HeatMaxRetry,
    Sts_State_Execute,
    Sts_State_Resetting,
    Sts_State_Starting,
    i_DoorClosed,
)


@subroutine("ProductionExecuteSteps")
def production_execute_steps():
    comment("If user calls for Fluff Only Cycle")
    with rung(Sts_State_Starting, C_P_FluffOnlyFlag):  # R1
        copy(109, Internal__Step)

    comment("Step 101 is the Heating Cycle")
    with rung(Internal__Step == 101):  # R2
        out(S_CurrStep_Dry)

    with rung(S_CurrStep_Dry, Sts_State_Execute):  # R3
        calc(Sts_P1_OperatingTemp_F - Sts_P5_HeatHoldBackBnd_F, S_ValHoldBackTemp_F)

    with rung(S_CurrStep_Dry):  # R4
        copy(1, Heat_EnableLimit, oneshot=True)

    with rung(Sts_State_Execute, S_CurrStep_Dry):  # R5
        on_delay(HeatDelay_Tmr, 10, "sec")

    with rung():  # R6
        calc(Sts_P1_OperatingTemp_F - S_P8_HeatLowBand_F, S_ValLowBandTemp_F)

    with rung(
        S_CurrStep_Dry, S_DryerTemp_F < S_ValLowBandTemp_F, ~Heat_x, HeatDelay_Tmr.Done
    ):  # R7
        copy(1, Heat_xCall)

    with rung(S_CurrStep_Dry, Heat_Error != 0, Sts_State_Execute):  # R8
        calc(S_CurrHeatRetryCount + 1, S_CurrHeatRetryCount, oneshot=True)

    comment("If within max retries, reset Heat")
    with rung(
        S_CurrStep_Dry,
        Heat_Error != 0,
        S_CurrHeatRetryCount <= Sts_P6_HeatMaxRetry,
        Sts_State_Execute,
    ):  # R9
        copy(1, Heat_xReset, oneshot=True)

    comment("On a successful heating cycle, reset our 'retry'")
    with rung(S_CurrStep_Dry, fall(Heat_x), Sts_State_Execute):  # R10
        copy(0, S_CurrHeatRetryCount)

    with rung(S_CurrStep_Dry, S_DryerTemp_F > S_ValHoldBackTemp_F, Sts_State_Execute):  # R11
        on_delay(S_HeatAtTemp_tmr, Sts_P2_Dry_Tm, "min").reset(Sts_State_Resetting)

    with rung(S_CurrStep_Dry, S_HeatAtTemp_tmr.Done, Sts_State_Execute):  # R12
        copy(1, Internal__TransBool)

    with rung(Internal__Step == 103):  # R13
        out(S_CurrStep_Cool)
        copy(0, Heat_xCall, oneshot=True)

    with rung(S_CurrStep_Cool, Sts_State_Execute):  # R14
        on_delay(S_CoolCycle_tmr, Sts_P4_Cooldown_Tm, "min").reset(Sts_State_Resetting)

    with rung(S_CurrStep_Cool, S_CoolCycle_tmr.Done, Sts_State_Execute):  # R15
        copy(1, Internal__TransBool)

    with rung(Internal__Step == 105):  # R16
        out(S_CurrStep_HoldForFluff)

    comment("Goto holding")
    with rung(S_CurrStep_HoldForFluff, Sts_State_Execute):  # R17
        copy(Ref_Cmd_Hold, Cmd_CtrlCmd)
        copy(1, Cmd_CmdChgRequestBool)

    with rung(S_CurrStep_HoldForFluff, ~i_DoorClosed):  # R18
        copy(1, Internal__TransBool)

    with rung(Internal__Step == 107):  # R19
        out(S_CurrStep_FlufferAdded)

    comment("Unhold if door is re-closed")
    with rung(S_CurrStep_FlufferAdded, Sts_State_Execute):  # R20
        copy(1, Internal__TransBool)

    with rung(Internal__Step == 109):  # R21
        out(S_CurrStep_Fluff)

    with rung(S_CurrStep_Fluff, Sts_State_Execute):  # R22
        on_delay(S_Fluffing_tmr, Sts_P3_Fluff_Tm, "min").reset(Sts_State_Resetting)

    with rung(rise(S_Fluffing_tmr.Done)):  # R23
        copy(Ref_Cmd_Complete, Cmd_CtrlCmd)
        copy(1, Cmd_CmdChgRequestBool)

    comment("""\
        EVEN STEP HANDLING - SAFETY MECHANISM FOR MANUAL INTERVENTION
            # This stays ABOVE incrementing Step
            # If we detect an even step number (either from normal transition or manual intervention),
            # we immediately increment to the next odd step without executing any step logic.
            # This provides a safe "neutral zone" when manually changing step numbers.""")
    with rung():  # R24
        calc(Internal__Step % 2, Internal__valstepisodd)

    with rung(Internal__valstepisodd != 1):  # R25
        calc(1 + Internal__Step, Internal__Step)

    with rung(Internal__TransBool == 1):  # R26
        calc(1 + Internal__Step, Internal__Step)
        copy(0, Internal__TransBool)
