# Generated by pyrung from Click ladder CSV

from pyrung import Or, calc, comment, copy, latch, on_delay, out, rung, subroutine

from ..tags import (
    A_Alm11_Rotate_Trig,
    A_Alm12_Blower_Trig,
    A_Alm13_Heat_Trig,
    A_Alm14_DoorOpen_Trig,
    A_Alm15_LintOpen_Trig,
    A_Alm16_Sail_Trig,
    A_AlmExtent,
    A_Warn11_DoorOpen,
    A_Warn12_LintDoorOpen,
    Blower_Error,
    BlowerErrorDelay_Tmr,
    Cmd_CmdChgRequestBool,
    Cmd_CtrlCmd,
    Heat_Error,
    Ref_Cmd_Abort,
    Rotate_Error,
    RotateErrorDelay_Tmr,
    S_CurrHeatRetryCount,
    S_CurrStep_Dry,
    S_P9_HeatTooHighBand_F,
    S_ValTooHiTemp_F,
    SailDelay_Tmr,
    Sts_P1_OperatingTemp_F,
    Sts_P6_HeatMaxRetry,
    Sts_State_Execute,
    Sts_State_Held,
    Sts_State_Holding,
    Sts_State_Idle,
    Sts_State_Resetting,
    Sts_State_Starting,
    Sts_State_Suspended,
    Sts_State_Suspending,
    Sts_State_Unholding,
    Sts_State_Unsuspending,
    i_DoorClosed,
    i_LintDoorClosed,
)


@subroutine("ProductionErrors")
def production_errors():
    with rung(
        A_AlmExtent != 0,
        Or(
            Sts_State_Resetting,
            Sts_State_Idle,
            Sts_State_Starting,
            Sts_State_Execute,
            Sts_State_Holding,
            Sts_State_Held,
            Sts_State_Unholding,
            Sts_State_Suspending,
            Sts_State_Suspended,
            Sts_State_Unsuspending,
        ),
    ):  # R1
        copy(Ref_Cmd_Abort, Cmd_CtrlCmd)
        copy(1, Cmd_CmdChgRequestBool)

    comment("Error with Rotate")
    with rung(
        Or(Sts_State_Starting, Sts_State_Execute, Sts_State_Unholding, Sts_State_Unsuspending),
        Rotate_Error != 0,
    ):  # R2
        on_delay(RotateErrorDelay_Tmr, 5, "sec")

    with rung(RotateErrorDelay_Tmr.Done):  # R3
        latch(A_Alm11_Rotate_Trig)

    comment("Error with Blower")
    with rung(
        Or(Sts_State_Starting, Sts_State_Execute, Sts_State_Unholding, Sts_State_Unsuspending),
        Blower_Error != 0,
    ):  # R4
        on_delay(BlowerErrorDelay_Tmr, 5, "sec")

    with rung(BlowerErrorDelay_Tmr.Done):  # R5
        latch(A_Alm12_Blower_Trig)

    comment("Error with heating")
    with rung(
        Sts_State_Execute,
        S_CurrStep_Dry,
        Heat_Error == 3,
        S_CurrHeatRetryCount > Sts_P6_HeatMaxRetry,
    ):  # R6
        latch(A_Alm13_Heat_Trig)

    comment("Door open while changing state")
    with rung(
        Or(Sts_State_Starting, Sts_State_Unholding, Sts_State_Unsuspending), ~i_DoorClosed
    ):  # R7
        latch(A_Alm14_DoorOpen_Trig)

    comment("Lint door open")
    with rung(
        Or(Sts_State_Starting, Sts_State_Unholding, Sts_State_Unsuspending), ~i_LintDoorClosed
    ):  # R8
        latch(A_Alm15_LintOpen_Trig)

    comment("Sail switch didn't close")
    with rung(Sts_State_Execute, S_CurrStep_Dry, Heat_Error == 2):  # R9
        on_delay(SailDelay_Tmr, 1, "sec")

    with rung(SailDelay_Tmr.Done):  # R10
        latch(A_Alm16_Sail_Trig)

    with rung():  # R11
        calc(Sts_P1_OperatingTemp_F + S_P9_HeatTooHighBand_F, S_ValTooHiTemp_F)

    with rung():  # R12
        pass

    with rung(Or(Sts_State_Holding, Sts_State_Held, Sts_State_Suspended), ~i_DoorClosed):  # R13
        out(A_Warn11_DoorOpen)

    with rung(Or(Sts_State_Holding, Sts_State_Held, Sts_State_Suspended), ~i_LintDoorClosed):  # R14
        out(A_Warn12_LintDoorOpen)
