# Generated by pyrung from Click ladder CSV

from pyrung import out, rung, subroutine

from ..tags import (
    i_BlowerFB,
    i_DoorClosed,
    i_LintDoorClosed,
    i_RotateFB,
    i_RotateSensor,
    i_SailRelay,
    x_BlowerFB,
    x_DoorClosed,
    x_LintDoorClosed,
    x_RotateFB,
    x_RotateSensor,
    x_SailRelay,
)


@subroutine("ReadInputs")
def read_inputs():
    with rung(x_DoorClosed):  # R1
        out(i_DoorClosed)

    with rung(x_LintDoorClosed):  # R2
        out(i_LintDoorClosed)

    with rung(x_SailRelay):  # R3
        out(i_SailRelay)

    with rung(x_RotateSensor):  # R4
        out(i_RotateSensor)

    with rung(x_RotateFB):  # R5
        out(i_RotateFB)

    with rung(x_BlowerFB):  # R6
        out(i_BlowerFB)
