# Generated by pyrung from Click ladder CSV

from pyrung import blockcopy, comment, rung, subroutine

from ..tags import Sts_R, Sts_RecipeRequested, StsCurRec


@subroutine("RecipeChange")
def recipe_change():
    with rung(Sts_RecipeRequested == 1):  # R1
        blockcopy(
            Sts_R.instance(1), StsCurRec.select(1, 50)
        )  # Sts_R1_P1_Name..Sts_R1_P50_Name  # Sts_CurRec_P1_Desc..Sts_CurRec_P50_Desc

    with rung(Sts_RecipeRequested == 2):  # R2
        blockcopy(
            Sts_R.instance(2), StsCurRec.select(1, 50)
        )  # Sts_R2_P1_Name..Sts_R2_P50_Name  # Sts_CurRec_P1_Desc..Sts_CurRec_P50_Desc

    with rung(Sts_RecipeRequested == 3):  # R3
        blockcopy(
            Sts_R.instance(3), StsCurRec.select(1, 50)
        )  # Sts_R3_P1_Name..Sts_R3_P50_Name  # Sts_CurRec_P1_Desc..Sts_CurRec_P50_Desc

    with rung(Sts_RecipeRequested == 4):  # R4
        blockcopy(
            Sts_R.instance(4), StsCurRec.select(1, 50)
        )  # Sts_R4_P1_Name..Sts_R4_P50_Name  # Sts_CurRec_P1_Desc..Sts_CurRec_P50_Desc

    with rung(Sts_RecipeRequested == 5):  # R5
        blockcopy(
            Sts_R.instance(5), StsCurRec.select(1, 50)
        )  # Sts_R5_P1_Name..Sts_R5_P50_Name  # Sts_CurRec_P1_Desc..Sts_CurRec_P50_Desc

    with rung(Sts_RecipeRequested == 6):  # R6
        blockcopy(
            Sts_R.instance(6), StsCurRec.select(1, 50)
        )  # Sts_R6_P1_Name..Sts_R6_P50_Name  # Sts_CurRec_P1_Desc..Sts_CurRec_P50_Desc

    with rung(Sts_RecipeRequested == 7):  # R7
        blockcopy(
            Sts_R.instance(7), StsCurRec.select(1, 50)
        )  # Sts_R7_P1_Name..Sts_R7_P50_Name  # Sts_CurRec_P1_Desc..Sts_CurRec_P50_Desc

    with rung(Sts_RecipeRequested == 8):  # R8
        blockcopy(
            Sts_R.instance(8), StsCurRec.select(1, 50)
        )  # Sts_R8_P1_Name..Sts_R8_P50_Name  # Sts_CurRec_P1_Desc..Sts_CurRec_P50_Desc

    with rung(Sts_RecipeRequested == 9):  # R9
        blockcopy(
            Sts_R.instance(9), StsCurRec.select(1, 50)
        )  # Sts_R9_P1_Name..Sts_R9_P50_Name  # Sts_CurRec_P1_Desc..Sts_CurRec_P50_Desc

    with rung(Sts_RecipeRequested == 10):  # R10
        blockcopy(
            Sts_R.instance(10), StsCurRec.select(1, 50)
        )  # Sts_R10_P1_Name..Sts_R10_P50_Name  # Sts_CurRec_P1_Desc..Sts_CurRec_P50_Desc

    comment("Clear Recipe Change Request and all that")
    with rung():  # R11
        pass
