# Generated by pyrung from Click ladder CSV

from pyrung import (
    Or,
    calc,
    comment,
    copy,
    fill,
    latch,
    on_delay,
    out,
    reset,
    return_early,
    rung,
    subroutine,
)

from ..tags import (
    Rotate__init,
    Rotate__valstepisodd,
    Rotate__x,
    Rotate_CurStep,
    Rotate_CurStep_tmr,
    Rotate_EnableLimit,
    Rotate_Error,
    Rotate_ErrorStep,
    Rotate_Limit_Ts,
    Rotate_ResetTmr,
    Rotate_SensorOffWD_tmr,
    Rotate_SensorOnWD_tmr,
    Rotate_StoredStep,
    Rotate_tmr,
    Rotate_Trans,
    Rotate_x,
    Rotate_xCall,
    Rotate_xInit,
    Rotate_xPause,
    Rotate_xReset,
    ds,
    i_RotateFB,
    i_RotateSensor,
    o_RotateCt,
)


@subroutine("Rotate")
def rotate():
    comment("""\
        Error List:

        1 = Not getting Feedback from Contactor (ie either contactor or thermal overload isn't getting power
        2 = Not rotating

            # ==============================================================================#
            # SECTION 1: SFC INITIALIZATION BOILERPLATE - DO NOT MODIFY
            # ==============================================================================#""")
    with rung():  # R1
        latch(Rotate_x)

    comment("Shared Resets for Init and Reset")
    with rung(Or(Rotate_xInit == 1, Rotate_xReset == 1)):  # R2
        copy(0, Rotate__init)
        copy(0, Rotate_tmr.Acc)
        copy(0, Rotate_CurStep_tmr.Acc)
        fill(1, ds.select(551, 552))  # Rotate_CurStep..Rotate_StoredStep
        fill(0, ds.select(545, 546))  # Rotate_Error..Rotate_ErrorStep

    comment("Built-in timer for step timeout detection")
    with rung():  # R3
        on_delay(Rotate_tmr, Rotate_Limit_Ts, "sec").reset(Rotate_ResetTmr == 1)

    comment("Reset the timer reset flag after it's been processed")
    with rung(Rotate_ResetTmr == 1):  # R4
        copy(0, Rotate_ResetTmr)

    comment("Error detection - If step exceeds time limit")
    with rung(Rotate_tmr.Acc >= Rotate_Limit_Ts, Rotate_EnableLimit == 1):  # R5
        copy(1, Rotate_Error, oneshot=True)
        copy(Rotate_CurStep, Rotate_ErrorStep, oneshot=True)

    comment("Synchronize current and stored step (must be at top)")
    with rung(Rotate_CurStep != Rotate_StoredStep):  # R6
        copy(Rotate_CurStep, Rotate_StoredStep)

    comment("""\
            # ==============================================================================#
            # SECTION 2: STEP IMPLEMENTATION SECTION - MODIFY THIS SECTION ONLY
            # ==============================================================================#

        FIRST STEP IS INIT
        (we will automatically set _init to 1 after Trans)

        Use `Once` as 'Entry' like actions for Steps""")
    with rung(Rotate_CurStep >= 1, Rotate_Error == 0):  # R7
        out(o_RotateCt)

    comment("# after everything is done, then Trans = 1")
    with rung(Rotate_CurStep == 1, Rotate_tmr.Acc > 2, i_RotateFB):  # R8
        copy(1, Rotate_Trans)

    comment("Problem with either Contactor or Thermal Overload")
    with rung(Rotate_CurStep == 3, Rotate_tmr.Acc > 2, ~i_RotateFB):  # R9
        copy(1, Rotate_Error)
        copy(3, Rotate_ErrorStep)

    comment("Rotating sensor configuration")
    with rung(Rotate_CurStep >= 3, i_RotateSensor):  # R10
        on_delay(Rotate_SensorOnWD_tmr, 2, "sec").reset(~i_RotateSensor)

    with rung(Rotate_CurStep >= 3):  # R11
        on_delay(Rotate_SensorOffWD_tmr, 10, "sec").reset(i_RotateSensor)

    with rung(Or(Rotate_SensorOnWD_tmr.Done, Rotate_SensorOffWD_tmr.Done)):  # R12
        copy(2, Rotate_Error)
        copy(3, Rotate_ErrorStep)

    comment("""\
            # =================================================================#
            # SECTION 3: SFC Pause and Shutdown definition - Modify to Suit your project
            # =================================================================#


        Pause actions""")
    with rung(Rotate_xPause == 1):  # R13
        reset(o_RotateCt)
        copy(0, Rotate_CurStep)

    comment("Pause conditions")
    with rung(Rotate_xPause == 1, ~i_RotateFB):  # R14
        copy(0, Rotate__x)

    comment("Stop actions")
    with rung(Rotate_xCall == 0):  # R15
        reset(o_RotateCt)

    comment("Stop conditions & Standard shutdown procedure")
    with rung(Rotate_xCall == 0):  # R16
        fill(0, ds.select(542, 546))  # Rotate_xInit..Rotate_ErrorStep
        copy(0, Rotate_tmr.Acc)
        copy(0, Rotate_CurStep_tmr.Acc)
        fill(0, ds.select(549, 555))  # Rotate_ResetTmr..Rotate__valstepisodd
        copy(0, Rotate__x)
        reset(Rotate_x)
        return_early()

    comment("""\
            # =================================================================#
            # SECTION 4: SFC EXECUTION CONTROL BOILERPLATE - DO NOT MODIFY
            # =================================================================#


        Reset handling - xReset is self-clearing, while XInit must be set back to 0 manually.""")
    with rung(Rotate_xReset == 1):  # R17
        copy(0, Rotate_xReset)

    comment("Check if current step is odd")
    with rung():  # R18
        calc(Rotate_CurStep % 2, Rotate__valstepisodd)

    comment("""\
        EVEN STEP HANDLING - SAFETY MECHANISM FOR MANUAL INTERVENTION
            # This stays ABOVE incrementing CurStep
            # If we detect an even step number (either from normal transition or manual intervention),
            # we immediately increment to the next odd step without executing any step logic.
            # This provides a safe "neutral zone" when manually changing step numbers.""")
    with rung(Rotate__valstepisodd != 1, Rotate_xPause == 0):  # R19
        calc(Rotate_CurStep + 1, Rotate_CurStep)

    comment("Step advancement when transition is triggered")
    with rung(Rotate_Trans == 1):  # R20
        calc(Rotate_CurStep + 1, Rotate_CurStep)
        copy(0, Rotate_Trans)

    comment("""\
        Built-in timer for step duration tracking
        # Note: reset after Trans""")
    with rung(Rotate_CurStep == Rotate_StoredStep):  # R21
        on_delay(Rotate_CurStep_tmr, 0, "sec")

    comment("Mark initialization complete after first step")
    with rung(Rotate_CurStep == 2):  # R22
        copy(1, Rotate__init)
