# Generated by pyrung from Click ladder CSV

from pyrung import out, rung, subroutine

from ..tags import (
    OCmd_JogBlower,
    OCmd_JogBuzzer,
    OCmd_JogRotate,
    o_BurnerLoop,
    y_BlowerCt,
    y_BurnerLoop,
    y_Buzzer,
    y_RotateCt,
)


@subroutine("SetOutputsManual")
def set_outputs_manual():
    with rung(OCmd_JogRotate):  # R1
        out(y_RotateCt)

    with rung(OCmd_JogBlower):  # R2
        out(y_BlowerCt)

    with rung(o_BurnerLoop):  # R3
        out(y_BurnerLoop)

    with rung(OCmd_JogBuzzer):  # R4
        out(y_Buzzer)
