# Generated by pyrung from Click ladder CSV

from pyrung import And, Or, out, rung, subroutine
from pyrung.core.system_points import system

from ..tags import (
    o_AlarmBuzzer,
    o_BlowerCt,
    o_BurnerLoop,
    o_Buzzer,
    o_CompleteBuzzer,
    o_RotateCt,
    y_BlowerCt,
    y_BurnerLoop,
    y_Buzzer,
    y_RotateCt,
)


@subroutine("SetOutputs")
def set_outputs():
    with rung(o_RotateCt):  # R1
        out(y_RotateCt)

    with rung(o_BlowerCt):  # R2
        out(y_BlowerCt)

    with rung(o_BurnerLoop):  # R3
        out(y_BurnerLoop)

    with rung(
        Or(
            And(o_CompleteBuzzer, system.sys.clock_1s, ~o_AlarmBuzzer),
            And(o_AlarmBuzzer, system.sys.clock_100ms, ~o_CompleteBuzzer),
        )
    ):  # R4
        out(o_Buzzer)

    with rung(o_Buzzer):  # R5
        out(y_Buzzer)
