# Generated by pyrung from Click ladder CSV

from pyrung import (
    Or,
    calc,
    comment,
    copy,
    fill,
    latch,
    on_delay,
    reset,
    return_early,
    rung,
    subroutine,
)

from ..tags import C2000, SFCExample, SFCExample__CurStep_tmr, SFCExample_tmr, SFCExample_x, ds


@subroutine("SFCExample")
def sfc_example():
    comment("""\
        SFC (Sequential Function Chart) Implementation Template for Click PLC

        IMPORTANT: STEP NUMBERING CONVENTION
        - All STEP actions must use ODD numbers (1, 3, 5, 7, etc.)
        - All TRANSITION logic occurs on the same odd number as its preceding step
        - Even numbers are used as "reset" steps that are automatically skipped

        WHY ODD STEPS?
        The ODD step convention provides two critical benefits:

        1. TROUBLESHOOTING SAFETY: If a sequence gets stuck at step N and you manually 
           decrement CurStep by 1 (setting it to N-1), you'll enter an EVEN step number.
           Since even steps contain no logic, this provides a safe "neutral" state that
           clears timers and one-shots before proceeding to the previous step.
           
           Without this convention, manually decrementing a step could cause the system
           to immediately execute the previous step's actions, potentially creating
           unsafe conditions.

        STANDARD PATTERN FOR STEP IMPLEMENTATION:
        # Step X: [Description] (X must be ODD: 1, 3, 5, etc.)
        if eq(ds.yourName_CurStep, X):
            # Your step logic here
            pass

        # Transition X?X+2: [Description] (Transitions advance to next ODD number)
        if eq(ds.yourName_CurStep, X):
            if [your transition condition]:
                copy(1, ds.yourName_Trans)  # This will advance to step X+2""")
    with rung():  # R1
        pass

    with rung():  # R2
        latch(C2000)

    comment("""\
        #############################################################################
        # SFC IMPLEMENTATION STANDARD VARIABLE NAMING CONVENTIONS
        #############################################################################
        # The following variables should be defined for each SFC subroutine:
        # subName_xCall - ds     # External trigger to call the SFC
        # subName_xInit - ds     # External trigger to initialize the SFC
        # subName_xReset - ds    # External trigger to reset the SFC
        # subName_xPause - ds    # External trigger to pause the SFC
        # subName_Error - ds     # Flag indicating an error has occurred
        # subName_ErrorStep - ds # Step where the error occurred
        # subName_EnableLimit - ds # Enable time limit checking
        # subName_Limit_Ts - ds  # Time limit for steps in Ts (second) units
        # subName_ResetTmr - ds  # Reset timer flag
        # subName_Trans - ds     # Transition flag
        # subName_CurStep - ds   # Current step number
        # subName_StoredStep - ds # Previous step number
        # subName__x - ds       # Internal execution flag
        # subName__init - ds    # Internal initialization flag
        # subName__valstepisodd - ds # Flag indicating if current step is odd""")
    with rung():  # R3
        latch(C2000)

    comment("""\
        Add this in main:

        def main():
            \"\"\"Main program that calls the SFC subroutine when triggered.\"\"\"
            with Rung(ds.subName_xCall == 1, ds.subName_xPause != 1):
                copy(1, ds.subName__x)
             with Rung(ds.subName__x == 1:
                call(subName)

            # ==============================================================================#
            # SECTION 1: SFC INITIALIZATION BOILERPLATE - DO NOT MODIFY
            # ==============================================================================#""")
    with rung():  # R4
        latch(SFCExample_x)

    comment("Shared Resets for Init and Reset")
    with rung(Or(SFCExample.xInit == 1, SFCExample.xReset == 1)):  # R5
        copy(0, SFCExample._init)
        copy(0, SFCExample_tmr.Acc)
        copy(0, SFCExample__CurStep_tmr.Acc)
        fill(1, ds.select(511, 512))  # SFCExample: _CurStep.._StoredStep
        fill(0, ds.select(505, 506))  # SFCExample: Error..ErrorStep

    comment("Built-in timer for step timeout detection")
    with rung():  # R6
        on_delay(SFCExample_tmr, SFCExample.Limit_Ts, "sec").reset(SFCExample.ResetTmr == 1)

    comment("Reset the timer reset flag after it's been processed")
    with rung(SFCExample.ResetTmr == 1):  # R7
        copy(0, SFCExample.ResetTmr)

    comment("Error detection - If step exceeds time limit")
    with rung(SFCExample_tmr.Acc >= SFCExample.Limit_Ts, SFCExample.Limit_Enable == 1):  # R8
        copy(1, SFCExample.Error, oneshot=True)
        copy(SFCExample._CurStep, SFCExample.ErrorStep, oneshot=True)

    comment("Synchronize current and stored step (must be at top)")
    with rung(SFCExample._CurStep != SFCExample._StoredStep):  # R9
        copy(SFCExample._CurStep, SFCExample._StoredStep)

    comment("""\
            # ==============================================================================#
            # SECTION 2: STEP IMPLEMENTATION SECTION - MODIFY THIS SECTION ONLY
            # ==============================================================================#

        FIRST STEP IS INIT
        (we will automatically set _init to 1 after Trans)

        Use `Once` as 'Entry' like actions for Steps""")
    with rung(SFCExample._CurStep == 1):  # R10
        latch(C2000)

    comment("# init")
    with rung(SFCExample._CurStep == 1):  # R11
        latch(C2000)

    comment("# after everything is done, then Trans = 1")
    with rung(SFCExample._CurStep == 1, SFCExample__CurStep_tmr.Acc > 10):  # R12
        copy(1, SFCExample.Trans)

    with rung(SFCExample._CurStep == 3):  # R13
        latch(C2000)

    comment("""\
            # =================================================================#
            # SECTION 3: SFC Pause and Shutdown definition - Modify to Suit your project
            # =================================================================#


        Pause actions""")
    with rung(SFCExample.xPause == 1):  # R14
        latch(C2000)

    comment("Pause conditions")
    with rung(SFCExample.xPause == 1):  # R15
        copy(0, SFCExample._x)

    comment("Stop actions")
    with rung(SFCExample.xCall == 0):  # R16
        latch(C2000)

    comment("Stop conditions & Standard shutdown procedure")
    with rung(SFCExample.xCall == 0):  # R17
        fill(0, ds.select(502, 506))  # SFCExample: xInit..ErrorStep
        copy(0, SFCExample_tmr.Acc)
        copy(0, SFCExample__CurStep_tmr.Acc)
        fill(0, ds.select(509, 515))  # SFCExample: ResetTmr.._valstepisodd
        copy(0, SFCExample._x)
        reset(SFCExample_x)
        return_early()

    comment("""\
            # =================================================================#
            # SECTION 4: SFC EXECUTION CONTROL BOILERPLATE - DO NOT MODIFY
            # =================================================================#


        Reset handling - xReset is self-clearing, while XInit must be set back to 0 manually.""")
    with rung(SFCExample.xReset == 1):  # R18
        copy(0, SFCExample.xReset)

    comment("Check if current step is odd")
    with rung():  # R19
        calc(SFCExample._CurStep % 2, SFCExample._valstepisodd)

    comment("""\
        EVEN STEP HANDLING - SAFETY MECHANISM FOR MANUAL INTERVENTION
            # This stays ABOVE incrementing CurStep
            # If we detect an even step number (either from normal transition or manual intervention),
            # we immediately increment to the next odd step without executing any step logic.
            # This provides a safe "neutral zone" when manually changing step numbers.""")
    with rung(SFCExample._valstepisodd != 1, SFCExample.xPause == 0):  # R20
        calc(SFCExample._CurStep + 1, SFCExample._CurStep)

    comment("Step advancement when transition is triggered")
    with rung(SFCExample.Trans == 1):  # R21
        calc(SFCExample._CurStep + 1, SFCExample._CurStep)
        copy(0, SFCExample.Trans)

    comment("""\
        Built-in timer for step duration tracking
        # Note: reset after Trans""")
    with rung(SFCExample._CurStep == SFCExample._StoredStep):  # R22
        on_delay(SFCExample__CurStep_tmr, 0, "sec")

    comment("Mark initialization complete after first step")
    with rung(SFCExample._CurStep == 2):  # R23
        copy(1, SFCExample._init)
