# Generated by pyrung from Click ladder CSV

from pyrung import Or, comment, copy, reset, rung, subroutine

from ..tags import (
    Cmd_CtrlCmd,
    Ref_State_ABORTING,
    Ref_State_CLEARING,
    Ref_State_COMPLETING,
    Ref_State_HOLDING,
    Ref_State_RESETTING,
    Ref_State_STARTING,
    Ref_State_STOPPING,
    Ref_State_SUSPENDING,
    Ref_State_UNHOLDING,
    Ref_State_UNSUSPENDING,
    Sts_State_Aborted,
    Sts_State_Clearing,
    Sts_State_Completed,
    Sts_State_Completing,
    Sts_State_Execute,
    Sts_State_Held,
    Sts_State_Holding,
    Sts_State_Idle,
    Sts_State_Resetting,
    Sts_State_Starting,
    Sts_State_Stopped,
    Sts_State_Stopping,
    Sts_State_Suspended,
    Sts_State_Suspending,
    Sts_State_Unholding,
    Sts_State_Unsuspending,
    Sts_StateRequested,
    sm_isCmdValid_Yes,
)


@subroutine("sm_CtrlCmd2StateRequest")
def sm_ctrl_cmd2_state_request():
    comment("""\
        0 undefined 
        1 CLEARING 
        2 STOPPED 
        3 STARTING 
        4 IDLE 
        5 SUSPENDED 
        6 EXECUTE 
        7 STOPPING 
        8 ABORTING 
        9 ABORTED 
        10 HOLDING 
        11 HELD 
        12 UNHOLDING 
        13 SUSPENDING 
        14 UNSUSPENDING 
        15 RESETTING 
        16 COMPLETING 
        17 COMPLETED 

        THIS ORDER TO MATCH DIAGRAMIN ON PG 27 of ISA-TR88.00.02-2022


        2 = Start""")
    with rung(Cmd_CtrlCmd == 2, Sts_State_Idle):  # R1
        copy(Ref_State_STARTING, Sts_StateRequested)

    comment("1 = Reset")
    with rung(Cmd_CtrlCmd == 1, Or(Sts_State_Completed, Sts_State_Stopped)):  # R2
        copy(Ref_State_RESETTING, Sts_StateRequested)

    comment("4 = Hold")
    with rung(Cmd_CtrlCmd == 4, Or(Sts_State_Execute, Sts_State_Suspended)):  # R3
        copy(Ref_State_HOLDING, Sts_StateRequested)

    comment("5 = Unhold")
    with rung(Cmd_CtrlCmd == 5, Sts_State_Held):  # R4
        copy(Ref_State_UNHOLDING, Sts_StateRequested)

    comment("6 = Suspend")
    with rung(Cmd_CtrlCmd == 6, Sts_State_Execute):  # R5
        copy(Ref_State_SUSPENDING, Sts_StateRequested)

    comment("7 = Unsuspend")
    with rung(Cmd_CtrlCmd == 7, Sts_State_Suspended):  # R6
        copy(Ref_State_UNSUSPENDING, Sts_StateRequested)

    comment("10 = Complete")
    with rung(Cmd_CtrlCmd == 10, Or(Sts_State_Execute, Sts_State_Held, Sts_State_Suspended)):  # R7
        copy(Ref_State_COMPLETING, Sts_StateRequested)

    comment("9 = Clear")
    with rung(Cmd_CtrlCmd == 9, Sts_State_Aborted):  # R8
        copy(Ref_State_CLEARING, Sts_StateRequested)

    comment("3 = Stop")
    with rung(
        Cmd_CtrlCmd == 3,
        Or(
            Sts_State_Idle,
            Sts_State_Starting,
            Sts_State_Execute,
            Sts_State_Completing,
            Sts_State_Completed,
            Sts_State_Resetting,
            Sts_State_Holding,
            Sts_State_Held,
            Sts_State_Unholding,
            Sts_State_Suspending,
            Sts_State_Unsuspending,
        ),
    ):  # R9
        copy(Ref_State_STOPPING, Sts_StateRequested)

    comment("8 = Abort")
    with rung(
        Cmd_CtrlCmd == 8,
        Or(
            Sts_State_Idle,
            Sts_State_Starting,
            Sts_State_Execute,
            Sts_State_Completing,
            Sts_State_Completed,
            Sts_State_Resetting,
            Sts_State_Holding,
            Sts_State_Held,
            Sts_State_Unholding,
            Sts_State_Suspending,
            Sts_State_Unsuspending,
            Sts_State_Stopping,
            Sts_State_Stopped,
            Sts_State_Clearing,
        ),
    ):  # R10
        copy(Ref_State_ABORTING, Sts_StateRequested)

    with rung():  # R11
        reset(sm_isCmdValid_Yes)
