# Generated by pyrung from Click ladder CSV

from pyrung import Or, calc, comment, copy, return_early, rung, subroutine

from ..tags import (
    A_CurDisabledStates_HEX,
    A_StateTimeCurrent_tmr,
    Sts_Pending1stScanSuspnd,
    Sts_StateCompleteBool,
    Sts_StateCurrent,
    Sts_StateRequested,
    dh,
    ds,
    sm__loopindex,
    sm__where2jump,
    sm_isStateEnbl__result,
    sm_isStateEnbl__stmask,
    sm_isStateEnbl_mask_idx,
    sm_isStateEnbl_Yes,
    sm_JMP__target_ds_idx,
)


@subroutine("sm_CopyOrJumpState")
def sm_copy_or_jump_state():
    with rung():  # R1
        calc(sm__loopindex + 1, sm__loopindex)

    comment("GOTO Aborted if loops too many times")
    with rung(sm__loopindex > 10):  # R2
        copy(9, Sts_StateRequested)

    comment("""\
            # Check if the requested state is one of our hardcoded always-enabled states
            # (STOPPED, IDLE, EXECUTE, ABORTED)""")
    with rung(
        Or(
            Sts_StateRequested == 2,
            Sts_StateRequested == 4,
            Sts_StateRequested == 6,
            Sts_StateRequested == 9,
        )
    ):  # R3
        copy(1, sm_isStateEnbl_Yes)

    comment("""\
            # Calculate the bit mask for the requested state
            # We'll store state bit masks in DH301-DH317 (where DH300 is reserved)""")
    with rung():  # R4
        calc(300 + Sts_StateRequested, sm_isStateEnbl_mask_idx)

    with rung():  # R5
        copy(dh[sm_isStateEnbl_mask_idx], sm_isStateEnbl__stmask)

    comment("""\
            # Check if state is disabled by ANDing the state mask with mode config
            # If result is non-zero, state is disabled""")
    with rung():  # R6
        calc(sm_isStateEnbl__stmask & A_CurDisabledStates_HEX, sm_isStateEnbl__result)

    comment("    # If result is zero, the bit is not set in mode config, meaning state is enabled")
    with rung(sm_isStateEnbl__result == 0x0000):  # R7
        copy(1, sm_isStateEnbl_Yes)

    comment("    # if the requested state is not disabled, set it")
    with rung(sm_isStateEnbl_Yes == 1):  # R8
        copy(Sts_StateRequested, Sts_StateCurrent)
        copy(0, Sts_StateCompleteBool)
        copy(0, Sts_StateRequested)
        copy(0, sm_isStateEnbl_Yes)
        copy(0, A_StateTimeCurrent_tmr.Acc)
        copy(0, Sts_Pending1stScanSuspnd)
        return_early()

    comment("IF Requested State isn't Enabled")
    with rung():  # R9
        calc(Sts_StateRequested + 150, sm_JMP__target_ds_idx)

    with rung():  # R10
        copy(ds[sm_JMP__target_ds_idx], sm__where2jump)

    with rung(sm__where2jump != 0):  # R11
        copy(sm__where2jump, Sts_StateRequested)
