# Generated by pyrung from Click ladder CSV

from pyrung import calc, comment, copy, out, rung, subroutine

from ..tags import (
    Cmd_CtrlCmd,
    Sts_StateCurrent,
    dh,
    isCmdValid__allowed_mask,
    isCmdValid__cmd,
    isCmdValid__result,
    sm_isCmdValid__dh_base,
    sm_isCmdValid_Yes,
)


@subroutine("sm_IsCmdValid")
def sm_is_cmd_valid():
    with rung():  # R1
        calc(100 + Cmd_CtrlCmd, sm_isCmdValid__dh_base)

    comment("""\
        PLC Lookup Table (State Disabled Masks):
        State | State Value | Disabled Hex
        --------------------------------------------------
        # State Allowed Masks:
        # 0  UNDEFINED    3FF - Allowed:
        # 1  CLEARING     37F - Allowed: ABORT
        # 2  STOPPED      37E - Allowed: RESET, ABORT
        # 3  STARTING     37B - Allowed: STOP, ABORT
        # 4  IDLE         379 - Allowed: START, STOP, ABORT
        # 5  SUSPENDED    133 - Allowed: STOP, HOLD, UNSUSPEND, ABORT, COMPLETE
        # 6  EXECUTE      153 - Allowed: STOP, HOLD, SUSPEND, ABORT, COMPLETE
        # 7  STOPPING     37F - Allowed: ABORT
        # 8  ABORTING     3FF - Allowed:
        # 9  ABORTED      2FF - Allowed: CLEAR
        # 10 HOLDING      37B - Allowed: STOP, ABORT
        # 11 HELD         16B - Allowed: STOP, UNHOLD, ABORT, COMPLETE
        # 12 UNHOLDING    37B - Allowed: STOP, ABORT
        # 13 SUSPENDING   37B - Allowed: STOP, ABORT
        # 14 UNSUSPENDING 37B - Allowed: STOP, ABORT
        # 15 RESETTING    37B - Allowed: STOP, ABORT
        # 16 COMPLETING   37B - Allowed: STOP, ABORT
        # 17COMPLETED    37A - Allowed: RESET, STOP, ABORT""")
    with rung():  # R2
        copy(dh[sm_isCmdValid__dh_base], isCmdValid__cmd)

    with rung():  # R3
        copy(dh[Sts_StateCurrent], isCmdValid__allowed_mask)

    with rung():  # R4
        calc(isCmdValid__cmd & isCmdValid__allowed_mask, isCmdValid__result)

    with rung(isCmdValid__result == 0x0000):  # R5
        out(sm_isCmdValid_Yes)
