# Generated by pyrung from Click ladder CSV

from pyrung import out, rung, subroutine

from ..tags import (
    Sts_State_Aborted,
    Sts_State_Aborting,
    Sts_State_Clearing,
    Sts_State_Completed,
    Sts_State_Completing,
    Sts_State_Execute,
    Sts_State_Held,
    Sts_State_Holding,
    Sts_State_Idle,
    Sts_State_Resetting,
    Sts_State_Starting,
    Sts_State_Stopped,
    Sts_State_Stopping,
    Sts_State_Suspended,
    Sts_State_Suspending,
    Sts_State_Unholding,
    Sts_State_Unsuspending,
    Sts_StateCurrent,
)


@subroutine("sm_MapVal2State")
def sm_map_val2_state():
    with rung(Sts_StateCurrent == 1):  # R1
        out(Sts_State_Clearing)

    with rung(Sts_StateCurrent == 2):  # R2
        out(Sts_State_Stopped)

    with rung(Sts_StateCurrent == 3):  # R3
        out(Sts_State_Starting)

    with rung(Sts_StateCurrent == 4):  # R4
        out(Sts_State_Idle)

    with rung(Sts_StateCurrent == 5):  # R5
        out(Sts_State_Suspended)

    with rung(Sts_StateCurrent == 6):  # R6
        out(Sts_State_Execute)

    with rung(Sts_StateCurrent == 7):  # R7
        out(Sts_State_Stopping)

    with rung(Sts_StateCurrent == 8):  # R8
        out(Sts_State_Aborting)

    with rung(Sts_StateCurrent == 9):  # R9
        out(Sts_State_Aborted)

    with rung(Sts_StateCurrent == 10):  # R10
        out(Sts_State_Holding)

    with rung(Sts_StateCurrent == 11):  # R11
        out(Sts_State_Held)

    with rung(Sts_StateCurrent == 12):  # R12
        out(Sts_State_Unholding)

    with rung(Sts_StateCurrent == 13):  # R13
        out(Sts_State_Suspending)

    with rung(Sts_StateCurrent == 14):  # R14
        out(Sts_State_Unsuspending)

    with rung(Sts_StateCurrent == 15):  # R15
        out(Sts_State_Resetting)

    with rung(Sts_StateCurrent == 16):  # R16
        out(Sts_State_Completing)

    with rung(Sts_StateCurrent == 17):  # R17
        out(Sts_State_Completed)
