# Generated by pyrung from Click ladder CSV

from pyrung import comment, copy, reset, rung, subroutine

from ..tags import (
    Cmd_CmdChgRequestBool,
    Cmd_CtrlCmd,
    Cmd_State_Abort,
    Cmd_State_Clear,
    Cmd_State_Complete,
    Cmd_State_Hold,
    Cmd_State_Reset,
    Cmd_State_Start,
    Cmd_State_Stop,
    Cmd_State_Suspend,
    Cmd_State_Unhold,
    Cmd_State_Unsuspend,
    c,
)


@subroutine("sm_MapCmd2Val")
def sm_map_cmd2_val():
    comment("""\
        0	Undefined
        1	Reset
        2	Start
        3	Stop
        4	Hold
        5	Unhold
        6	Suspend
        7	Unsuspend
        8	Abort
        9	Clear
        10	Complete""")
    with rung():  # R1
        pass

    with rung(Cmd_State_Reset):  # R2
        copy(1, Cmd_CtrlCmd)
        copy(1, Cmd_CmdChgRequestBool)

    with rung(Cmd_State_Start):  # R3
        copy(2, Cmd_CtrlCmd)
        copy(1, Cmd_CmdChgRequestBool)

    with rung(Cmd_State_Stop):  # R4
        copy(3, Cmd_CtrlCmd)
        copy(1, Cmd_CmdChgRequestBool)

    with rung(Cmd_State_Hold):  # R5
        copy(4, Cmd_CtrlCmd)
        copy(1, Cmd_CmdChgRequestBool)

    with rung(Cmd_State_Unhold):  # R6
        copy(5, Cmd_CtrlCmd)
        copy(1, Cmd_CmdChgRequestBool)

    with rung(Cmd_State_Suspend):  # R7
        copy(6, Cmd_CtrlCmd)
        copy(1, Cmd_CmdChgRequestBool)

    with rung(Cmd_State_Unsuspend):  # R8
        copy(7, Cmd_CtrlCmd)
        copy(1, Cmd_CmdChgRequestBool)

    with rung(Cmd_State_Abort):  # R9
        copy(8, Cmd_CtrlCmd)
        copy(1, Cmd_CmdChgRequestBool)

    with rung(Cmd_State_Clear):  # R10
        copy(9, Cmd_CtrlCmd)
        copy(1, Cmd_CmdChgRequestBool)

    with rung(Cmd_State_Complete):  # R11
        copy(10, Cmd_CtrlCmd)
        copy(1, Cmd_CmdChgRequestBool)

    with rung(Cmd_CtrlCmd != 0):  # R12
        reset(c.select(1007, 1016))  # Cmd_State_Reset..Cmd_State_Complete
