# Generated by pyrung from Click ladder CSV

from pyrung import copy, reset, rung, subroutine

from ..tags import (
    Ref_State_ABORTED,
    Ref_State_COMPLETED,
    Ref_State_EXECUTE,
    Ref_State_HELD,
    Ref_State_IDLE,
    Ref_State_STOPPED,
    Ref_State_SUSPENDED,
    Sts_State_Aborting,
    Sts_State_Clearing,
    Sts_State_Completing,
    Sts_State_Holding,
    Sts_State_Resetting,
    Sts_State_Starting,
    Sts_State_Stopping,
    Sts_State_Suspending,
    Sts_State_Unholding,
    Sts_State_Unsuspending,
    Sts_StateCompleteBool,
    Sts_StateCompleteFlag,
    Sts_StateRequested,
)


@subroutine("sm_StateComplete2Request")
def sm_state_complete2_request():
    with rung(Sts_State_Starting):  # R1
        copy(Ref_State_EXECUTE, Sts_StateRequested)

    with rung(Sts_State_Completing):  # R2
        copy(Ref_State_COMPLETED, Sts_StateRequested)

    with rung(Sts_State_Resetting):  # R3
        copy(Ref_State_IDLE, Sts_StateRequested)

    with rung(Sts_State_Holding):  # R4
        copy(Ref_State_HELD, Sts_StateRequested)

    with rung(Sts_State_Unholding):  # R5
        copy(Ref_State_EXECUTE, Sts_StateRequested)

    with rung(Sts_State_Suspending):  # R6
        copy(Ref_State_SUSPENDED, Sts_StateRequested)

    with rung(Sts_State_Unsuspending):  # R7
        copy(Ref_State_EXECUTE, Sts_StateRequested)

    with rung(Sts_State_Stopping):  # R8
        copy(Ref_State_STOPPED, Sts_StateRequested)

    with rung(Sts_State_Aborting):  # R9
        copy(Ref_State_ABORTED, Sts_StateRequested)

    with rung(Sts_State_Clearing):  # R10
        copy(Ref_State_STOPPED, Sts_StateRequested)

    with rung():  # R11
        copy(0, Sts_StateCompleteBool)

    with rung():  # R12
        reset(Sts_StateCompleteFlag)
