# Generated by pyrung from Click ladder CSV

from pyrung import Or, latch, rung, subroutine

from ..tags import (
    A_Alm4_ThermError,
    _IO1_CH1_Burnout,
    _IO1_CH1_Over_Range,
    _IO1_CH1_Under_Range,
    _IO1_Module_Config,
    _IO1_Module_Error,
)


@subroutine("ThermErrors")
def therm_errors():
    with rung(
        Or(
            _IO1_Module_Error,
            _IO1_Module_Config,
            _IO1_CH1_Burnout,
            _IO1_CH1_Under_Range,
            _IO1_CH1_Over_Range,
        )
    ):  # R1
        latch(A_Alm4_ThermError)
