# Generated by pyrung from Click ladder CSV

from pyrung import copy, rung, subroutine

from ..tags import (
    C_P7_CompleteBuzzTime_Ts,
    C_P8_HeatLowBand_F,
    C_P9_HeatTooHighBand_F,
    Cmd_P1_OperatingTempF,
    Cmd_P2_Dry_Tm,
    Cmd_P3_Sheet_Tm,
    Cmd_P4_CoolDown_Tm,
    Cmd_P5_HeatHoldBackBnd_F,
    Cmd_P6_HeatMaxRetry,
    S_P7_CompleteBuzzTime_Ts,
    S_P8_HeatLowBand_F,
    S_P9_HeatTooHighBand_F,
    Sts_P1_OperatingTemp_F,
    Sts_P2_Dry_Tm,
    Sts_P3_Sheet_Tm,
    Sts_P4_Cooldown_Tm,
    Sts_P5_HeatHoldBackBnd_F,
    Sts_P6_HeatMaxRetry,
)


@subroutine("Validation")
def validation():
    with rung(Cmd_P1_OperatingTempF >= 120, Cmd_P1_OperatingTempF <= 150):  # R1
        copy(Cmd_P1_OperatingTempF, Sts_P1_OperatingTemp_F)

    with rung(Cmd_P2_Dry_Tm >= 1, Cmd_P2_Dry_Tm <= 120):  # R2
        copy(Cmd_P2_Dry_Tm, Sts_P2_Dry_Tm)

    with rung(Cmd_P3_Sheet_Tm >= 1, Cmd_P3_Sheet_Tm <= 60):  # R3
        copy(Cmd_P3_Sheet_Tm, Sts_P3_Sheet_Tm)

    with rung(Cmd_P4_CoolDown_Tm >= 1, Cmd_P4_CoolDown_Tm <= 60):  # R4
        copy(Cmd_P4_CoolDown_Tm, Sts_P4_Cooldown_Tm)

    with rung(Cmd_P5_HeatHoldBackBnd_F >= 1, Cmd_P5_HeatHoldBackBnd_F <= 10):  # R5
        copy(Cmd_P5_HeatHoldBackBnd_F, Sts_P5_HeatHoldBackBnd_F)

    with rung(Cmd_P6_HeatMaxRetry >= 1, Cmd_P6_HeatMaxRetry <= 2):  # R6
        copy(Cmd_P6_HeatMaxRetry, Sts_P6_HeatMaxRetry)

    with rung(C_P7_CompleteBuzzTime_Ts >= 0, C_P7_CompleteBuzzTime_Ts <= 120):  # R7
        copy(C_P7_CompleteBuzzTime_Ts, S_P7_CompleteBuzzTime_Ts)

    with rung(C_P8_HeatLowBand_F > 0, C_P8_HeatLowBand_F <= 5):  # R8
        copy(C_P8_HeatLowBand_F, S_P8_HeatLowBand_F)

    with rung(C_P9_HeatTooHighBand_F >= 5, C_P9_HeatTooHighBand_F <= 10):  # R9
        copy(C_P9_HeatTooHighBand_F, S_P9_HeatTooHighBand_F)
