# Generated by pyrung from Click ladder CSV

from pyrung import Or, calc, comment, copy, pack_bits, reset, rung, subroutine, unpack_to_words

from ..tags import (
    A_PLCDT_MMDD,
    A_PLCDT_hhmm,
    A_PLCDT_Second,
    WarnTimestam__status_idx,
    WarnTimestamp__ack_idx,
    WarnTimestamp__hhmm_idx,
    WarnTimestamp__idx,
    WarnTimestamp__MMDD_idx,
    WarnTimestamp__packedbit,
    WarnTimestamp__ss_idx,
    WarnTimestamp_Bit2Record,
    WarnTimestamp_Id2Stamp,
    WarnTimestamp_ManualStam,
    WarnTimestamp_StatusFlag,
    c,
    ds,
)


@subroutine("WarnTimestamp")
def warn_timestamp():
    comment("Reset subroutine bits")
    with rung(Or(WarnTimestamp_Id2Stamp < 1, WarnTimestamp_Id2Stamp > 50)):  # R1
        copy(0, WarnTimestamp_Id2Stamp)
        reset(WarnTimestamp_Bit2Record)
        copy(0, WarnTimestamp_ManualStam)

    comment("""\
        So we can have a SINGLE run when calling WarnTimestamp

        Only care about the 1 bit, but you need 2
        Pack into a DD, unpack into DS""")
    with rung():  # R2
        pack_bits(
            c.select(1063, 1064), WarnTimestamp__packedbit
        )  # WarnTimestamp_Bit2Record..WarnTimestamp__empty1

    with rung():  # R3
        unpack_to_words(
            WarnTimestamp__packedbit, ds.select(189, 190)
        )  # WarnTimestamp_StatusFlag..WarnTimestamp__empty2

    comment("When called, copy in the ID of the Warning to Warn_Id2Stamp")
    with rung():  # R4
        calc((WarnTimestamp_Id2Stamp * 10) + 3991, WarnTimestamp__idx)

    with rung():  # R5
        calc(WarnTimestamp__idx + 5, WarnTimestamp__MMDD_idx)

    with rung():  # R6
        copy(A_PLCDT_MMDD, ds[WarnTimestamp__MMDD_idx])

    with rung():  # R7
        calc(WarnTimestamp__idx + 6, WarnTimestamp__hhmm_idx)

    with rung():  # R8
        copy(A_PLCDT_hhmm, ds[WarnTimestamp__hhmm_idx])

    with rung():  # R9
        calc(WarnTimestamp__idx + 7, WarnTimestamp__ss_idx)

    with rung():  # R10
        copy(A_PLCDT_Second, ds[WarnTimestamp__ss_idx])

    with rung():  # R11
        calc(WarnTimestamp_Id2Stamp + 300, WarnTimestam__status_idx)

    with rung():  # R12
        copy(WarnTimestamp_StatusFlag, ds[WarnTimestam__status_idx])

    with rung():  # R13
        calc(WarnTimestamp__idx + 8, WarnTimestamp__ack_idx)

    comment("Reset subroutine bits")
    with rung():  # R14
        copy(0, WarnTimestamp_Id2Stamp)

    with rung():  # R15
        reset(WarnTimestamp_Bit2Record)

    with rung():  # R16
        copy(0, WarnTimestamp_ManualStam)
