"""Multi-file project output for ladder_to_pyrung_project().

Generates a Python project layout::

    pyproject.toml
    run.py
    project_to_csv.py
    src/plc/
        __init__.py
        main.py
        tags.py
        subroutines/
            __init__.py
            startup.py
            alarm_handler.py
    tests/
        conftest.py
        test_smoke.py
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Literal

from pyrung.click.codegen.collector import _scan_file_refs
from pyrung.click.codegen.emitter import (
    _emit_physical_declarations,
    _emit_plain_block_declarations,
    _emit_rung_sequence,
    _emit_slot_aliases,
    _emit_slot_overrides,
    _emit_structure_declarations,
    _emit_tag_map,
    _emit_tc_clone_declarations,
    _has_flat_tags,
    _is_trailing_return,
    _prescan_expr_funcs,
    _structure_needs_field_import,
    _structure_uses_auto,
)
from pyrung.click.codegen.models import (
    _AnalyzedRung,
    _FileRefs,
    _OperandCollection,
    _SubroutineInfo,
)
from pyrung.click.codegen.utils import _build_sub_name_map, _slugify

if TYPE_CHECKING:
    from pyrung.click.tag_map import TagMap


_GENERATED_HEADER = "# Generated by pyrung from Click ladder CSV"
_PLC_PACKAGE_DIR = "src/plc"
_WORKSPACE_LIFECYCLE_START = "<!-- pyrung:workspace-lifecycle:start -->"
_WORKSPACE_LIFECYCLE_END = "<!-- pyrung:workspace-lifecycle:end -->"

WorkspaceKind = Literal["temporary", "persistent"]

_LEGACY_README_WORKSPACE_LIFECYCLE = """\
> **Temporary workspace:** This folder exists inside CLICK's temporary project
> directory. It survives CLICK saves, but closing the CLICK application deletes
> the entire folder. Copy the whole folder elsewhere before closing CLICK if you
> want to keep your tests, backup, environment, or other work.

ClickNick keeps the most recent `rung apply` source snapshot under
`backup/src/plc/`. Use `clicknick-cli backup` to replace that snapshot manually
and `clicknick-cli restore` to replace the active `src/plc/` tree from it. This
backup is temporary too and disappears when CLICK closes.

The copied folder is useful offline: `uv run pytest`, `uv run python run.py`,
VS Code debugging, and `uv run python project_to_csv.py` continue to work.
`clicknick-cli` is different: every command targets ClickNick's active temporary
workspace, not whichever directory your terminal is in. To use `tag apply` or
`rung apply` on copied work, first copy those source edits back into the active
temporary folder. You can always export the copied project and load its
`csv_output/` through Guided Paste instead."""

_LEGACY_AGENTS_WORKSPACE_LIFECYCLE = """\
A Click save regenerates this folder from the accepted project, like refreshing
the working branch from the repository. Propose work you want accepted before
the engineer saves.

`backup/`, `tests/`, `pyproject.toml`, `uv.lock`, and `.venv/` survive
regeneration while this CLICK project remains open. This workspace still lives
in CLICK's temporary project folder: closing the CLICK application deletes the
entire folder, including those preserved files. Copy the whole folder elsewhere
before closing CLICK if you want to keep it.

`clicknick-cli rung apply` automatically snapshots the complete active
`src/plc/` tree to `backup/src/plc/` before exporting. Use
`clicknick-cli backup` to replace that recovery snapshot at any other time, and
`clicknick-cli restore` to replace active `src/plc/` from it. The backup is for
recovering a proposal after regeneration or a failed export; keep editing and
applying from `src/plc/`, not from `backup/`.

If ClickNick restarts or the generated project refreshes after `rung apply` but
before the engineer pastes, the proposal is still recoverable. Run
`clicknick-cli restore`, then rerun `rung apply`. If CLICK
Programming Software itself was closed, the temporary backup is gone unless
the project folder was copied or exported elsewhere.

A copied folder is an offline project, not the active ClickNick workspace. Its
tests, `run.py`, VS Code debugger, and `project_to_csv.py` continue to work.
Every `clicknick-cli` command is routed to ClickNick's active temporary folder,
regardless of the terminal's current directory. Copy offline source edits back
into the active folder before `tag apply` or `rung apply`, or export locally and
load `csv_output/` through Guided Paste."""

_SCAFFOLDING_FILES = frozenset(
    {
        "pyproject.toml",
        "README.md",
        ".gitignore",
        ".vscode/launch.json",
        ".vscode/extensions.json",
        "AGENTS.md",
        "CLAUDE.md",
        "click-cheatsheet.md",
        ".claude/settings.json",
        "tests/conftest.py",
        "tests/test_smoke.py",
    }
)


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------


def _generate_project(
    rungs: list[_AnalyzedRung],
    collection: _OperandCollection,
    nicknames: dict[str, str] | None,
    subroutines: list[_SubroutineInfo],
    *,
    structured_map: TagMap | None = None,
    index: bool = False,
    machine_name: str = "PLC",
    workspace_kind: WorkspaceKind = "temporary",
) -> dict[str, str]:
    """Generate a multi-file pyrung project.

    Returns ``{relative_path: content}`` — ready to write to disk or inspect.
    """
    # Pre-scan expression functions so imports are complete.
    _prescan_expr_funcs(rungs, collection, subroutines or None)

    sub_name_map = _build_sub_name_map(subroutines)
    # call_func_map: subroutine display name → Python function identifier
    call_func_map = sub_name_map

    files: dict[str, str] = {}

    files[f"{_PLC_PACKAGE_DIR}/__init__.py"] = ""

    # tags.py
    files[f"{_PLC_PACKAGE_DIR}/tags.py"] = _generate_tags_file(collection)

    # subroutines/
    if subroutines:
        files[f"{_PLC_PACKAGE_DIR}/subroutines/__init__.py"] = ""
        for sub in subroutines:
            func_name = sub_name_map[sub.name]
            files[f"{_PLC_PACKAGE_DIR}/subroutines/{func_name}.py"] = _generate_subroutine_file(
                sub,
                collection,
                nicknames,
                structured_map=structured_map,
                call_func_map=call_func_map,
                index=index,
            )

    # main.py
    files[f"{_PLC_PACKAGE_DIR}/main.py"] = _generate_main_file(
        rungs,
        collection,
        nicknames,
        subroutines,
        structured_map=structured_map,
        call_func_map=call_func_map,
        index=index,
    )

    # run.py
    files["run.py"] = _generate_run_file()

    # project_to_csv.py
    files["project_to_csv.py"] = _generate_export_file()

    # .vscode/launch.json
    files[".vscode/launch.json"] = _generate_launch_json()

    # .vscode/extensions.json
    files[".vscode/extensions.json"] = _generate_extensions_json()

    # pyproject.toml
    files["pyproject.toml"] = _generate_pyproject()

    # README
    files["README.md"] = _generate_readme(workspace_kind)

    files[".gitignore"] = _generate_gitignore()

    # --- Agent workspace artifacts ---

    files["click-cheatsheet.md"] = _generate_cheatsheet()

    files["AGENTS.md"] = _generate_agents_md(
        rungs,
        collection,
        subroutines,
        machine_name,
        workspace_kind,
    )
    files["CLAUDE.md"] = "@AGENTS.md\n"

    files[".claude/settings.json"] = _generate_claude_settings()

    files["tests/conftest.py"] = _generate_conftest()
    files["tests/test_smoke.py"] = _generate_test_smoke()

    return files


# ---------------------------------------------------------------------------
# run.py
# ---------------------------------------------------------------------------


def _generate_pyproject() -> str:
    """Generate a private, installable project with test dependencies."""
    return """\
[project]
name = "plc-logic"
version = "0.1.0"
requires-python = ">=3.11"
classifiers = [
    "Private :: Do Not Upload",
]
dependencies = [
    "pyrung>=0.12.0",
]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/plc"]
"""


def _workspace_lifecycle_section(body: str) -> str:
    return f"{_WORKSPACE_LIFECYCLE_START}\n{body}\n{_WORKSPACE_LIFECYCLE_END}"


def _marked_workspace_lifecycle(content: str) -> str | None:
    if content.count(_WORKSPACE_LIFECYCLE_START) != 1:
        return None
    if content.count(_WORKSPACE_LIFECYCLE_END) != 1:
        return None
    start = content.index(_WORKSPACE_LIFECYCLE_START)
    end = content.find(_WORKSPACE_LIFECYCLE_END, start)
    if end < 0:
        return None
    end += len(_WORKSPACE_LIFECYCLE_END)
    return content[start:end]


def refresh_workspace_lifecycle_guidance(existing: str, generated: str) -> str:
    """Refresh pyrung-owned workspace guidance while preserving surrounding edits.

    Marked lifecycle sections are replaceable generated content. Exact legacy
    sections emitted before the markers were introduced are migrated once; any
    other unmarked content is treated as user-authored and left unchanged.
    """
    replacement = _marked_workspace_lifecycle(generated)
    if replacement is None:
        return existing

    current = _marked_workspace_lifecycle(existing)
    if current is not None:
        return existing.replace(current, replacement, 1)

    for legacy in (
        _LEGACY_README_WORKSPACE_LIFECYCLE,
        _LEGACY_AGENTS_WORKSPACE_LIFECYCLE,
    ):
        if legacy in existing:
            return existing.replace(legacy, replacement, 1)
    return existing


def _readme_workspace_lifecycle(workspace_kind: WorkspaceKind) -> str:
    if workspace_kind == "temporary":
        body = _LEGACY_README_WORKSPACE_LIFECYCLE
    else:
        body = """\
> **Persistent workspace:** ClickNick stores this folder outside CLICK's
> temporary project directory. Closing CLICK ends the active connection but
> does not delete this workspace, its tests, or its recovery snapshot.

ClickNick keeps the most recent `rung apply` source snapshot under
`backup/src/plc/`. Use `clicknick-cli backup` to replace that snapshot manually
and `clicknick-cli restore` to replace the active `src/plc/` tree from it. The
snapshot remains in this workspace after CLICK closes.

Offline tools such as `uv run pytest`, `uv run python run.py`, VS Code debugging,
and `uv run python project_to_csv.py` work directly from this folder.
`clicknick-cli` commands target ClickNick's configured active workspace,
regardless of the terminal's current directory, and require ClickNick to be open
and connected to the matching CLICK project."""
    return _workspace_lifecycle_section(body)


def _agents_workspace_lifecycle(workspace_kind: WorkspaceKind) -> str:
    if workspace_kind == "temporary":
        body = _LEGACY_AGENTS_WORKSPACE_LIFECYCLE
    else:
        body = """\
A Click save regenerates `src/plc/` from the accepted project, like refreshing
the working branch from the repository. Propose work you want accepted before
the engineer saves.

`backup/`, `tests/`, `pyproject.toml`, `uv.lock`, and `.venv/` survive
regeneration and remain on disk after CLICK closes. Closing CLICK ends the live
connection; it does not delete this configured workspace.

`clicknick-cli rung apply` automatically snapshots the complete active
`src/plc/` tree to `backup/src/plc/` before exporting. Use
`clicknick-cli backup` to replace that recovery snapshot at any other time, and
`clicknick-cli restore` to replace active `src/plc/` from it. The backup is for
recovering a proposal after regeneration or a failed export; keep editing and
applying from `src/plc/`, not from `backup/`.

If ClickNick restarts, CLICK closes, or the generated project refreshes after
`rung apply` but before the engineer pastes, the proposal remains in this
workspace. Reopen the matching CLICK project and reconnect ClickNick, then run
`clicknick-cli restore` and rerun `rung apply`.

Every `clicknick-cli` command is routed to ClickNick's configured active
workspace, regardless of the terminal's current directory. The files remain
available offline, but CLI commands require ClickNick to be open and connected
to the matching CLICK project."""
    return _workspace_lifecycle_section(body)


def _generate_readme(workspace_kind: WorkspaceKind) -> str:
    """Generate README.md with setup instructions."""
    lifecycle = _readme_workspace_lifecycle(workspace_kind)
    return f"""\
# Setup

{lifecycle}

1. Install [uv](https://docs.astral.sh/uv/getting-started/installation/) if you haven't already:

       powershell -ExecutionPolicy ByPass -c "irm https://astral.sh/uv/install.ps1 | iex"

2. Create the virtual environment and install dependencies:

       uv sync

3. Install the pyrung debugger extension for VS Code.
   Download `pyrung-debug-*.vsix` from the
   [latest release](https://github.com/ssweber/pyrung/releases), then:

       code --install-extension pyrung-debug-0.12.0.vsix

4. Open this folder in VS Code, press F5 to debug.

# Loading into Click Programming Software

`csv/` is the regenerated snapshot of the ladder currently accepted in CLICK.
Treat it as reference input. `csv_output/` is the proposed ladder export created
from edits in `src/plc/`; this is the folder you load through Guided Paste.

1. Re-export the project to Click ladder CSV (picks up any edits you've made):

       uv run python project_to_csv.py

2. Install [ClickNick](https://github.com/ssweber/clicknick):

       uv tool install clicknick

3. With CLICK and ClickNick open, confirm that ClickNick sees this project:

       clicknick-cli rung list

   ClickNick itself provides the `clicknick-cli` session. The Console window is
   not required for those commands. For simulation and analysis through
   `uv run pyrung live`, ask the engineer to choose **Tools → Console** and keep
   it open; closing the Console ends that pyrung live session.

   This lists `main` and the available subroutine files. Use
   `clicknick-cli rung list main` to list the main program's rung numbers and
   comments.

4. In Click Programming Software, go to **Ladder → Open in Guided Paste...**
   and point it at the `csv_output` folder.

   ClickNick walks you through pasting each rung and subroutine into Click
   with addresses and nicknames already wired up.
"""


def _generate_gitignore() -> str:
    """Generate ignores for local environments, caches, and exported CSVs."""
    return """\
.venv/
__pycache__/
*.py[cod]
.pytest_cache/
csv_output/
"""


def _generate_extensions_json() -> str:
    """Generate .vscode/extensions.json recommending the pyrung debugger."""
    import json

    config = {
        "recommendations": [
            "ssweber.pyrung-debug",
        ]
    }
    return json.dumps(config, indent=2) + "\n"


def _generate_launch_json() -> str:
    """Generate .vscode/launch.json for the pyrung debugger extension."""
    import json

    config = {
        "version": "0.2.0",
        "configurations": [
            {
                "name": "Debug PLC Logic",
                "type": "pyrung",
                "request": "launch",
                "program": "${workspaceFolder}/run.py",
                "pythonPath": "${workspaceFolder}/.venv/Scripts/python.exe",
                "autoReload": True,
            }
        ],
    }
    return json.dumps(config, indent=2) + "\n"


def _generate_run_file() -> str:
    """Generate run.py: instantiate PLC and step the logic."""
    return """\
from pyrung import PLC
from plc.main import logic

runner = PLC(logic)
runner.step()
print(f"Scan {runner.current_state.scan_id}: OK")
"""


def _generate_export_file() -> str:
    """Generate project_to_csv.py: convert the pyrung project back to Click CSV.

    Passes the ``blocks`` ClickBlockSet to ``to_nickname_file`` so
    configured-but-unmapped slots (plain nicknames and annotations, the bulk of
    the address table) are written — not just the handful of addresses reachable
    through TagMap ``map_to`` entries.
    """
    return '''\
"""Export this pyrung project back to Click ladder CSV files."""

from pathlib import Path

from pyrung.click import pyrung_to_ladder
from plc.main import logic
from plc.tags import mapping, blocks

here = Path(__file__).parent
output_dir = here / "csv_output"
bundle = pyrung_to_ladder(logic, mapping)
bundle.write(output_dir)

mapping.to_nickname_file(output_dir / "nicknames.csv", blocks=blocks)

print(f"Wrote CSV to {output_dir}")
'''


# ---------------------------------------------------------------------------
# tags.py
# ---------------------------------------------------------------------------


def _generate_tags_file(collection: _OperandCollection) -> str:
    """Generate tags.py: declarations + TagMap."""
    lines: list[str] = [_GENERATED_HEADER, ""]

    # Imports
    _emit_tags_imports(lines, collection)
    lines.append("")

    if collection.physical_decls:
        lines.append("# --- Physical ---")
        _emit_physical_declarations(lines, collection)
        lines.append("")

    # Tag declarations
    if _has_flat_tags(collection):
        lines.append("# --- Tags ---")
        _emit_slot_aliases(lines, collection, suppress_comments=True)
        lines.append("")

    if collection.timer_counter_clones:
        lines.append("# --- Clones ---")
        _emit_tc_clone_declarations(lines, collection)
        lines.append("")

    if collection.plain_blocks:
        lines.append("# --- Blocks ---")
        _emit_plain_block_declarations(lines, collection)
        lines.append("")

    # Structure declarations
    if collection.structures:
        lines.append("# --- Structures ---")
        _emit_structure_declarations(lines, collection)
        lines.append("")

    # Slot name overrides for nicknamed addresses inside ranges
    _emit_slot_overrides(lines, collection)

    # TagMap
    lines.append("# --- Tag Map ---")
    _emit_tag_map(lines, collection)
    lines.append("")

    return "\n".join(lines) + "\n"


def _emit_tags_imports(lines: list[str], collection: _OperandCollection) -> None:
    """Emit imports for tags.py (types, blocks, TagMap)."""
    core: list[str] = []

    # Block/TagType for reconstructed plain named blocks
    if collection.plain_blocks:
        core.append("Block")
        core.append("TagType")

    # Structure decorators
    has_named_array = any(s.structure_type == "named_array" for s in collection.structures)
    has_udt = any(s.structure_type == "udt" for s in collection.structures)
    if collection.physical_decls:
        core.append("Physical")
    if has_named_array:
        core.append("named_array")
    if has_udt:
        core.append("udt")
    if _structure_needs_field_import(collection):
        core.append("Field")
    if _structure_uses_auto(collection):
        core.append("auto")

    # Built-in Timer/Counter UDTs
    if collection.used_instructions & {"on_delay", "off_delay"}:
        core.append("Timer")
    if collection.used_instructions & {"count_up", "count_down"}:
        core.append("Counter")

    # Tag types (needed for structure field types, not for flat tags which are slot aliases)
    if collection.structures or collection.plain_blocks:
        for tt in sorted(collection.used_types):
            if tt not in core:
                core.append(tt)

    if core:
        lines.append(f"from pyrung import {', '.join(core)}")

    # Click imports
    click: list[str] = ["ClickBlocks", "TagMap"]
    lines.append(f"from pyrung.click import {', '.join(click)}")

    # Keep the ClickBlockSet bound as ``blocks`` so project_to_csv.py can pass
    # it to to_nickname_file(blocks=...). The export imports this name even for
    # a completely empty project, before any individual bank aliases are needed.
    lines.append("blocks = ClickBlocks()")
    if collection.used_blocks:
        lines.append(
            "x, y, c, t, ct, sc, ds, dd, dh, df, xd, yd, xd0u, yd0u, td, ctd, sd, txt = blocks"
        )

    # Expression functions
    if collection.used_expr_funcs:
        expr = sorted(collection.used_expr_funcs)
        lines.append(f"from pyrung.core.expression import {', '.join(expr)}")


# ---------------------------------------------------------------------------
# src/plc/subroutines/<name>.py
# ---------------------------------------------------------------------------


def _generate_subroutine_file(
    sub: _SubroutineInfo,
    collection: _OperandCollection,
    nicknames: dict[str, str] | None,
    *,
    structured_map: TagMap | None = None,
    call_func_map: dict[str, str] | None = None,
    index: bool = False,
) -> str:
    """Generate a single subroutine file with @subroutine decorator."""
    func_name = call_func_map[sub.name] if call_func_map else _slugify(sub.name)

    sub_rungs = sub.analyzed
    if sub_rungs and _is_trailing_return(sub_rungs[-1]):
        sub_rungs = sub_rungs[:-1]

    refs = _scan_file_refs(sub_rungs, collection, nicknames, call_func_map=call_func_map)

    lines: list[str] = [_GENERATED_HEADER, ""]

    # pyrung imports
    _emit_logic_imports(lines, refs, is_subroutine=True)

    # from ..tags import ...
    _emit_tags_import_line(lines, refs, module="..tags")

    # Cross-subroutine imports
    for cross_func in sorted(refs.subroutine_func_names):
        lines.append(f"from .{cross_func} import {cross_func}")

    lines.append("")
    lines.append("")

    # @subroutine("name") decorator + function
    lines.append(f'@subroutine("{sub.name}")')
    lines.append(f"def {func_name}():")
    if sub_rungs:
        _emit_rung_sequence(
            lines,
            sub_rungs,
            collection,
            nicknames,
            indent=1,
            structured_map=structured_map,
            call_func_map=call_func_map,
            index=index,
        )
    else:
        lines.append("    pass")
    lines.append("")

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# src/plc/main.py
# ---------------------------------------------------------------------------


def _generate_main_file(
    rungs: list[_AnalyzedRung],
    collection: _OperandCollection,
    nicknames: dict[str, str] | None,
    subroutines: list[_SubroutineInfo],
    *,
    structured_map: TagMap | None = None,
    call_func_map: dict[str, str] | None = None,
    index: bool = False,
) -> str:
    """Generate main.py: Program with main rungs + call() statements."""
    refs = _scan_file_refs(rungs, collection, nicknames, call_func_map=call_func_map)

    lines: list[str] = [_GENERATED_HEADER, ""]

    # pyrung imports
    has_calls = bool(subroutines)
    _emit_logic_imports(lines, refs, is_main=True, has_calls=has_calls)

    # from .tags import mapping, ...
    _emit_tags_import_line(lines, refs, include_mapping=True, module=".tags")

    # from .subroutines.X import X
    if subroutines:
        for sub in subroutines:
            func_name = call_func_map[sub.name] if call_func_map else _slugify(sub.name)
            lines.append(f"from .subroutines.{func_name} import {func_name}")

    lines.append("")

    # Program body (main rungs only, no subroutine definitions)
    lines.append("with Program() as logic:")
    if rungs:
        _emit_rung_sequence(
            lines,
            rungs,
            collection,
            nicknames,
            indent=1,
            structured_map=structured_map,
            call_func_map=call_func_map,
            index=index,
        )
    else:
        lines.append("    pass")
    lines.append("")

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Shared import helpers
# ---------------------------------------------------------------------------


def _emit_logic_imports(
    lines: list[str],
    refs: _FileRefs,
    *,
    is_main: bool = False,
    is_subroutine: bool = False,
    has_calls: bool = False,
) -> None:
    """Emit ``from pyrung import ...`` for a logic file (main or subroutine)."""
    parts: list[str] = []

    if is_main:
        parts.append("Program")
    parts.append("rung")

    if has_calls or refs.subroutine_func_names:
        parts.append("call")
    if is_subroutine:
        parts.append("subroutine")

    # Built-in Timer/Counter UDTs
    if refs.used_instructions & {"on_delay", "off_delay"}:
        parts.append("Timer")
    if refs.used_instructions & {"count_up", "count_down"}:
        parts.append("Counter")

    # Conditions
    if refs.has_Or:
        parts.append("Or")
    if refs.has_And:
        parts.append("And")
    for cw in sorted(refs.used_conditions):
        parts.append(cw)

    # Instructions
    _INSTR_MAP = {
        "out": "out",
        "latch": "latch",
        "reset": "reset",
        "copy": "copy",
        "blockcopy": "blockcopy",
        "fill": "fill",
        "math": "calc",
        "on_delay": "on_delay",
        "off_delay": "off_delay",
        "count_up": "count_up",
        "count_down": "count_down",
        "shift": "shift",
        "search": "search",
        "pack_bits": "pack_bits",
        "pack_words": "pack_words",
        "pack_text": "pack_text",
        "unpack_to_bits": "unpack_to_bits",
        "unpack_to_words": "unpack_to_words",
        "event_drum": "event_drum",
        "time_drum": "time_drum",
        "return": "return_early",
    }
    for instr_name in sorted(refs.used_instructions):
        import_name = _INSTR_MAP.get(instr_name)
        if import_name and import_name not in parts:
            parts.append(import_name)

    if refs.has_branch:
        parts.append("branch")
    if refs.has_comment:
        parts.append("comment")
    if refs.has_forloop:
        parts.append("forloop")

    # Copy converters
    for cc in sorted(refs.used_copy_converters):
        parts.append(cc)

    lines.append(f"from pyrung import {', '.join(parts)}")

    # Click imports (only if needed — blocks come from tags.py, not pyrung.click)
    click_parts: list[str] = []
    if refs.has_modbus_target:
        click_parts.append("ModbusTcpTarget")
    if refs.has_modbus_rtu_target:
        click_parts.append("ModbusRtuTarget")
    if refs.has_modbus_address:
        click_parts.append("ModbusAddress")
    if "send" in refs.used_instructions:
        click_parts.append("send")
    if "receive" in refs.used_instructions:
        click_parts.append("receive")
    if click_parts:
        lines.append(f"from pyrung.click import {', '.join(click_parts)}")

    # Expression functions
    if refs.used_expr_funcs:
        expr = sorted(refs.used_expr_funcs)
        lines.append(f"from pyrung.core.expression import {', '.join(expr)}")

    if refs.has_system_import:
        lines.append("from pyrung.core.system_points import system")


# ---------------------------------------------------------------------------
# Agent workspace artifacts
# ---------------------------------------------------------------------------

_SYSTEM_BLOCK_VARS = frozenset({"sc", "sd"})


def _generate_cheatsheet() -> str:
    """Load the bundled click-cheatsheet.md from package data."""
    from importlib.resources import files

    return (
        files("pyrung.click.codegen")
        .joinpath("data/click-cheatsheet.md")
        .read_text(encoding="utf-8")
    )


def _generate_agents_md(
    rungs: list[_AnalyzedRung],
    collection: _OperandCollection,
    subroutines: list[_SubroutineInfo],
    machine_name: str,
    workspace_kind: WorkspaceKind,
) -> str:
    """Generate AGENTS.md with program-specific metadata."""
    shape = _build_program_shape(rungs, collection, subroutines)

    sections: list[str] = []
    sections.append(f"# Machine: {machine_name}\n")

    # --- Workspace model ---
    sections.append(f"""\
## Workspace model

Think of the Click project as the repository and this generated folder as its
editable working branch. Read, test, and change the Python files here.

Use the apply workflows to propose finished changes to the engineer.
`clicknick-cli tag apply` stages tag changes and opens the Address Editor.
`clicknick-cli rung apply` validates and stages the ladder CSVs, then opens the
Rung Preview for Copy/paste. The engineer accepts the proposal by Syncing or
pasting it, then decides when to save in Click.

The CLI reports only state it can know. Tags move from `staged` to `synced`
before the engineer saves. Rungs remain `staged` while they differ from the
last saved CLICK project; copying to the clipboard is not treated as proof that
the engineer pasted them.

{_agents_workspace_lifecycle(workspace_kind)}
""")

    # --- Project orientation ---
    shape_lines = [
        """\
## Read the project

The program is ladder logic represented as Python. Read it in this order:

1. `click-cheatsheet.md` — pyrung syntax and Click terminology
2. `src/plc/tags.py` — tag declarations, types, metadata, and TagMap
3. `src/plc/main.py` — scan order, main rungs, and subroutine calls
4. Relevant files in `src/plc/subroutines/` — each machine function's logic

The Python mirrors what the engineer sees in the Click GUI editor. A few names
differ: Set → `latch`, Math → `calc`.

### Program shape
""",
        f"- Main: {shape['main_rungs']} rungs, {shape['sub_count']} subroutines",
    ]
    for s in shape["subs"]:
        shape_lines.append(f"- `{s['name']}`: {s['rungs']} rungs — {s['desc']}")
    shape_lines.append(f"- Tags: {shape['tag_summary']}")
    sections.append("\n".join(shape_lines) + "\n")

    # --- Run and inspect ---
    sections.append("""\
## Run and inspect

Run `uv sync` once to install the project, pyrung, and pytest. ClickNick provides
the live connection used by these commands:

- **`uv run pyrung live`** — simulate and analyze with patch, force, step, why, and how
- **`clicknick-cli`** — inspect Click and propose tag or rung changes
- **`clicknick-cli check`** — lint the editable proposal with the same rules as Tools → Check Program

ClickNick itself provides the live `clicknick-cli` session while the application
is open and connected to the CLICK project. The Console is the engineer's active
consent gate for `pyrung live`: before starting simulation or analysis, ask the
engineer to open **Tools → Console** in ClickNick and keep it open while you use
`uv run pyrung live`. Closing the Console ends the pyrung live session but does
not end `clicknick-cli`. If a CLI command reports
`No active ClickNick session found`, ask the engineer to verify that ClickNick is
open and connected to the project, then retry the command.

Chain commands with `;` to avoid repeated process launches.

First confirm that ClickNick can see the generated program:

    clicknick-cli rung list
    clicknick-cli rung list main

The first command lists the available program files. The second lists the main
program's rung numbers and comments.

Run `clicknick-cli check` after meaningful logic edits. It reports lint-style
program findings from the editable `src/plc` proposal; it does not replace
`rung apply`, whose validation catches failures that prevent Click export.

Structural commands such as `upstream` and `simplified` work without a snapshot.
To diagnose the machine's actual state, start from a tag snapshot. If `why()`
shows everything at defaults, ask the engineer to load one: Data > Read Data
from PLC > All > Save in Click, then select it in ClickNick before starting DAP.

Start with a few scans and a focused set of tags:

    uv run pyrung live "step 5"
    uv run pyrung live "get ExampleState ExampleOutput ExampleFault"

`step` runs scans. `get` reads tag values. Chain with `;` to patch-step-observe
in one command. Names beginning with `Example` below are placeholders: replace
them with relevant names from `src/plc/tags.py` before running the command.

## Test changes

Run `uv run pytest`. The generated smoke test checks that the whole program
loads and completes a scan. Add focused tests under `tests/` for behavior you
change, especially interlocks, state transitions, alarms, and failure cases.

`src/plc/main.py` and subroutine files are reconstructed from CLICK, so arbitrary
Python-only constants in them do not survive a save. For discrete states, keep
the durable labels in tag `choices=` metadata and use the explicit value form in
logic and tests:

    copy(State.choice("RUNNING"), State)
    assert State.value == State.choice("RUNNING")

Import `State` from `plc.tags`, not constants from `plc.main`. Comparisons also
allow the shorthand `State == "RUNNING"`; reverse codegen emits the explicit
`State.choice("RUNNING")` form when CLICK stores the underlying number.

## Choose an analysis tool

### Explore program structure

    uv run pyrung live "dataview i:"
    uv run pyrung live "upstream ExampleOutput"
    uv run pyrung live "simplified ExampleOutput"

`dataview` discovers what exists (`i:` inputs, `t:` terminals, or search by
name). `upstream`/`downstream` trace dependencies. `simplified` resolves
intermediate tags to a Boolean expression over root inputs.

### Explain the current state

    uv run pyrung live "why ExampleFault"
    uv run pyrung live "why ExampleFault ExampleOutput"

`why()` walks backward from a tag and explains how it reached its current value.
Each rung shows its contacts; `*` marks blocked paths. Multiple tags merge into
one explanation.

### Test behavior

`patch` sets a value once. The program runs normally from there.

    uv run pyrung live "patch ExampleInput true; step 1; why ExampleOutput"

`force` pins the value across scans — simulates a stuck sensor or failed
component:

    uv run pyrung live "force ExampleInput false; step 10; why ExampleFault"

Use `get` or `why()` after stepping to inspect the result.

### Ask structural what-if questions

    uv run pyrung live "cause ExampleOutput to=false"
    uv run pyrung live "effect ExampleInput from=false"
    uv run pyrung live "recovers ExampleLatch"

`cause` finds what would need to change to reach a value. `effect` traces what
a change would propagate to. `recovers` checks whether a latched bit has a
clear path. No scans needed — these are structural.

### Explore a route to a target

    uv run pyrung live "how ExampleState == 6"
    uv run pyrung live "how ExampleState == 6 avoid ExampleState == 3"

`how()` is an experimental steering aid. It reads the program backward, tries
changes on a fork, and reports a replayable path when it finds one. Use `avoid`
to exclude states from the path. Treat its route as a lead, not a verdict; if
the route looks irrelevant or implausible, set it aside.

If `how()` does not find a path, that does not mean the program is broken or the
target is unreachable. It means only that this bounded search did not find one
for the current snapshot. When its result is not useful, continue with `why()`,
focused patch/step experiments, and direct ladder review.

## Add & annotate tags (edit `src/plc/tags.py`, then `tag apply`)

Two ways to change a tag, same landing spot — both stage unsaved edits in the
Address Editor for the engineer to review and Sync.

**Edit `src/plc/tags.py`** (default, same as you edit rungs) — add a nickname
on an unused address, or annotate a slot with kwargs, then apply the whole diff:

    ds.slot(568, name='Heat_Limit_Ts', uom='degF')
    ds.slot(30, name='ExampleState', choices={0:'IDLE', 1:'FILLING', 3:'FAULTED'})

    clicknick-cli tag apply     # diff tags.py -> Address Editor, "Changed" filter

`tag apply` lands only the changed rows and opens the Address Editor on them —
the tag counterpart of the rung Copy/paste step.

**One-off `tag set-*`** — a single change without touching the file:

    clicknick-cli "tag set-choices ExampleState IDLE:0 FILLING:1 FAULTED:3"

### Save order

A save in Click regenerates pyrung_project/ and discards anything not yet
applied — un-pasted rungs, un-Synced tags. **So never save while edits are still
pending.** When a change touches both tags and rungs, ask the engineer which
order they want:

- **Together** — apply tags + rungs, then one save.
- **Tags first** — apply + Sync + save *before* you write any rung code (nothing
  pending to lose).

## Edit and apply logic changes

New logic usually needs a spare address. `unused` returns the next free
address(es) — not used in the program and carrying no content — so you never
collide with an existing tag:

    clicknick-cli unused C            # next free C bit -> C5
    clicknick-cli unused C1031 C1414  # one free bit near each neighbor (distinct)
    clicknick-cli unused DS 3         # 3 consecutive free DS

Browse existing rungs:

    clicknick-cli rung list
    clicknick-cli rung list main

### Add a new subroutine

A Python file cannot create the destination program inside CLICK. When a change
needs a new subroutine, tell the engineer the exact CLICK title and ask them to
choose **Add New Subroutine Program** (`Ctrl+U`), enter that title, and save the
empty subroutine before editing Python. An empty subroutine is enough for CLICK
to persist it.

Wait for ClickNick to regenerate this folder, then find the new file under
`src/plc/subroutines/` by its `@subroutine("Exact Title")` decorator. Do not
predict its Python filename. Edit that materialized file, then import and call
its generated function from `main.py` where appropriate. Click export appends
the terminal `return()` automatically; use `return_early()` only for an earlier
exit path.

Edit `src/plc/main.py` or an existing `src/plc/subroutines/*.py` directly. Then:

1. `clicknick-cli check` — review lint-style program findings
2. `clicknick-cli rung apply <file>` — back up `src/plc/`, validate and stage
   ladder CSVs in `csv_output/`, then open the paste window with the diff
3. Engineer clicks Copy, pastes in Click, and saves
4. ScrWatcher detects the save and auto-regenerates `pyrung_project/`

Use `--select` for a focused proposal, for example
`clicknick-cli rung apply main --select r3`. Rerun `rung apply` whenever the
proposal window needs to be refreshed or reopened.

Verify every logic change with focused tests and direct patch/step scenarios,
including the failure case. `how()` can provide additional evidence when it
finds a path, but its failure to find one is not a failed verification.

## Reference

- `src/plc/` — importable pyrung model of this machine's logic
- `backup/src/plc/` — latest source snapshot from `rung apply` or `clicknick-cli backup`
- `tests/` — smoke test and focused behavioral tests
- `csv/` — regenerated reference snapshot of the ladder accepted in CLICK
- `csv_output/` — proposed ladder export produced from edits in `src/plc/`
- `click-cheatsheet.md` — pyrung DSL quick reference (read first)
- `uv run pyrung live help` — full command list
""")

    return "\n".join(sections)


def _build_program_shape(
    rungs: list[_AnalyzedRung],
    collection: _OperandCollection,
    subroutines: list[_SubroutineInfo],
) -> dict:
    """Extract program shape metadata for AGENTS.md."""
    # Tag type distribution (exclude system tags)
    type_counts: dict[str, int] = {}
    for decl in collection.tags.values():
        if decl.block_var in _SYSTEM_BLOCK_VARS:
            continue
        type_counts[decl.tag_type] = type_counts.get(decl.tag_type, 0) + 1

    tag_parts = [f"{count} {typ}" for typ, count in sorted(type_counts.items())]
    tag_summary = ", ".join(tag_parts) if tag_parts else "none"

    subs = []
    for sub in subroutines:
        subs.append(
            {
                "name": sub.name,
                "rungs": len(sub.analyzed),
                "desc": _describe_subroutine(sub),
            }
        )

    return {
        "main_rungs": len(rungs),
        "sub_count": len(subroutines),
        "subs": subs,
        "tag_summary": tag_summary,
    }


def _describe_subroutine(sub: _SubroutineInfo) -> str:
    """One-line description of a subroutine's purpose."""
    if sub.analyzed and sub.analyzed[0].comment:
        return _first_meaningful_line(sub.analyzed[0].comment)
    return sub.name


def _first_meaningful_line(comment: str) -> str:
    """Extract the first non-decoration line from a comment block."""
    for line in comment.splitlines():
        stripped = line.strip()
        if not stripped:
            continue
        # Skip section-heading decoration (===, ---, ###, ***)
        if len(stripped) >= 3 and len(set(stripped) - {" "}) == 1:
            continue
        if stripped.startswith(("#", "=", "-", "*")) and stripped.rstrip("#=-* ") == "":
            continue
        return stripped
    return comment.splitlines()[0].strip()


def _generate_claude_settings() -> str:
    """Generate .claude/settings.json with tool permissions."""
    import json

    config = {
        "permissions": {
            "allow": [
                "Bash(clicknick-cli *)",
                "Bash(uv run pyrung live *)",
            ]
        }
    }
    return json.dumps(config, indent=2) + "\n"


def _generate_conftest() -> str:
    """Generate tests/conftest.py with PLC fixture and coverage plugin."""
    return """\
import pytest
from pyrung import PLC

pytest_plugins = ["pyrung.pytest_plugin"]


@pytest.fixture
def plc(pyrung_coverage):
    from plc.main import logic

    p = PLC(logic, dt=0.1)
    yield p
    pyrung_coverage.collect(p)
"""


def _generate_test_smoke() -> str:
    """Generate tests/test_smoke.py — program loads and steps without error."""
    return """\
def test_program_loads_and_steps(plc):
    plc.step()
    assert plc.state.scan_id == 1
"""


# ---------------------------------------------------------------------------
# Shared import helpers
# ---------------------------------------------------------------------------


def _emit_tags_import_line(
    lines: list[str],
    refs: _FileRefs,
    *,
    include_mapping: bool = False,
    module: str = ".tags",
) -> None:
    """Emit the package-relative tags import used by one logic module."""
    names: list[str] = []
    if include_mapping:
        names.append("mapping")
    names.extend(sorted(refs.tag_var_names))
    names.extend(sorted(refs.block_var_names))
    names.extend(sorted(refs.range_var_names))
    names.extend(sorted(refs.structure_names))
    names.extend(sorted(refs.tc_clone_var_names))
    names.extend(sorted(refs.used_click_blocks))

    if names:
        lines.append(f"from {module} import {', '.join(names)}")
