"""Multi-file project output for ladder_to_pyrung_project().

Generates a Python project layout::

    main.py
    tags.py
    subroutines/
        __init__.py
        startup.py
        alarm_handler.py
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from pyrung.click.codegen.collector import _scan_file_refs
from pyrung.click.codegen.emitter import (
    _emit_physical_declarations,
    _emit_plain_block_declarations,
    _emit_rung_sequence,
    _emit_slot_aliases,
    _emit_slot_overrides,
    _emit_structure_declarations,
    _emit_tag_map,
    _emit_tc_clone_declarations,
    _has_flat_tags,
    _is_trailing_return,
    _prescan_expr_funcs,
    _structure_needs_field_import,
    _structure_uses_auto,
)
from pyrung.click.codegen.models import (
    _AnalyzedRung,
    _FileRefs,
    _OperandCollection,
    _SubroutineInfo,
)
from pyrung.click.codegen.utils import _build_sub_name_map, _slugify

if TYPE_CHECKING:
    from pyrung.click.tag_map import TagMap


_GENERATED_HEADER = "# Generated by pyrung from Click ladder CSV"

_SCAFFOLDING_FILES = frozenset(
    {
        "pyproject.toml",
        "README.md",
        ".vscode/launch.json",
        ".vscode/extensions.json",
        "AGENTS.md",
        "CLAUDE.md",
        "click-cheatsheet.md",
        ".claude/settings.json",
        "tests/conftest.py",
        "tests/test_smoke.py",
    }
)


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------


def _generate_project(
    rungs: list[_AnalyzedRung],
    collection: _OperandCollection,
    nicknames: dict[str, str] | None,
    subroutines: list[_SubroutineInfo],
    *,
    structured_map: TagMap | None = None,
    index: bool = False,
    machine_name: str = "PLC",
) -> dict[str, str]:
    """Generate a multi-file pyrung project.

    Returns ``{relative_path: content}`` — ready to write to disk or inspect.
    """
    # Pre-scan expression functions so imports are complete.
    _prescan_expr_funcs(rungs, collection, subroutines or None)

    sub_name_map = _build_sub_name_map(subroutines)
    # call_func_map: subroutine display name → Python function identifier
    call_func_map = sub_name_map

    files: dict[str, str] = {}

    # tags.py
    files["tags.py"] = _generate_tags_file(collection)

    # subroutines/
    if subroutines:
        files["subroutines/__init__.py"] = ""
        for sub in subroutines:
            func_name = sub_name_map[sub.name]
            files[f"subroutines/{func_name}.py"] = _generate_subroutine_file(
                sub,
                collection,
                nicknames,
                structured_map=structured_map,
                call_func_map=call_func_map,
                index=index,
            )

    # main.py
    files["main.py"] = _generate_main_file(
        rungs,
        collection,
        nicknames,
        subroutines,
        structured_map=structured_map,
        call_func_map=call_func_map,
        index=index,
    )

    # run.py
    files["run.py"] = _generate_run_file()

    # project_to_csv.py
    files["project_to_csv.py"] = _generate_export_file()

    # .vscode/launch.json
    files[".vscode/launch.json"] = _generate_launch_json()

    # .vscode/extensions.json
    files[".vscode/extensions.json"] = _generate_extensions_json()

    # pyproject.toml
    files["pyproject.toml"] = _generate_pyproject()

    # README
    files["README.md"] = _generate_readme()

    # --- Agent workspace artifacts ---

    files["click-cheatsheet.md"] = _generate_cheatsheet()

    files["AGENTS.md"] = _generate_agents_md(rungs, collection, subroutines, machine_name)
    files["CLAUDE.md"] = "@AGENTS.md\n"

    files[".claude/settings.json"] = _generate_claude_settings()

    files["tests/conftest.py"] = _generate_conftest()
    files["tests/test_smoke.py"] = _generate_test_smoke()

    return files


# ---------------------------------------------------------------------------
# run.py
# ---------------------------------------------------------------------------


def _generate_pyproject() -> str:
    """Generate pyproject.toml with pyrung as a dependency."""
    return """\
[project]
name = "plc-logic"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "pyrung>=0.11.0",
]
"""


def _generate_readme() -> str:
    """Generate README.md with setup instructions."""
    return """\
# Setup

1. Install [uv](https://docs.astral.sh/uv/getting-started/installation/) if you haven't already:

       powershell -ExecutionPolicy ByPass -c "irm https://astral.sh/uv/install.ps1 | iex"

2. Create the virtual environment and install dependencies:

       uv sync

3. Install the pyrung debugger extension for VS Code.
   Download `pyrung-debug-*.vsix` from the
   [latest release](https://github.com/ssweber/pyrung/releases), then:

       code --install-extension pyrung-debug-0.1.0.vsix

4. Open this folder in VS Code, press F5 to debug.

# Loading into Click Programming Software

1. Re-export the project to Click ladder CSV (picks up any edits you've made):

       uv run python project_to_csv.py

2. Install [ClickNick](https://github.com/ssweber/clicknick):

       uv tool install clicknick

3. In Click Programming Software, go to **Ladder → Open in Guided Paste...**
   and point it at the `click_csv` folder.

   ClickNick walks you through pasting each rung and subroutine into Click
   with addresses and nicknames already wired up.
"""


def _generate_extensions_json() -> str:
    """Generate .vscode/extensions.json recommending the pyrung debugger."""
    import json

    config = {
        "recommendations": [
            "ssweber.pyrung-debug",
        ]
    }
    return json.dumps(config, indent=2) + "\n"


def _generate_launch_json() -> str:
    """Generate .vscode/launch.json for the pyrung debugger extension."""
    import json

    config = {
        "version": "0.2.0",
        "configurations": [
            {
                "name": "Debug PLC Logic",
                "type": "pyrung",
                "request": "launch",
                "program": "${workspaceFolder}/run.py",
                "pythonPath": "${workspaceFolder}/.venv/Scripts/python.exe",
                "autoReload": True,
            }
        ],
    }
    return json.dumps(config, indent=2) + "\n"


def _generate_run_file() -> str:
    """Generate run.py: instantiate PLC and step the logic."""
    return """\
from pyrung import PLC
from main import logic

runner = PLC(logic)
runner.step()
print(f"Scan {runner.current_state.scan_id}: OK")
"""


def _generate_export_file() -> str:
    """Generate project_to_csv.py: convert the pyrung project back to Click CSV.

    Passes the ``blocks`` ClickBlockSet to ``to_nickname_file`` so
    configured-but-unmapped slots (plain nicknames and annotations, the bulk of
    the address table) are written — not just the handful of addresses reachable
    through TagMap ``map_to`` entries.
    """
    return '''\
"""Export this pyrung project back to Click ladder CSV files."""

from pathlib import Path

from pyrung.click import pyrung_to_ladder
from main import logic
from tags import mapping, blocks

here = Path(__file__).parent
output_dir = here / "csv_output"
bundle = pyrung_to_ladder(logic, mapping, validate=False)
bundle.write(output_dir)

mapping.to_nickname_file(output_dir / "nicknames.csv", blocks=blocks)

print(f"Wrote CSV to {output_dir}")
'''


# ---------------------------------------------------------------------------
# tags.py
# ---------------------------------------------------------------------------


def _generate_tags_file(collection: _OperandCollection) -> str:
    """Generate tags.py: declarations + TagMap."""
    lines: list[str] = [_GENERATED_HEADER, ""]

    # Imports
    _emit_tags_imports(lines, collection)
    lines.append("")

    if collection.physical_decls:
        lines.append("# --- Physical ---")
        _emit_physical_declarations(lines, collection)
        lines.append("")

    # Tag declarations
    if _has_flat_tags(collection):
        lines.append("# --- Tags ---")
        _emit_slot_aliases(lines, collection, suppress_comments=True)
        lines.append("")

    if collection.timer_counter_clones:
        lines.append("# --- Clones ---")
        _emit_tc_clone_declarations(lines, collection)
        lines.append("")

    if collection.plain_blocks:
        lines.append("# --- Blocks ---")
        _emit_plain_block_declarations(lines, collection)
        lines.append("")

    # Structure declarations
    if collection.structures:
        lines.append("# --- Structures ---")
        _emit_structure_declarations(lines, collection)
        lines.append("")

    # Slot name overrides for nicknamed addresses inside ranges
    _emit_slot_overrides(lines, collection)

    # TagMap
    lines.append("# --- Tag Map ---")
    _emit_tag_map(lines, collection)
    lines.append("")

    return "\n".join(lines) + "\n"


def _emit_tags_imports(lines: list[str], collection: _OperandCollection) -> None:
    """Emit imports for tags.py (types, blocks, TagMap)."""
    core: list[str] = []

    # Block/TagType for reconstructed plain named blocks
    if collection.plain_blocks:
        core.append("Block")
        core.append("TagType")

    # Structure decorators
    has_named_array = any(s.structure_type == "named_array" for s in collection.structures)
    has_udt = any(s.structure_type == "udt" for s in collection.structures)
    if collection.physical_decls:
        core.append("Physical")
    if has_named_array:
        core.append("named_array")
    if has_udt:
        core.append("udt")
    if _structure_needs_field_import(collection):
        core.append("Field")
    if _structure_uses_auto(collection):
        core.append("auto")

    # Built-in Timer/Counter UDTs
    if collection.used_instructions & {"on_delay", "off_delay"}:
        core.append("Timer")
    if collection.used_instructions & {"count_up", "count_down"}:
        core.append("Counter")

    # Tag types (needed for structure field types, not for flat tags which are slot aliases)
    if collection.structures or collection.plain_blocks:
        for tt in sorted(collection.used_types):
            if tt not in core:
                core.append(tt)

    if core:
        lines.append(f"from pyrung import {', '.join(core)}")

    # Click imports
    click: list[str] = ["ClickBlocks", "TagMap"]
    lines.append(f"from pyrung.click import {', '.join(click)}")

    if collection.used_blocks:
        # Keep the ClickBlockSet bound as ``blocks`` so project_to_csv.py can pass
        # it to to_nickname_file(blocks=...) — without it, configured-but-unmapped
        # slots (the bulk of nicknames + all annotations) are dropped.
        lines.append("blocks = ClickBlocks()")
        lines.append(
            "x, y, c, t, ct, sc, ds, dd, dh, df, xd, yd, xd0u, yd0u, td, ctd, sd, txt = blocks"
        )

    # Expression functions
    if collection.used_expr_funcs:
        expr = sorted(collection.used_expr_funcs)
        lines.append(f"from pyrung.core.expression import {', '.join(expr)}")


# ---------------------------------------------------------------------------
# subroutines/<name>.py
# ---------------------------------------------------------------------------


def _generate_subroutine_file(
    sub: _SubroutineInfo,
    collection: _OperandCollection,
    nicknames: dict[str, str] | None,
    *,
    structured_map: TagMap | None = None,
    call_func_map: dict[str, str] | None = None,
    index: bool = False,
) -> str:
    """Generate a single subroutine file with @subroutine decorator."""
    func_name = call_func_map[sub.name] if call_func_map else _slugify(sub.name)

    sub_rungs = sub.analyzed
    if sub_rungs and _is_trailing_return(sub_rungs[-1]):
        sub_rungs = sub_rungs[:-1]

    refs = _scan_file_refs(sub_rungs, collection, nicknames, call_func_map=call_func_map)

    lines: list[str] = [_GENERATED_HEADER, ""]

    # pyrung imports
    _emit_logic_imports(lines, refs, is_subroutine=True)

    # from tags import ...
    _emit_tags_import_line(lines, refs)

    # Cross-subroutine imports
    for cross_func in sorted(refs.subroutine_func_names):
        lines.append(f"from subroutines.{cross_func} import {cross_func}")

    lines.append("")
    lines.append("")

    # @subroutine("name") decorator + function
    lines.append(f'@subroutine("{sub.name}")')
    lines.append(f"def {func_name}():")
    if sub_rungs:
        _emit_rung_sequence(
            lines,
            sub_rungs,
            collection,
            nicknames,
            indent=1,
            structured_map=structured_map,
            call_func_map=call_func_map,
            index=index,
        )
    else:
        lines.append("    pass")
    lines.append("")

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# main.py
# ---------------------------------------------------------------------------


def _generate_main_file(
    rungs: list[_AnalyzedRung],
    collection: _OperandCollection,
    nicknames: dict[str, str] | None,
    subroutines: list[_SubroutineInfo],
    *,
    structured_map: TagMap | None = None,
    call_func_map: dict[str, str] | None = None,
    index: bool = False,
) -> str:
    """Generate main.py: Program with main rungs + call() statements."""
    refs = _scan_file_refs(rungs, collection, nicknames, call_func_map=call_func_map)

    lines: list[str] = [_GENERATED_HEADER, ""]

    # pyrung imports
    has_calls = bool(subroutines)
    _emit_logic_imports(lines, refs, is_main=True, has_calls=has_calls)

    # from tags import mapping, ...
    _emit_tags_import_line(lines, refs, include_mapping=True)

    # from subroutines.X import X
    if subroutines:
        for sub in subroutines:
            func_name = call_func_map[sub.name] if call_func_map else _slugify(sub.name)
            lines.append(f"from subroutines.{func_name} import {func_name}")

    lines.append("")

    # Program body (main rungs only, no subroutine definitions)
    lines.append("with Program() as logic:")
    if rungs:
        _emit_rung_sequence(
            lines,
            rungs,
            collection,
            nicknames,
            indent=1,
            structured_map=structured_map,
            call_func_map=call_func_map,
            index=index,
        )
    else:
        lines.append("    pass")
    lines.append("")

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Shared import helpers
# ---------------------------------------------------------------------------


def _emit_logic_imports(
    lines: list[str],
    refs: _FileRefs,
    *,
    is_main: bool = False,
    is_subroutine: bool = False,
    has_calls: bool = False,
) -> None:
    """Emit ``from pyrung import ...`` for a logic file (main or subroutine)."""
    parts: list[str] = []

    if is_main:
        parts.append("Program")
    parts.append("rung")

    if has_calls or refs.subroutine_func_names:
        parts.append("call")
    if is_subroutine:
        parts.append("subroutine")

    # Built-in Timer/Counter UDTs
    if refs.used_instructions & {"on_delay", "off_delay"}:
        parts.append("Timer")
    if refs.used_instructions & {"count_up", "count_down"}:
        parts.append("Counter")

    # Conditions
    if refs.has_Or:
        parts.append("Or")
    if refs.has_And:
        parts.append("And")
    for cw in sorted(refs.used_conditions):
        parts.append(cw)

    # Instructions
    _INSTR_MAP = {
        "out": "out",
        "latch": "latch",
        "reset": "reset",
        "copy": "copy",
        "blockcopy": "blockcopy",
        "fill": "fill",
        "math": "calc",
        "on_delay": "on_delay",
        "off_delay": "off_delay",
        "count_up": "count_up",
        "count_down": "count_down",
        "shift": "shift",
        "search": "search",
        "pack_bits": "pack_bits",
        "pack_words": "pack_words",
        "pack_text": "pack_text",
        "unpack_to_bits": "unpack_to_bits",
        "unpack_to_words": "unpack_to_words",
        "event_drum": "event_drum",
        "time_drum": "time_drum",
        "return": "return_early",
    }
    for instr_name in sorted(refs.used_instructions):
        import_name = _INSTR_MAP.get(instr_name)
        if import_name and import_name not in parts:
            parts.append(import_name)

    if refs.has_branch:
        parts.append("branch")
    if refs.has_comment:
        parts.append("comment")
    if refs.has_forloop:
        parts.append("forloop")

    # Copy converters
    for cc in sorted(refs.used_copy_converters):
        parts.append(cc)

    lines.append(f"from pyrung import {', '.join(parts)}")

    # Click imports (only if needed — blocks come from tags.py, not pyrung.click)
    click_parts: list[str] = []
    if refs.has_modbus_target:
        click_parts.append("ModbusTcpTarget")
    if refs.has_modbus_rtu_target:
        click_parts.append("ModbusRtuTarget")
    if refs.has_modbus_address:
        click_parts.append("ModbusAddress")
    if "send" in refs.used_instructions:
        click_parts.append("send")
    if "receive" in refs.used_instructions:
        click_parts.append("receive")
    if click_parts:
        lines.append(f"from pyrung.click import {', '.join(click_parts)}")

    # Expression functions
    if refs.used_expr_funcs:
        expr = sorted(refs.used_expr_funcs)
        lines.append(f"from pyrung.core.expression import {', '.join(expr)}")

    if refs.has_system_import:
        lines.append("from pyrung.core.system_points import system")


# ---------------------------------------------------------------------------
# Agent workspace artifacts
# ---------------------------------------------------------------------------

_SYSTEM_BLOCK_VARS = frozenset({"sc", "sd"})


def _generate_cheatsheet() -> str:
    """Load the bundled click-cheatsheet.md from package data."""
    from importlib.resources import files

    return (
        files("pyrung.click.codegen")
        .joinpath("data/click-cheatsheet.md")
        .read_text(encoding="utf-8")
    )


def _generate_agents_md(
    rungs: list[_AnalyzedRung],
    collection: _OperandCollection,
    subroutines: list[_SubroutineInfo],
    machine_name: str,
) -> str:
    """Generate AGENTS.md with program-specific metadata."""
    shape = _build_program_shape(rungs, collection, subroutines)

    sections: list[str] = []
    sections.append(f"# Machine: {machine_name}\n")

    # --- Cheatsheet + program files ---
    sections.append("""\
Read `click-cheatsheet.md` first. The program is ladder logic as Python — it
mirrors what the engineer sees in the Click GUI editor. Some names differ from
Click: Set → `latch`, Math → `calc`.

Then read the program:
- `tags.py` — tag declarations, types, metadata, TagMap
- `main.py` — main rungs and subroutine calls
- `subroutines/` — individual subroutine files
""")

    # --- Program shape ---
    shape_lines = [
        "## Program shape\n",
        f"- Main: {shape['main_rungs']} rungs, {shape['sub_count']} subroutines",
    ]
    for s in shape["subs"]:
        shape_lines.append(f"- `{s['name']}`: {s['rungs']} rungs — {s['desc']}")
    shape_lines.append(f"- Tags: {shape['tag_summary']}")
    sections.append("\n".join(shape_lines) + "\n")

    # --- Tools ---
    sections.append("""\
## Tools

Run `uv sync` first — it creates the project venv and installs pyrung, which
both tools below need. Without it, `pyrung` and `clicknick-cli` aren't available.

Two CLI tools. Chain commands with `;` to avoid repeated process launches.

- **pyrung live** — simulation and analysis (patch, force, step, why, how)
- **clicknick-cli** — push annotations and rung edits back to Click

## Snapshot prerequisite

For diagnosis to be useful, the simulation must be loaded with a snapshot from
the faulted machine. If `why()` shows everything at defaults, ask the engineer
to load a tag dump (Data > Read Data from PLC > All > Save in Click, then
select in ClickNick before starting DAP).

## Working with the program

Read the code before running tools. `main.py` has the scan order and subroutine
calls. Each `subroutines/*.py` file has the logic for one function — state
machines, interlocks, alarms. Read the subroutines relevant to the problem,
not all 30+.

    pyrung live "step 5"
    pyrung live "get StateCurrent Running FaultAlarm"

`step` runs scans. `get` reads tag values. Chain with `;` to patch-step-observe
in one command.

## Analysis tools — escalation ladder

Each level costs more but answers a harder question. Start at the top, escalate
when the answer isn't enough.

### 1. Understand the program (no snapshot needed)

    pyrung live "dataview i:"
    pyrung live "dataview fill"
    pyrung live "upstream ConveyorMotor"
    pyrung live "simplified ConveyorMotor"

`dataview` discovers what exists (`i:` inputs, `t:` terminals, or search by
name). `upstream`/`downstream` trace dependencies. `simplified` resolves
intermediate tags to a Boolean expression over root inputs.

### 2. Diagnose — why is this tag at this value?

    pyrung live "why FaultAlarm"
    pyrung live "why FaultAlarm MotorStall"

`why()` walks backward from a tag and explains how it reached its current value.
Each rung shows its contacts; `*` marks blocked paths. Multiple tags merge into
one unified explanation. This is your first tool on a service call.

### 3. Test a hypothesis — patch, step, observe

`patch` sets a value once. The program runs normally from there.

    pyrung live "patch StartBtn true; step 1; why Running"

`force` pins the value across scans — simulates a stuck sensor or failed
component:

    pyrung live "force FlowSensor false; step 10; why FaultAlarm"

Each `why()` shows what remains. Iterate until you understand the causal chain.

### 4. Projected queries — what-if without running scans

    pyrung live "cause Running to=false"
    pyrung live "effect StartBtn from=false"
    pyrung live "recovers FaultLatch"

`cause` finds what would need to change to reach a value. `effect` traces what
a change would propagate to. `recovers` checks whether a latched bit has a
clear path. No scans needed — these are structural.

### 5. Steer — how do I reach a target state?

    pyrung live "how StateCurrent == 6"
    pyrung live "how Running"
    pyrung live "how StateCurrent == 6 avoid StateCurrent == 3"

`how()` is an experimental steering aid. It reads the program backward, tries
changes on a fork, and reports a replayable path when it finds one. Use `avoid`
to exclude states from the path.

Treat a failed search narrowly: if `how()` does not find a path, that does not
mean the program is broken or the target is unreachable. It can mean only that
the bounded search ran out of safe, evidence-backed actions for this snapshot.
Continue with `why()`, focused patch/step experiments, and direct ladder review.

## Add & annotate tags (edit tags.py, then `tag apply`)

Two ways to change a tag, same landing spot — both stage unsaved edits in the
Address Editor for the engineer to review and Sync.

**Edit `tags.py`** (default, same as you edit rungs) — add a nickname on an
unused address, or annotate a slot with kwargs, then apply the whole diff:

    ds.slot(568, name='Heat_Limit_Ts', uom='degF')
    ds.slot(30, name='StateCurrent', choices={0:'IDLE', 1:'FILLING', 3:'FAULTED'})

    clicknick-cli tag apply     # diff tags.py -> Address Editor, "Changed" filter

`tag apply` lands only the changed rows and opens the Address Editor on them —
the tag counterpart of the rung Copy/paste step.

**One-off `tag set-*`** — a single change without touching the file:

    clicknick-cli "tag set-choices StateCurrent IDLE:0 FILLING:1 FAULTED:3"

### Save order

A save in Click regenerates pyrung_project/ and discards anything not yet
applied — un-pasted rungs, un-Synced tags. **So never save while edits are still
pending.** When a change touches both tags and rungs, ask the engineer which
order they want:

- **Together** — apply tags + rungs, then one save.
- **Tags first** — apply + Sync + save *before* you write any rung code (nothing
  pending to lose).

## Edit and apply logic changes

New logic usually needs a spare address. `unused` returns the next free
address(es) — not used in the program and carrying no content — so you never
collide with an existing tag:

    clicknick-cli unused C            # next free C bit -> C5
    clicknick-cli unused C1031 C1414  # one free bit near each neighbor (distinct)
    clicknick-cli unused DS 3         # 3 consecutive free DS

Browse existing rungs:

    clicknick-cli rung list
    clicknick-cli rung list init
    clicknick-cli rung preview --select r3

Edit `main.py` or `subroutines/*.py` directly. Then:

1. `clicknick-cli rung apply <file>` — convert to ladder CSVs in csv_output/
2. `clicknick-cli rung preview <file>` — opens preview window with diff
3. Engineer clicks Copy, pastes in Click, saves
4. ScrWatcher detects save → auto-regenerates pyrung_project/

Verify every logic change with focused tests and direct patch/step scenarios,
including the failure case. `how()` can provide additional evidence when it
finds a path, but its failure to find one is not a failed verification.

## Reference

- `tags.py`, `main.py`, `subroutines/` — pyrung model of this machine's logic
- `click-cheatsheet.md` — pyrung DSL quick reference (read first)
- `pyrung live help` — full command list
""")

    return "\n".join(sections)


def _build_program_shape(
    rungs: list[_AnalyzedRung],
    collection: _OperandCollection,
    subroutines: list[_SubroutineInfo],
) -> dict:
    """Extract program shape metadata for AGENTS.md."""
    # Tag type distribution (exclude system tags)
    type_counts: dict[str, int] = {}
    for decl in collection.tags.values():
        if decl.block_var in _SYSTEM_BLOCK_VARS:
            continue
        type_counts[decl.tag_type] = type_counts.get(decl.tag_type, 0) + 1

    tag_parts = [f"{count} {typ}" for typ, count in sorted(type_counts.items())]
    tag_summary = ", ".join(tag_parts) if tag_parts else "none"

    subs = []
    for sub in subroutines:
        subs.append(
            {
                "name": sub.name,
                "rungs": len(sub.analyzed),
                "desc": _describe_subroutine(sub),
            }
        )

    return {
        "main_rungs": len(rungs),
        "sub_count": len(subroutines),
        "subs": subs,
        "tag_summary": tag_summary,
    }


def _describe_subroutine(sub: _SubroutineInfo) -> str:
    """One-line description of a subroutine's purpose."""
    if sub.analyzed and sub.analyzed[0].comment:
        return _first_meaningful_line(sub.analyzed[0].comment)
    return sub.name


def _first_meaningful_line(comment: str) -> str:
    """Extract the first non-decoration line from a comment block."""
    for line in comment.splitlines():
        stripped = line.strip()
        if not stripped:
            continue
        # Skip section-heading decoration (===, ---, ###, ***)
        if len(stripped) >= 3 and len(set(stripped) - {" "}) == 1:
            continue
        if stripped.startswith(("#", "=", "-", "*")) and stripped.rstrip("#=-* ") == "":
            continue
        return stripped
    return comment.splitlines()[0].strip()


def _generate_claude_settings() -> str:
    """Generate .claude/settings.json with tool permissions."""
    import json

    config = {
        "permissions": {
            "allow": [
                "Bash(clicknick-cli *)",
                "Bash(pyrung live *)",
            ]
        }
    }
    return json.dumps(config, indent=2) + "\n"


def _generate_conftest() -> str:
    """Generate tests/conftest.py with PLC fixture and coverage plugin."""
    return """\
import pytest
from pyrung import PLC

pytest_plugins = ["pyrung.pytest_plugin"]


@pytest.fixture
def plc(pyrung_coverage):
    from main import logic

    p = PLC(logic, dt=0.1)
    yield p
    pyrung_coverage.collect(p)
"""


def _generate_test_smoke() -> str:
    """Generate tests/test_smoke.py — program loads and steps without error."""
    return """\
def test_program_loads_and_steps(plc):
    plc.step()
    assert plc.current_state.scan_id == 1
"""


# ---------------------------------------------------------------------------
# Shared import helpers
# ---------------------------------------------------------------------------


def _emit_tags_import_line(
    lines: list[str],
    refs: _FileRefs,
    *,
    include_mapping: bool = False,
) -> None:
    """Emit ``from tags import ...`` for the symbols this file references."""
    names: list[str] = []
    if include_mapping:
        names.append("mapping")
    names.extend(sorted(refs.tag_var_names))
    names.extend(sorted(refs.block_var_names))
    names.extend(sorted(refs.range_var_names))
    names.extend(sorted(refs.structure_names))
    names.extend(sorted(refs.tc_clone_var_names))
    names.extend(sorted(refs.used_click_blocks))

    if names:
        lines.append(f"from tags import {', '.join(names)}")
