"""Click PLC System Control (SC) and System Data (SD) predefined nicknames.

These nicknames are specific to AutomationDirect Click PLCs and map
system control relay bits (SC) and system data registers (SD) to
their predefined functions.

Reference: Click PLC User Manual - System Control/Data Tables
"""

SYSTEM_CONTROL_NICKNAMES = {
    1: "_Always_ON",
    2: "_1st_SCAN",
    3: "_SCAN_Clock",
    4: "_10ms_Clock",
    5: "_100ms_Clock",
    6: "_500ms_Clock",
    7: "_1sec_Clock",
    8: "_1min_Clock",
    9: "_1hour_Clock",
    10: "_Mode_Switch",
    11: "_PLC_Mode",
    19: "_PLC Error",
    20: "_I/O Module Error",
    21: "_System Config Error",
    22: "_I/O Config Error",
    23: "_Memory Check Error",
    24: "_Project File Error",
    25: "_Firmware Version Error",
    26: "_Watchdog Timer Error",
    27: "_Lost SDRAM Data",
    28: "_Battery Low Voltage",
    29: "_Battery Replacement",
    30: "_Run Edit Project Error",
    31: "_Sub_CPU_FW_Ver_Error",
    32: "_C2DCM_FW_Ver_Error",
    40: "_Division_Error",
    43: "_Out_of_Range",
    44: "_Address_Error",
    46: "_Math_Operation_Error",
    50: "_PLC_Mode_Change_to_STOP",
    51: "_Watchdog_Timer_Reset",
    53: "_RTC_Date_Change",
    54: "_RTC_Date_Change_Error",
    55: "_RTC_Time_Change",
    56: "_RTC_Time_Change_Error",
    60: "_BT_Disable_Pairing",
    61: "_BT_Activate_Pairing",
    62: "_BT_Paired_Devices",
    63: "_BT_Pairing_SW_State",
    65: "_SD_Eject",
    66: "_SD_Delete_All",
    67: "_SD_Copy_System",
    68: "_SD_Ready_To_Use",
    69: "_SD_Write_Status",
    70: "_SD_Error",
    75: "_WLAN_Reset",
    76: "_Sub_CPU_Reset",
    80: "_WLAN_Ready_Flag",
    81: "_WLAN_Error_Flag",
    82: "_WLAN_Connection_Limit",
    83: "_WLAN_IP_Resolved",
    84: "_WLAN_Connected",
    86: "_WLAN_DHCP_Enabled",
    87: "_WLAN_DNS_Success",
    88: "_WLAN_DNS_Error",
    90: "_Port_1_Ready_Flag",
    91: "_Port_1_Error_Flag",
    92: "_Port_1_Connection_Limit",
    93: "_Port_1_IP_Resolved",
    94: "_Port_1_Link_Flag",
    95: "_Port_1_100MBIT_Flag",
    96: "_Port_1_DHCP_Enabled",
    97: "_Port_1_DNS_Success",
    98: "_Port_1_DNS_Error",
    100: "_Port_2_Ready_Flag",
    101: "_Port_2_Error_Flag",
    102: "_Port_3_Ready_Flag",
    103: "_Port_3_Error_Flag",
    111: "_EIP_Con1_ConOnline",
    112: "_EIP_Con1_Error",
    113: "_EIP_Con1_Originator_Run",
    114: "_EIP_Con2_ConOnline",
    115: "_EIP_Con2_Error",
    116: "_EIP_Con2_Originator_Run",
    120: "_Network Time_Request",
    121: "_Network Time_DST",
    122: "_Network Time_Processing",
    123: "_Network Time_Error",
    131: "_Password_Failure_Detect",
    132: "_Password_Locked_Out",
    133: "_Port1_AL_Enabled",
    134: "_Port1_AL_Denied_Flag",
    135: "_WLAN_AL_Enabled",
    136: "_WLAN_AL_Denied_Flag",
    140: "_S0_P1_Ready_Flag",
    141: "_S0_P1_Error_Flag",
    142: "_S0_P2_Ready_Flag",
    143: "_S0_P2_Error_Flag",
    144: "_S1_P1_Ready_Flag",
    145: "_S1_P1_Error_Flag",
    146: "_S1_P2_Ready_Flag",
    147: "_S1_P2_Error_Flag",
    150: "_PTO_Axis1_Ready_Flag",
    151: "_PTO_Axis2_Ready_Flag",
    152: "_PTO_Axis3_Ready_Flag",
    202: "_Fixed_Scan_Mode",
    203: "_Battery_Installed",
}

SYSTEM_DATA_NICKNAMES = {
    8: "_Sub_Firmware_Version_H",
    9: "_Scan_Counter",
    10: "_Current_Scan_Time",
    11: "_Minimum_Scan_Time",
    12: "_Maximum_Scan_Time",
    13: "_Fixed_Scan_Time_Setup",
    14: "_Interrupt_Scan_Time",
    19: "_RTC_Year(4 digits)",
    20: "_RTC_Year(2 digits)",
    21: "_RTC_Month",
    22: "_RTC_Day",
    23: "_RTC_Day_of_The_Week",
    24: "_RTC_Hour",
    25: "_RTC_Minute",
    26: "_RTC_Second",
    29: "_RTC_New_Year(4 digits)",
    31: "_RTC_New_Month",
    32: "_RTC_New_Day",
    34: "_RTC_New_Hour",
    35: "_RTC_New_Minute",
    36: "_RTC_New_Second",
    40: "_Port1_Received_Data_Len",
    41: "_Port1_No_Comm_Time",
    42: "_Port1_Rcv_Pkt_High_Cnt",
    50: "_Port2_Received_Data_Len",
    51: "_Port2_No_Comm_Time",
    60: "_Port3_Received_Data_Len",
    61: "_Port3_No_Comm_Time",
    62: "_BT_Paired_Device_Count",
    63: "_SD_Total_Memory_L",
    64: "_SD_Total_Memory_H",
    65: "_SD_Free_Memory_L",
    66: "_SD_Free_Memory_H",
    67: "_SD_Used_Memory_L",
    68: "_SD_Used_Memory_H",
    69: "_SD_Error_Information",
    70: "_SD_Log_File_Number",
    80: "_Port1_IP_Address1",
    81: "_Port1_IP_Address2",
    82: "_Port1_IP_Address3",
    83: "_Port1_IP_Address4",
    84: "_Port1_Subnet_Mask1",
    85: "_Port1_Subnet_Mask2",
    86: "_Port1_Subnet_Mask3",
    87: "_Port1_Subnet_Mask4",
    88: "_Port1_Default_Gateway1",
    89: "_Port1_Default_Gateway2",
    90: "_Port1_Default_Gateway3",
    91: "_Port1_Default_Gateway4",
    101: "_EIP_ModuleStatus",
    102: "_EIP_IdentityStatus",
    103: "_EIP_Con1_NodeStatus",
    104: "_EIP_Con1_GeneralStatus",
    105: "_EIP_Con1_ExtendedStatus",
    106: "_EIP_Con1_LostCount",
    107: "_EIP_Con1_DisConCount",
    108: "_EIP_Con1_No_Comm_Time",
    109: "_EIP_Con2_NodeStatus",
    110: "_EIP_Con2_GeneralStatus",
    111: "_EIP_Con2_ExtendedStatus",
    112: "_EIP_Con2_LostCount",
    113: "_EIP_Con2_DisConCount",
    114: "_EIP_Con2_No_Comm_Time",
    131: "_Password_Failed_Count",
    132: "_Port1_AL_Denied_No1_Cnt",
    133: "_WLAN_AL_Denied_No1_Cnt",
    134: "_Port1_AL_Denied_Count",
    135: "_WLAN_AL_Denied_Count",
    140: "_S0_P1_Received_Data_Len",
    141: "_S0_P1_No_Comm_Time",
    142: "_S0_P2_Received_Data_Len",
    143: "_S0_P2_No_Comm_Time",
    144: "_S1_P1_Received_Data_Len",
    145: "_S1_P1_No_Comm_Time",
    146: "_S1_P2_Received_Data_Len",
    147: "_S1_P2_No_Comm_Time",
    188: "_Port1_MAC_Address1",
    189: "_Port1_MAC_Address2",
    190: "_Port1_MAC_Address3",
    191: "_Port1_MAC_Address4",
    192: "_Port1_MAC_Address5",
    193: "_Port1_MAC_Address6",
    194: "_WLAN_ST_MAC_Address1",
    195: "_WLAN_ST_MAC_Address2",
    196: "_WLAN_ST_MAC_Address3",
    197: "_WLAN_ST_MAC_Address4",
    198: "_WLAN_ST_MAC_Address5",
    199: "_WLAN_ST_MAC_Address6",
    200: "_WLAN_IP_Address1",
    201: "_WLAN_IP_Address2",
    202: "_WLAN_IP_Address3",
    203: "_WLAN_IP_Address4",
    204: "_WLAN_Subnet_Mask1",
    205: "_WLAN_Subnet_Mask2",
    206: "_WLAN_Subnet_Mask3",
    207: "_WLAN_Subnet_Mask4",
    208: "_WLAN_Default_Gateway1",
    209: "_WLAN_Default_Gateway2",
    210: "_WLAN_Default_Gateway3",
    211: "_WLAN_Default_Gateway4",
    212: "_WLAN_Signal_Strength",
    213: "_WLAN_Connection_Status",
    214: "_WLAN_No_Comm_Time",
    215: "_WLAN_Rcv_Pkt_High_Cnt",
    216: "_WLAN_Connected_Channel",
    217: "_WLAN_Country_Code",
    218: "_WLAN_No_Connect_Status",
}
